/* Wouf Éducation — leçons chien (Wouf Plus), 7ᵉ série : comportement, langage, situations particulières et complicité.
   Renforcement positif uniquement, aucune contrainte physique ni punition.
   Contenu à faire relire par un vétérinaire ou un comportementaliste diplômé avant communication commerciale. */
LESSONS.push(

{ id: 'langage', free: false, icon: '🗣️', cat: 'Émotions', title: 'Comprendre son chien : le langage du corps', from: 8, dur: '10 min d’observation par jour', span: '2 à 3 semaines', level: 'Essentiel',
  goal: 'Vous savez lire les émotions de votre chien (détente, joie, inconfort, peur, menace) et réagir avant qu’une situation ne dégénère.',
  why: 'Le chien parle avec tout son corps : oreilles, queue, regard, posture, bouche. Beaucoup de morsures arrivent après des signaux d’inconfort ignorés ou punis. Apprendre à les lire est la base d’une relation sereine et sûre, notamment avec les enfants.',
  need: ['Du temps d’observation', 'Votre téléphone pour filmer quelques situations', 'Le journal de Wouf pour noter vos observations'],
  steps: [
    { t: 'Le chien détendu', min: 10, b: 'Observez votre chien au calme : bouche entrouverte, langue visible, muscles souples, oreilles en position naturelle, queue à hauteur normale et mouvements amples. C’est votre point de référence. Filmez-le pour comparer ensuite.', crit: 'Vous décrivez 4 signes de détente chez votre chien.' },
    { t: 'Les signaux d’apaisement', min: 10, b: 'Léchage de truffe, bâillement hors fatigue, détournement de la tête, reniflage soudain du sol, ralentissement, s’ébrouer comme en sortant de l’eau : le chien dit « je suis un peu mal à l’aise » ou « calmons-nous ». Repérez-les chez le vétérinaire, en croisant un chien, pendant un câlin.', crit: 'Vous repérez 3 signaux d’apaisement dans une journée.' },
    { t: 'La peur', min: 10, b: 'Oreilles plaquées, queue basse ou entre les pattes, corps bas, poids sur l’arrière, blanc de l’œil visible (« œil de baleine »), tremblements, halètement sans chaleur, fuite ou immobilité. Un chien qui a peur a besoin de distance, pas d’être forcé ni rassuré en le tenant.', crit: 'Vous identifiez 5 signes de peur.' },
    { t: 'L’échelle de la menace', min: 10, b: 'Avant de mordre, la plupart des chiens se figent, fixent, relèvent les babines, grognent, puis claquent des dents. Le grognement est un avertissement précieux : ne le punissez jamais, sinon le chien mordra sans prévenir. Éloignez-vous calmement et identifiez la cause.', crit: 'Vous connaissez les étapes de l’escalade et savez vous éloigner.' },
    { t: 'La queue qui remue ne veut pas toujours dire « content »', min: 10, b: 'Une queue haute et raide qui vibre peut traduire l’excitation ou la tension ; une queue basse qui balaie lentement, l’hésitation. Lisez toujours le corps entier et le contexte, jamais un seul signe.', crit: 'Vous interprétez une situation en observant 3 parties du corps.' }
  ],
  plan: [['Jours 1 à 3', 'Observer et filmer votre chien détendu.'], ['Jours 4 à 7', 'Repérer les signaux d’apaisement au quotidien.'], ['Semaine 2', 'Identifier les signes de peur et leurs déclencheurs.'], ['Semaine 3', 'Anticiper : s’éloigner dès les premiers signaux.']],
  next: ['Apprendre ces signaux aux enfants de la maison.', 'Suivre « Chien craintif avec les inconnus » ou « Chien réactif en laisse » si vous repérez souvent de la peur.', 'Lire les ouvrages sur les signaux d’apaisement (par exemple ceux de Turid Rugaas).'],
  mistakes: ['Punir un grognement : on supprime l’avertissement, pas l’émotion.', 'Croire qu’une queue qui remue signifie toujours la joie.', 'Faire un câlin serré à un chien qui détourne la tête et se lèche la truffe.', 'Forcer un chien qui a peur à « affronter » ce qui l’effraie.'],
  faq: [['Il bâille chez le vétérinaire, il est fatigué ?', 'Plus probablement un signal de stress : récompensez le calme et offrez-lui de la distance si possible.'], ['Mon chien grogne quand on le dérange sur le canapé.', 'Il exprime un inconfort : ne le punissez pas, apprenez-lui à descendre contre une récompense et consultez un professionnel si cela s’aggrave.']],
  test: 'Devant 3 vidéos ou situations réelles, vous identifiez correctement l’émotion du chien et l’action à mener.', safety: 'Un chien qui a grogné ou mordu doit être évalué par un vétérinaire (douleur ?) et un comportementaliste diplômé. Ne laissez jamais un enfant seul avec un chien, même s’il ne montre aucun signe d’inconfort.' },

{ id: 'decompression', free: false, icon: '🌿', cat: 'Balades', title: 'La balade de reniflage : la sortie qui apaise', from: 10, dur: '20 à 45 min × 2 par semaine', span: 'Toute la vie', level: 'Tous niveaux',
  goal: 'Votre chien profite régulièrement d’une balade lente, où il renifle librement, et revient plus calme et plus détendu qu’une course au parc.',
  why: 'Renifler est l’activité la plus naturelle et la plus apaisante pour un chien : elle abaisse le rythme cardiaque, fatigue le cerveau et réduit le stress. Une balade « de décompression » au rythme du chien, sans exigences, est précieuse pour les chiens anxieux, réactifs, jeunes ou en convalescence.',
  need: ['Une longe de 5 mètres et un harnais', 'Un lieu calme (forêt, champ, parc peu fréquenté)', 'De l’eau', 'Pas d’horaire serré'],
  steps: [
    { t: 'Choisir le bon endroit', min: 5, b: 'Cherchez un lieu riche en odeurs et pauvre en déclencheurs : chemin forestier, prairie, bord de champ, parc tôt le matin. Évitez les zones de passage, les routes et les parcs canins bondés.', crit: 'Vous avez repéré 2 lieux calmes adaptés.' },
    { t: 'Le chien mène', min: 20, b: 'Sur longe, laissez le chien choisir le chemin et le rythme. Ne l’interrompez pas quand il renifle, même longtemps au même endroit : c’est le but. Vous suivez, sans téléphone si possible, en observant.', crit: 'Il renifle librement pendant 20 minutes.' },
    { t: 'Aucune exigence', min: 20, b: 'Pas d’ordres, pas d’exercices, pas de jeu excitant. Juste quelques rappels récompensés si nécessaire, puis retour à l’exploration. Semez quelques friandises dans l’herbe avec « Cherche ! » pour relancer le flair.', crit: 'Vous terminez la balade sans avoir donné d’ordre inutile.' },
    { t: 'Observer l’effet', min: 5, b: 'Notez son état au retour : sieste profonde, calme, meilleure attention ? Comparez avec les jours de balades rapides ou de parc canin. Beaucoup de propriétaires découvrent que 30 minutes de reniflage fatiguent plus qu’une heure de course.', crit: 'Vous observez un chien plus calme au retour.' },
    { t: 'L’intégrer à la semaine', min: 5, b: 'Prévoyez au moins deux balades de décompression par semaine, davantage pour un chien stressé. Les autres sorties peuvent être plus sportives ou éducatives. Enregistrez-les dans les balades Wouf pour garder un équilibre.', crit: 'Deux balades de reniflage sont prévues chaque semaine.' }
  ],
  plan: [['Semaine 1', 'Repérer les lieux, première balade de 20 minutes.'], ['Semaine 2', 'Deux balades de 30 minutes, avec quelques « Cherche ! ».'], ['Semaine 3', 'Allonger à 45 minutes selon l’énergie du chien.'], ['Ensuite', 'Garder deux balades de reniflage par semaine.']],
  next: ['Suivre « Cherche ! Les jeux d’odorat ».', 'Suivre « La longe : de la liberté en toute sécurité ».', 'Suivre « Chien réactif en laisse » en utilisant ces balades comme sorties sans stress.'],
  mistakes: ['Tirer le chien pour avancer.', 'Transformer la balade en séance d’obéissance.', 'Choisir un lieu bruyant ou bondé.', 'Penser que la balade est inutile parce qu’on a peu marché.'],
  faq: [['Il mange tout ce qu’il trouve.', 'Travaillez « Laisse-le » et voyez la leçon « Manger ce qui traîne » ; évitez les zones de déchets.'], ['On n’avance pas.', 'C’est normal : la distance n’est pas l’objectif, c’est le reniflage.']],
  test: 'Après une balade de reniflage de 30 minutes, votre chien fait une longue sieste calme au retour.', safety: 'Vérifiez l’absence de tiques et d’épillets (graminées) au retour, surtout entre les doigts et dans les oreilles. Traitement antiparasitaire à jour indispensable en forêt.' },

{ id: 'sourd', free: false, icon: '🤟', cat: 'Soins', title: 'Chien sourd ou malvoyant : éduquer autrement', from: 8, dur: '5 min × 3 par jour', span: '4 à 8 semaines', level: 'Utile',
  goal: 'Votre chien sourd ou malvoyant comprend vos signaux (gestes, vibrations, toucher, odeurs), vient à vous et vit une vie sereine et sûre.',
  why: 'Un chien sourd ou aveugle, de naissance ou avec l’âge, peut apprendre autant qu’un autre : il faut simplement changer de canal de communication. Adapter le quotidien et les signaux évite les sursauts, la peur et les accidents.',
  need: ['Friandises', 'Une lampe de poche ou une petite lumière (chien sourd)', 'Des odeurs ou textures repères (chien malvoyant)', 'Un harnais et une médaille « Je suis sourd » ou « Je suis aveugle »'],
  steps: [
    { t: 'Un marqueur adapté', min: 5, b: 'Chien sourd : remplacez le « Oui ! » par un geste clair (pouce levé ou main ouverte) ou un flash lumineux, suivi d’une friandise. Chien malvoyant : utilisez un mot bref et toujours le même, ou un léger contact sur l’épaule. Chargez ce marqueur comme d’habitude, 20 répétitions.', crit: 'Il réagit à votre marqueur par une attente de friandise.' },
    { t: 'Attirer l’attention sans surprendre', min: 5, b: 'Chien sourd : tapez du pied au sol (vibration), allumez et éteignez la lumière, ou touchez toujours au même endroit (épaule). Chien aveugle : parlez avant de le toucher. Récompensez chaque fois qu’il se tourne vers vous.', crit: 'Il se tourne vers vous au signal d’attention, 8 fois sur 10.' },
    { t: 'Les signes des ordres', min: 5, b: 'Pour un chien sourd, associez un geste à chaque consigne : assis (main qui monte), couché (main qui descend), viens (bras ramené vers la poitrine), stop (main ouverte). Pour un chien malvoyant, utilisez des mots clairs, toujours identiques, et des repères tactiles.', crit: 'Il répond à 3 signes ou mots distincts.' },
    { t: 'Adapter la maison', min: 10, b: 'Chien malvoyant : ne déplacez pas les meubles, protégez les escaliers, utilisez des tapis de textures différentes comme repères (évitez les huiles essentielles, irritantes pour les chiens). Chien sourd : réveillez-le doucement en posant la main près de son nez ou par la vibration.', crit: 'La maison est sécurisée et les repères installés.' },
    { t: 'La sécurité dehors', min: 10, b: 'Gardez-le en laisse ou longe dans les zones non closes : il n’entendra pas votre rappel ni une voiture. Médaille indiquant sa surdité ou sa cécité, harnais visible. Prévenez les personnes qui l’approchent.', crit: 'Il sort toujours identifié et en sécurité.' }
  ],
  plan: [['Semaine 1', 'Marqueur adapté et signal d’attention.'], ['Semaines 2 et 3', 'Trois consignes en signes ou mots clairs.'], ['Semaines 4 et 5', 'Aménagements de la maison et repères.'], ['Semaines 6 à 8', 'Sorties sécurisées, rappel sur longe.']],
  next: ['Faire un bilan auditif ou ophtalmologique chez le vétérinaire pour connaître l’évolution.', 'Suivre « La longe : de la liberté en toute sécurité ».', 'Suivre « Cherche ! Les jeux d’odorat » : le flair compense beaucoup.'],
  mistakes: ['Toucher ou réveiller brusquement le chien : il peut sursauter ou mordre par réflexe.', 'Le lâcher dans un espace non clos.', 'Déplacer sans cesse les meubles pour un chien aveugle.', 'Penser qu’il ne peut pas apprendre.'],
  faq: [['Il sursaute quand je le touche.', 'Prévenez-le d’abord (vibration au sol, main près du nez) et récompensez après chaque contact.'], ['Mon chien vieillissant devient sourd.', 'Commencez les signes dès maintenant, en les associant à vos mots habituels : il les reconnaîtra quand l’audition baissera.']],
  test: 'Il se tourne vers vous au signal d’attention et répond à 3 consignes par signes ou mots, 8 fois sur 10.', safety: 'Une perte soudaine de la vue ou de l’audition, ou un œil douloureux, trouble ou rouge, nécessite une consultation rapide.' },

{ id: 'convalescence', free: false, icon: '🩹', cat: 'Soins', title: 'Repos forcé et collerette : occuper un chien en convalescence', from: 8, dur: 'Pendant la convalescence', span: '1 à 8 semaines', level: 'Utile',
  goal: 'Votre chien respecte le repos prescrit après une opération ou une blessure, accepte la collerette ou le body, et reste calme et occupé sans se blesser.',
  why: 'Après une stérilisation, une chirurgie orthopédique ou une blessure, le repos strict conditionne la guérison. Mais un chien qui s’ennuie saute, court, lèche sa plaie. L’occupation mentale et l’habituation à la collerette rendent cette période plus facile pour tout le monde.',
  need: ['Collerette ou body post-opératoire adapté', 'Parc ou caisse (si prescrit)', 'Jouets à mâcher, tapis de léchage, jeux de flair', 'Ordonnance et consignes du vétérinaire'],
  steps: [
    { t: 'Suivre les consignes du vétérinaire', min: 5, b: 'Notez précisément : durée du repos, sorties autorisées (en laisse, pipi seulement ?), escaliers, canapé, soins de plaie, médicaments. Mettez des rappels dans Wouf. En cas de doute, appelez le vétérinaire plutôt que de deviner.', crit: 'Les consignes et les traitements sont notés et programmés.' },
    { t: 'Habituer à la collerette', min: 5, b: 'Si possible avant l’opération : présentez la collerette avec des friandises, glissez-la quelques secondes, puis minutes. Après l’opération, surélevez gamelle et eau, dégagez les passages. Le body post-opératoire est parfois une alternative plus confortable : demandez au vétérinaire.', crit: 'Il mange, boit et se couche avec la collerette.' },
    { t: 'Un espace de repos sécurisé', min: 10, b: 'Installez une zone restreinte (parc, pièce, caisse) sans possibilité de sauter : pas de canapé, tapis antidérapants, couchage confortable. Bloquez les escaliers. Portez-le si besoin pour les marches.', crit: 'Il ne peut ni sauter ni courir dans son espace.' },
    { t: 'Occuper l’esprit', min: 15, b: 'Remplacez les balades par des jeux calmes : tapis de léchage, jouets distributeurs, recherche de friandises à portée, mâchouilles, petits tours statiques (touche, regard, donne la patte). 3 à 4 courtes séances par jour suffisent à fatiguer mentalement.', crit: 'Il a 3 activités calmes par jour.' },
    { t: 'La reprise progressive', min: 10, b: 'Reprenez l’activité selon le vétérinaire : sorties en laisse de 5 minutes, puis 10, 15. Pas de course, de jeu avec d’autres chiens ni de saut avant le feu vert. Observez la plaie et la marche chaque jour.', crit: 'La reprise suit le calendrier validé par le vétérinaire.' }
  ],
  plan: [['Avant l’opération', 'Habituation à la collerette et à l’espace de repos.'], ['Semaine 1', 'Repos strict, soins, 3 activités calmes par jour.'], ['Semaines 2 à 4', 'Jeux de flair et tours statiques, sorties courtes en laisse.'], ['Ensuite', 'Reprise progressive selon le vétérinaire.']],
  next: ['Suivre « Jeux d’intelligence : occuper l’esprit à la maison ».', 'Suivre « Le protocole de relaxation ».', 'Suivre « La gym du chien » après accord du vétérinaire, pour la rééducation.'],
  mistakes: ['Retirer la collerette « parce qu’il est malheureux » : il peut rouvrir sa plaie en quelques minutes.', 'Laisser le chien courir ou sauter trop tôt.', 'Arrêter les médicaments avant la fin.', 'Ne rien lui proposer à faire.'],
  faq: [['Il lèche sa plaie malgré tout.', 'Vérifiez la taille de la collerette ou demandez un body ; une plaie léchée s’infecte.'], ['Il pleure et s’agite.', 'Il peut avoir mal : appelez le vétérinaire pour ajuster l’antidouleur.']],
  test: 'Il respecte le repos, garde sa collerette, et reste calme grâce à 3 activités par jour jusqu’au contrôle.', safety: 'Consultez rapidement en cas de plaie rouge, gonflée, qui suinte, sent mauvais ou s’ouvre, de fièvre, de vomissements ou si le chien ne mange plus.' },

{ id: 'ramasse', free: false, icon: '🚯', cat: 'Savoir-vivre', title: 'Manger ce qui traîne : déchets, crottes et objets', from: 10, dur: '5 min × 2 par jour', span: '3 à 6 semaines', level: 'Important',
  goal: 'Votre chien ignore déchets, crottes et objets au sol en balade, les laisse sur « Laisse-le », et se tourne vers vous au lieu de ramasser.',
  why: 'Manger ce qui traîne est dangereux : os cuits, poisons, raticides, médicaments, objets qui bloquent l’intestin. La coprophagie (manger des excréments) est fréquente, surtout chez le jeune chien, et n’est pas un « vice » : elle a des causes (ennui, faim, habitude, parfois santé). On la gère par la prévention et l’apprentissage.',
  need: ['Friandises de haute valeur', 'Longe ou laisse', 'Muselière panier conditionnée (si le chien avale tout)', 'Un rendez-vous vétérinaire si la coprophagie est importante'],
  steps: [
    { t: 'Écarter une cause de santé', min: 10, b: 'Parlez-en au vétérinaire : parasites, alimentation insuffisante ou mal digérée, faim, certains troubles peuvent augmenter l’envie de manger n’importe quoi. Ramassez immédiatement les crottes dans le jardin : moins d’occasions, moins d’habitude.', crit: 'Une cause médicale a été écartée et le jardin est propre.' },
    { t: 'Apprendre « Laisse-le » à la maison', min: 5, b: 'Friandise dans la main fermée : il se détourne, « Oui ! », récompense de l’autre main. Puis friandise au sol couverte par le pied, puis découverte. Voir la leçon « Laisse-le et Donne ». La récompense doit toujours être meilleure que ce qu’il laisse.', crit: 'Il laisse une friandise au sol sur « Laisse-le », 8 fois sur 10.' },
    { t: 'Le mettre en place en balade', min: 10, b: 'Repérez les déchets avant lui. Dites « Laisse-le » avant qu’il n’atteigne l’objet, récompensez généreusement quand il vous regarde. Gardez-le en laisse courte dans les zones à risque, et passez à distance.', crit: 'Il laisse 3 déchets en balade sur signal.' },
    { t: 'Récompenser le regard vers vous', min: 10, b: 'Chaque fois qu’il passe devant quelque chose sans le prendre, ou qu’il vous regarde, récompensez. Il apprend que passer à côté est plus payant que ramasser.', crit: 'Il vous regarde spontanément en passant près d’un déchet.' },
    { t: 'La muselière si nécessaire', min: 5, b: 'Pour un chien qui avale tout et rapidement, une muselière panier bien conditionnée (il peut boire et haleter) est une vraie sécurité en attendant que l’apprentissage progresse. Ce n’est pas une punition.', crit: 'Il porte une muselière panier en balade sans stress, si besoin.' }
  ],
  plan: [['Semaine 1', 'Bilan vétérinaire, jardin propre, « Laisse-le » à la maison.'], ['Semaine 2', '« Laisse-le » avec friandise au sol.'], ['Semaines 3 et 4', 'Mise en place en balade, laisse courte en zone à risque.'], ['Semaines 5 et 6', 'Récompense du regard spontané ; muselière si nécessaire.']],
  next: ['Suivre « Laisse-le et Donne : ne pas ramasser, savoir lâcher ».', 'Suivre « Muselière : un conditionnement positif ».', 'Suivre « Jeux d’intelligence » pour réduire l’ennui.'],
  mistakes: ['Lui courir après pour récupérer l’objet : il avale plus vite.', 'Crier : il apprend à ramasser discrètement.', 'Oublier de ramasser les crottes du jardin.', 'Mettre des produits « dégoûtants » dans la nourriture sans avis vétérinaire.'],
  faq: [['Il a avalé quelque chose de dangereux.', 'Appelez immédiatement votre vétérinaire ou un centre antipoison vétérinaire. Ne le faites pas vomir sans avis.'], ['Il mange les crottes de chat.', 'Placez la litière hors de sa portée (porte à chatière, bac en hauteur).']],
  test: 'Au cours d’une balade, il laisse 5 déchets ou crottes sur « Laisse-le » et se tourne vers vous.', safety: 'Raticides, médicaments, chocolat, raisins, xylitol, os cuits et objets (chaussette, jouet) avalés sont des urgences : appelez un vétérinaire immédiatement. Signes d’obstruction : vomissements répétés, ventre douloureux, absence de selles.' },

{ id: 'creuser', free: false, icon: '🕳️', cat: 'Savoir-vivre', title: 'Le chien qui creuse le jardin', from: 12, dur: '10 min × 1 par jour', span: '3 à 6 semaines', level: 'Utile',
  goal: 'Votre chien creuse uniquement dans son coin autorisé (bac à fouille) et laisse le reste du jardin tranquille.',
  why: 'Creuser est un comportement naturel : chercher des odeurs ou des rongeurs, se rafraîchir, enterrer un trésor, s’occuper quand on s’ennuie. Certaines races (terriers, nordiques) adorent creuser. Plutôt que d’interdire, on offre un endroit dédié et on répond au besoin qui se cache derrière.',
  need: ['Un bac à sable ou un coin de terre meuble', 'Jouets et friandises à enterrer', 'Grillage ou pierres pour protéger les zones sensibles', 'Un coin d’ombre et de l’eau'],
  steps: [
    { t: 'Comprendre pourquoi il creuse', min: 10, b: 'Observez quand et où : au soleil (il cherche la fraîcheur), le long de la clôture (envie de sortir), dans un coin précis (odeur de rongeur), quand il est seul (ennui). La solution dépend de la cause.', crit: 'Vous avez identifié la cause principale.' },
    { t: 'Créer un bac à fouille', min: 20, b: 'Installez un bac à sable ou délimitez un coin de terre meuble, dans un endroit ombragé. Enterrez devant lui des jouets et friandises, à peine recouverts au début. Encouragez-le : « Creuse ! ». Récompensez chaque trouvaille.', crit: 'Il creuse volontiers dans le bac pour trouver les trésors.' },
    { t: 'Rendre le bac plus intéressant que le reste', min: 5, b: 'Changez les trésors souvent, enterrez-les plus profond, variez les jouets. Pendant ce temps, rendez les zones interdites moins attrayantes : grillage enterré, grosses pierres, massifs protégés.', crit: 'Il se dirige de lui-même vers le bac.' },
    { t: 'Rediriger sans punir', min: 5, b: 'Si vous le surprenez à creuser ailleurs, appelez-le joyeusement vers le bac et récompensez quand il y creuse. Ne punissez pas les trous découverts après coup : il ne comprendra pas le lien.', crit: 'Il accepte d’être redirigé vers le bac, 8 fois sur 10.' },
    { t: 'Répondre au vrai besoin', min: 10, b: 'Fraîcheur : ombre, eau, tapis rafraîchissant. Ennui : plus de balades, jeux de flair, compagnie. Envie de sortir : vérifiez la clôture (voir la leçon sur les fugues). Un chien comblé creuse beaucoup moins.', crit: 'Le besoin à l’origine du creusage est comblé.' }
  ],
  plan: [['Semaine 1', 'Observer la cause, installer le bac à fouille.'], ['Semaine 2', 'Jeux de trésors quotidiens dans le bac.'], ['Semaines 3 et 4', 'Protéger les zones sensibles, rediriger.'], ['Semaines 5 et 6', 'Répondre au besoin de fond (ombre, activité, clôture).']],
  next: ['Suivre « Cherche ! Les jeux d’odorat ».', 'Suivre « Fugues : clôture, portail et prévention ».', 'Suivre « Jeux d’intelligence : occuper l’esprit à la maison ».'],
  mistakes: ['Punir un trou découvert après coup.', 'Mettre les déjections du chien dans les trous (pratique inutile et insalubre).', 'Le laisser seul toute la journée au jardin.', 'Utiliser des produits répulsifs toxiques.'],
  faq: [['Il creuse sous la clôture.', 'Enterrez du grillage en « L » vers l’intérieur ou des pierres le long de la clôture, et voyez la leçon sur les fugues.'], ['Il mange la terre.', 'Parlez-en au vétérinaire : cela peut révéler une carence ou un trouble digestif.']],
  test: 'Pendant 2 semaines, il ne creuse plus que dans son bac à fouille.', safety: 'Évitez les engrais, anti-limaces, insecticides et produits de jardin toxiques. Certains paillages (cacao) sont dangereux pour le chien.' },

{ id: 'fugue', free: false, icon: '🚪', cat: 'Sécurité', title: 'Fugues : clôture, portail et prévention', from: 12, dur: '10 min × 1 par jour', span: '3 à 6 semaines', level: 'Important',
  goal: 'Votre chien ne s’échappe plus du jardin ni par la porte d’entrée, attend votre signal pour sortir, et est identifié pour être retrouvé s’il fugue.',
  why: 'Un chien qui fugue risque l’accident, la perte, le conflit avec d’autres animaux ou les amendes. Les fugues ont des causes précises : femelle en chaleur à proximité, ennui, peur (orages, pétards), instinct de chasse. Il faut sécuriser, combler le besoin et éduquer.',
  need: ['Clôture adaptée à la taille et aux capacités du chien', 'Identification (puce) à jour et médaille avec votre numéro', 'Friandises', 'Le mot de libération « Libre ! »'],
  steps: [
    { t: 'Sécuriser le jardin', min: 30, b: 'Vérifiez toute la clôture : hauteur (un chien sportif saute 1,5 mètre), trous, grillage enterré (creusage), portail qui se referme bien. Supprimez les « tremplins » (bancs, tas de bois) près de la clôture.', crit: 'La clôture est vérifiée et sans point faible.' },
    { t: 'La porte d’entrée : attendre le signal', min: 5, b: 'Apprenez à attendre à la porte (voir la leçon « Attendre »). La porte ne s’ouvre que s’il reste en place, il ne sort qu’après « Libre ! ». Travaillez avec tous les membres de la famille et les visiteurs.', crit: 'Il reste en place porte ouverte, 9 fois sur 10.' },
    { t: 'Comprendre et combler la cause', min: 10, b: 'Mâle attiré par une femelle : parlez de la stérilisation avec le vétérinaire. Ennui : plus de balades et de jeux. Peur : un coin refuge à la maison les jours d’orage ou de feux d’artifice. Chasse : voir la leçon sur l’instinct de chasse.', crit: 'Vous avez agi sur la cause principale.' },
    { t: 'Un rappel à la maison ultra-positif', min: 5, b: 'Au jardin, appelez-le souvent pour une récompense spéciale, et relâchez-le. Il apprend que le jardin et votre voix sont le meilleur endroit.', crit: 'Il revient au rappel dans le jardin 9 fois sur 10.' },
    { t: 'Se préparer au pire', min: 10, b: 'Vérifiez que la puce est enregistrée à votre adresse et numéro actuels, médaille avec téléphone sur le collier ou harnais. Gardez une photo récente. En cas de fugue, utilisez la page « Animal perdu » de Wouf.', crit: 'L’identification est à jour et une photo récente est prête.' }
  ],
  plan: [['Semaine 1', 'Vérifier la clôture et l’identification.'], ['Semaine 2', 'Attendre à la porte, avec toute la famille.'], ['Semaines 3 et 4', 'Combler la cause (stérilisation, ennui, peur, chasse).'], ['Semaines 5 et 6', 'Rappel au jardin ultra-positif.']],
  next: ['Suivre « Rappel : « Ici ! » fiable ».', 'Suivre « Attendre : la porte, la gamelle, la voiture ».', 'Suivre « Bruits forts, orages et pétards ».'],
  mistakes: ['Punir le chien quand il revient d’une fugue : il reviendra encore moins vite.', 'Laisser le portail ouvert « juste une minute ».', 'Laisser un chien seul au jardin toute la journée.', 'Ne pas mettre à jour l’identification après un déménagement.'],
  faq: [['Il saute la clôture.', 'Rehaussez-la ou inclinez le haut vers l’intérieur, et répondez à la cause de la fugue.'], ['Il fugue les soirs de feux d’artifice.', 'Gardez-le à l’intérieur ces jours-là, fenêtres fermées, et préparez-le avec la leçon sur les bruits.']],
  test: 'Pendant 1 mois, aucune fugue : il attend « Libre ! » à la porte et revient au rappel au jardin.', safety: 'Si votre chien a disparu : prévenez immédiatement le fichier d’identification, les vétérinaires, la mairie, la fourrière et les voisins, et utilisez la page « Animal perdu » de Wouf.' },

{ id: 'canape', free: false, icon: '🛋️', cat: 'Savoir-vivre', title: 'Règles de la maison : canapé, lit et pièces interdites', from: 8, dur: '3 min × 3 par jour', span: '2 à 4 semaines', level: 'Utile',
  goal: 'Votre chien respecte les règles choisies par la famille : il monte sur le canapé uniquement sur invitation (ou jamais), descend sur « Descends » et reste hors des pièces interdites.',
  why: 'Il n’y a pas de bonne ou de mauvaise règle : un chien peut très bien dormir sur le canapé. Ce qui compte, c’est la cohérence : si les règles changent selon les personnes ou les jours, le chien ne comprend pas. On lui apprend des consignes claires, sans conflit.',
  need: ['Un couchage confortable et attractif à lui', 'Friandises', 'Une barrière pour les pièces interdites', 'Une réunion de famille pour fixer les règles'],
  steps: [
    { t: 'Fixer les règles ensemble', min: 10, b: 'Décidez en famille : canapé autorisé, sur invitation, ou jamais ? Lit ? Pièces interdites ? Tout le monde applique la même règle. Notez-la pour les invités et le gardien (fiche gardien).', crit: 'Les règles sont décidées et partagées par toute la famille.' },
    { t: 'Un couchage plus attirant', min: 5, b: 'Installez un panier confortable près du canapé, avec couverture et mâchouille. Récompensez chaque fois qu’il s’y installe. S’il a sa place à côté de vous, le canapé devient moins nécessaire.', crit: 'Il s’installe volontairement dans son panier près de vous.' },
    { t: 'Apprendre « Descends »', min: 3, b: 'Lancez une friandise au sol en disant « Descends ». Quand il descend, « Oui ! » et récompense. Au bout de quelques répétitions, dites « Descends » avant de lancer. Pas de traction sur le collier : cela peut provoquer un conflit.', crit: 'Il descend du canapé sur « Descends », 8 fois sur 10.' },
    { t: 'Monter sur invitation', min: 3, b: 'Si le canapé est autorisé sur invitation : il attend au sol, vous tapotez le coussin en disant « Monte », il monte. Sans invitation, il ne monte pas : lancez une friandise au sol quand il attend.', crit: 'Il attend l’invitation au pied du canapé.' },
    { t: 'Les pièces interdites', min: 5, b: 'Utilisez une barrière au début. Récompensez quand il reste de l’autre côté. Plus tard, apprenez-lui à attendre sur le seuil (voir « Attendre »). La gestion (porte fermée) reste la solution la plus simple.', crit: 'Il reste hors de la pièce interdite, porte ouverte.' }
  ],
  plan: [['Jour 1', 'Fixer les règles en famille, installer le panier.'], ['Semaine 1', '« Descends » avec friandise lancée.'], ['Semaine 2', 'Monter sur invitation, attendre au sol.'], ['Semaines 3 et 4', 'Pièces interdites : barrière puis attente sur le seuil.']],
  next: ['Suivre « La Place : un tapis pour se calmer ».', 'Suivre « Attendre : la porte, la gamelle, la voiture ».', 'Suivre « Partage serein : prévenir la garde de ressources » si le chien grogne sur le canapé.'],
  mistakes: ['Des règles différentes selon les personnes.', 'Tirer le chien par le collier pour le faire descendre.', 'Le punir de monter alors qu’on l’y a invité la veille.', 'Oublier de lui offrir un couchage vraiment confortable.'],
  faq: [['Il grogne quand on veut le faire descendre.', 'N’insistez pas physiquement : utilisez la friandise lancée et voyez la leçon sur la garde de ressources ; consultez un professionnel si c’est fréquent.'], ['Il monte quand nous sommes absents.', 'Fermez la porte du salon, ou couvrez le canapé et offrez-lui un couchage plus agréable.']],
  test: 'Il descend du canapé sur « Descends », attend l’invitation pour monter et reste hors des pièces interdites, 8 fois sur 10.', safety: 'Évitez les sauts répétés depuis un lit ou un canapé haut pour les chiots, les petits chiens au dos fragile (teckel, bouledogue) et les seniors : utilisez une rampe ou une marche.' },

{ id: 'parc-canin', free: false, icon: '🐕', cat: 'Émotions', title: 'Jouer avec les autres chiens : parc canin et bonnes manières', from: 12, dur: '15 à 30 min × 2 par semaine', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien joue sainement avec des chiens compatibles, respecte les pauses, revient à vous au rappel, et vous savez repérer quand il faut intervenir.',
  why: 'Le jeu entre chiens est précieux, mais pas tous les chiens aiment jouer avec tous les chiens, et les parcs canins peuvent devenir stressants. Savoir distinguer le bon jeu d’une situation qui dégénère protège votre chien et sa confiance.',
  need: ['Friandises de haute valeur', 'Un chien ami calme et bien sociable', 'Un lieu peu fréquenté aux premières fois', 'Vaccins et antiparasitaires à jour'],
  steps: [
    { t: 'Choisir de bons partenaires', min: 10, b: 'Commencez par des chiens connus, calmes et d’un gabarit et d’un style de jeu compatibles. Un chiot a besoin d’adultes patients. Évitez les heures d’affluence au parc canin, et observez le groupe avant d’entrer.', crit: 'Vous avez identifié 1 ou 2 chiens partenaires fiables.' },
    { t: 'Reconnaître le bon jeu', min: 15, b: 'Corps souples, mouvements rebondissants, invitations au jeu (arrière-train levé), inversion des rôles (chacun poursuit à son tour), pauses spontanées. Le jeu doit être réciproque : chaque chien revient chercher l’autre.', crit: 'Vous repérez l’inversion des rôles et les pauses.' },
    { t: 'Repérer quand il faut intervenir', min: 10, b: 'Un chien se fait poursuivre sans jamais inverser, se cache, a la queue basse, cherche à fuir ; ou un groupe de chiens s’acharne sur un seul ; ou le jeu devient raide et silencieux. Intervenez calmement : rappel ou séparation douce, pause.', crit: 'Vous interrompez un jeu déséquilibré avant qu’il ne dégénère.' },
    { t: 'Le rappel au milieu du jeu', min: 10, b: 'Appelez votre chien au milieu du jeu, récompensez généreusement, puis relâchez-le immédiatement avec « Va jouer ! ». Il apprend que revenir ne signifie pas la fin du plaisir.', crit: 'Il revient au rappel au milieu du jeu, 8 fois sur 10.' },
    { t: 'Savoir partir', min: 5, b: 'Partez avant la fatigue ou la surexcitation. Si votre chien est inquiet ou si l’ambiance se tend, partez sans hésiter. Beaucoup de chiens adultes préfèrent un ou deux amis à un grand groupe : respectez sa préférence.', crit: 'Vous partez quand votre chien montre des signes de fatigue ou de stress.' }
  ],
  plan: [['Semaine 1', 'Rencontres avec un chien ami calme en terrain neutre.'], ['Semaines 2 et 3', 'Observation du jeu, repérage de l’inversion des rôles.'], ['Semaines 4 et 5', 'Rappel au milieu du jeu, pauses.'], ['Semaine 6', 'Petits groupes, heures creuses au parc canin.']],
  next: ['Suivre « Rencontrer d’autres chiens sereinement ».', 'Suivre « Comprendre son chien : le langage du corps ».', 'Suivre « Chien réactif en laisse » si les rencontres en laisse sont difficiles.'],
  mistakes: ['Laisser « ils vont régler ça entre eux ».', 'Utiliser le parc canin pour « socialiser » un chien qui a peur.', 'Ne pas surveiller parce qu’on discute.', 'Forcer un chien qui préfère rester près de vous.'],
  faq: [['Mon chien est trop brusque.', 'Faites des pauses fréquentes, choisissez des partenaires plus grands et patients, et récompensez le calme.'], ['Mon chien ne veut pas jouer.', 'Certains chiens adultes ne jouent plus ou préfèrent l’humain : c’est normal, ne le forcez pas.']],
  test: 'Il joue 15 minutes avec un chien ami, les rôles alternent, il revient au rappel et repart jouer.', safety: 'En cas de bagarre, n’intervenez jamais à mains nues entre les gueules : bruit fort, objet large ou saisie des pattes arrière par deux personnes. Consultez un vétérinaire après toute morsure, même minime.' },

{ id: 'tours2', free: false, icon: '🎪', cat: 'Jeu', title: 'Tours avancés : recule, slalom entre les jambes, salut, fais le mort', from: 16, dur: '5 min × 1 par jour', span: '3 à 6 semaines', level: 'Avancé',
  goal: 'Votre chien exécute 4 tours spectaculaires sur signal, avec plaisir : recule, slalom entre vos jambes, salut (révérence) et « Pan ! » (fait le mort).',
  why: 'Les tours ne sont pas « futiles » : ils développent la coordination, la conscience du corps, la concentration et renforcent votre complicité. Et ils plaisent énormément aux enfants et aux amis. La méthode, toujours la même : guidage, marqueur, récompense, puis retrait progressif de l’aide.',
  need: ['Friandises petites et appétissantes', 'Le marqueur « Oui ! »', 'Un couloir ou deux meubles (pour le recul)', 'Un sol non glissant'],
  steps: [
    { t: 'Recule', min: 5, b: 'Dans un couloir étroit, avancez doucement vers le chien : dès qu’il fait un pas en arrière, « Oui ! » et friandise lancée entre ses pattes avant. Augmentez à 2, puis 3 pas. Ajoutez le mot « Recule » quand le geste est fluide.', crit: 'Il recule de 3 pas sur « Recule », 8 fois sur 10.' },
    { t: 'Slalom entre les jambes', min: 5, b: 'Jambes écartées, guidez-le avec une friandise d’une main pour passer sous votre jambe, puis l’autre main de l’autre côté. Avancez d’un pas à chaque passage. Commencez lentement, puis enchaînez.', crit: 'Il fait 4 passages entre vos jambes en marchant.' },
    { t: 'Salut (révérence)', min: 5, b: 'Chien debout, amenez une friandise entre ses pattes avant, vers le sol : l’avant descend, l’arrière reste levé. Marquez à ce moment précis, avant qu’il ne se couche entièrement. Une main légère sous le ventre au début peut aider, sans pousser.', crit: 'Il fait la révérence 2 secondes, 8 fois sur 10.' },
    { t: '« Pan ! » (fait le mort)', min: 5, b: 'À partir du couché, guidez la friandise vers son épaule pour qu’il bascule sur le flanc. Récompensez au sol. Puis ajoutez le signal (doigt pointé, « Pan ! »). Enfin demandez l’immobilité 2 secondes.', crit: 'Il bascule sur le flanc sur « Pan ! » et reste 2 secondes.' },
    { t: 'Enchaîner le spectacle', min: 5, b: 'Enchaînez deux tours, puis trois, puis les quatre, avec une seule récompense à la fin. Variez l’ordre. Gardez des séances courtes et joyeuses : un chien qui s’ennuie fait moins bien.', crit: 'Il enchaîne les 4 tours avec une seule récompense finale.' }
  ],
  plan: [['Semaine 1', 'Recule dans un couloir.'], ['Semaine 2', 'Slalom entre les jambes.'], ['Semaines 3 et 4', 'Salut et « Pan ! ».'], ['Semaines 5 et 6', 'Enchaîner et varier l’ordre.']],
  next: ['Suivre « Petits tours : patte, tourne, roule » si ce n’est pas fait.', 'Suivre « La gym du chien ».', 'Apprendre le « Tiens » (porter un petit panier).'],
  mistakes: ['Pousser ou manipuler le chien pour obtenir la position.', 'Enseigner deux tours en même temps.', 'Faire des séances trop longues.', 'Faire faire le salut ou « Pan ! » à un chien avec un problème de dos ou d’épaule.'],
  faq: [['Il se couche au lieu de faire le salut.', 'Marquez plus tôt, dès que les coudes plient, et ne descendez pas la friandise jusqu’au sol.'], ['Il ne recule pas, il s’assoit.', 'Avancez plus lentement dans un couloir étroit, et récompensez le moindre déplacement des pattes arrière.']],
  test: 'Il exécute « Recule », le slalom, le salut et « Pan ! » sur signal, enchaînés, avec entrain.', safety: 'Évitez les rotations et révérences répétées chez un chien arthrosique, ou juste après un repas copieux. Travaillez toujours sur un sol non glissant.' }

);

PROGRAMS.push(
  { id: 'complice6', sp: 'dog', icon: '🤝', title: 'Programme complicité : 6 semaines', sub: 'Comprendre son chien, jouer et apprendre ensemble', weeks: [
    ['Semaine 1', 'Comprendre son chien', ['langage', 'focus']],
    ['Semaine 2', 'Balades qui apaisent', ['decompression', 'longe']],
    ['Semaine 3', 'Jouer avec des règles', ['tir', 'nosework']],
    ['Semaine 4', 'Le calme sur demande', ['relaxation', 'place']],
    ['Semaine 5', 'Des tours pour briller', ['tours', 'tours2']],
    ['Semaine 6', 'Bouger ensemble', ['parcours', 'canicross']]
  ] },
  { id: 'soins4', sp: 'dog', icon: '🧴', title: 'Programme soins sans stress : 4 semaines', sub: 'Médicaments, griffes, brossage et vétérinaire', weeks: [
    ['Semaine 1', 'Se laisser manipuler', ['manipulations', 'equipement']],
    ['Semaine 2', 'Pelage et griffes', ['brossage', 'griffes']],
    ['Semaine 3', 'Traitements', ['medicaments', 'dents']],
    ['Semaine 4', 'Chez le vétérinaire', ['veto', 'museliere']]
  ] }
);
