/* Wouf Éducation — leçons. Méthode : renforcement positif (récompenser ce qu'on veut voir), fondée sur les
   principes de l'apprentissage animal. Aucune méthode aversive (pas de coups, de collier étrangleur ou à piques,
   d'électrique, de cris). Contenu indicatif : pour un problème sérieux (agressivité, anxiété de séparation
   marquée, peur intense), consultez un vétérinaire comportementaliste ou un éducateur canin diplômé. */

const PRINCIPLES = [
  ['Récompenser ce qu’on veut revoir', 'Un chien répète ce qui lui rapporte quelque chose. Chaque fois qu’il fait bien, il gagne une friandise, un jeu ou une caresse (selon ce qu’il préfère). Ignorer les bêtises bénignes et rediriger vaut mieux que punir : la punition n’explique pas quoi faire à la place et abîme la confiance.'],
  ['Le marqueur : « Oui ! » au bon moment', 'Un mot bref (« Oui ! ») ou un clicker signale à l’instant précis où le comportement est correct, puis la friandise suit. Le timing compte : la récompense doit arriver dans la seconde. Sans marqueur, le chien ne sait pas toujours ce qui lui vaut la friandise.'],
  ['Séances courtes, souvent, et toujours finies sur une réussite', '2 à 5 minutes, 2 à 4 fois par jour, valent mieux que 30 minutes d’un coup. Un chiot se fatigue vite mentalement. Terminez toujours par un exercice facile qu’il réussit.'],
  ['La règle des 80 %', 'Quand votre chien réussit 8 fois sur 10 sur 10 essais, passez à l’étape suivante. En dessous de 6 sur 10, revenez d’un cran : l’exercice est trop difficile, ce n’est jamais la faute du chien.'],
  ['Un seul critère à la fois : les « 3 D »', 'Ne changez qu’une chose à la fois : la Durée, la Distance ou la Distraction. Quand vous augmentez l’une, baissez les autres. Un chien qui « sait » assis à la maison ne sait pas encore assis dans la rue : il faut généraliser dans plusieurs lieux.'],
  ['Le signal vient après le comportement', 'Apprenez d’abord le geste sans rien dire (avec l’appât ou en le capturant). Ajoutez le mot seulement quand le chien le fait presque à coup sûr, juste avant qu’il ne le fasse. Un mot dit trop tôt n’a aucun sens pour lui.'],
  ['Cohérence dans la famille', 'Mêmes mots, mêmes gestes, mêmes règles pour tout le monde. Décidez ensemble : le chien a-t-il le droit d’aller sur le canapé ? Sauter sur les gens ? Un chien qui reçoit des messages contraires ne peut pas comprendre.'],
  ['Comprendre le langage du chien', 'Bâillements, léchage de truffe, oreilles en arrière, tête détournée, queue basse, halètement sans chaleur : signes de stress ou d’inconfort. Ralentissez, éloignez-vous de la difficulté, facilitez. Un chien qui grogne prévient : ne le punissez jamais de l’avoir fait, c’est son dernier avertissement avant la morsure.'],
  ['Friandises : petites, molles, de valeur', 'Des morceaux de la taille d’un petit pois, faciles à avaler. Prélevez-les sur la ration du jour pour éviter le surpoids. Réservez les plus appétissantes (poulet, fromage sec, foie séché) aux exercices difficiles ou distrayants.'],
  ['Éducation et bien-être', 'Un chien qui a dépensé son énergie, exploré (renifler !) et dormi 16 à 20 heures par jour (chiot) apprend bien mieux. Fatigue, douleur ou maladie freinent l’apprentissage : un chien qui « refuse soudain » est peut-être souffrant. Parlez-en à votre vétérinaire.']
];

const LESSONS = [
/* ---------------- GRATUITES ---------------- */
{ id: 'marqueur', free: true, icon: '🎯', cat: 'Bases', title: 'Premiers pas : le marqueur « Oui ! » et son prénom', from: 7, dur: '2 min × 3 par jour', span: '2 à 4 jours', level: 'Débutant',
  goal: 'Votre chien associe « Oui ! » à une friandise, et se retourne vers vous dès qu’il entend son prénom.',
  why: 'Le marqueur est le langage de base de toute l’éducation positive : il dit « c’est exactement ça » à l’instant précis. Un prénom associé à du positif devient un signal d’attention fiable, sur lequel vous construirez le rappel.',
  need: ['Friandises minuscules et molles (10 à 20 par séance)', 'Un endroit calme, sans distraction', 'Éventuellement un clicker (facultatif : le mot « Oui » suffit)'],
  steps: [
    { t: 'Charger le marqueur', min: 2, b: 'Dites « Oui ! » d’une voix claire et brève, puis donnez aussitôt une friandise. Le chien n’a rien à faire. Répétez 15 à 20 fois en variant les moments. Le « Oui ! » doit toujours être suivi d’une friandise, même si c’est une maladresse.', crit: 'Le chien tourne la tête vers votre main ou vers vous dès qu’il entend « Oui ! » (5 fois de suite).' },
    { t: 'Le prénom = regarde-moi', min: 2, b: 'Attendez que votre chien soit un peu distrait (pas trop). Dites son prénom UNE fois, d’un ton joyeux. Dès qu’il vous regarde (même une demi-seconde) : « Oui ! » et friandise. S’il ne réagit pas, ne répétez pas : faites un petit bruit (claquement de langue) une seule fois puis marquez son regard.', crit: 'Il se retourne vers vous à l’appel de son prénom 8 fois sur 10, dans la pièce calme.' },
    { t: 'Ajouter de la distance', min: 3, b: 'Reculez de 1 à 3 pas, ou attendez qu’il ait la tête tournée. Appelez son prénom une fois. Récompensez dès le regard. Ensuite, faites-le dans une autre pièce puis au jardin.', crit: '8 réussites sur 10 dans 3 endroits différents.' },
    { t: 'Ajouter une petite distraction', min: 3, b: 'Jouet posé au sol, bruit léger, personne qui passe au loin. Si votre chien échoue, éloignez-vous de la distraction ou récompensez avec une friandise plus appétissante.', crit: '8 réussites sur 10 avec une distraction légère.' }
  ],
  mistakes: ['Répéter le prénom plusieurs fois (« Nala ! Nala ! NALA ! ») : il apprend à l’ignorer.', 'Utiliser le prénom pour gronder : il ne doit signifier que du positif.', 'Dire « Oui ! » puis chercher les friandises dans sa poche : préparez-les à l’avance.', 'Séances trop longues : arrêtez dès que l’attention baisse.'],
  faq: [['Il n’a pas l’air de comprendre le « Oui ! ».', 'Refaites la première étape sans rien demander, 15 fois, dans un endroit encore plus calme. La compréhension vient du nombre de répétitions « Oui ! puis friandise ».'], ['Il ne mange pas les friandises.', 'Il est peut-être trop stressé, ou la friandise est peu intéressante. Essayez du poulet, ou faites la séance avant le repas.'], ['Et si je préfère un clicker ?', 'Très bien : chargez-le exactement de la même façon (clic puis friandise). Le clicker est plus régulier, le mot plus pratique au quotidien.']],
  test: 'Depuis 3 endroits différents, votre chien vous regarde 8 fois sur 10 quand vous dites son prénom une seule fois.', safety: '' },

{ id: 'assis', free: true, icon: '🐕', cat: 'Bases', title: 'Assis', from: 8, dur: '3 min × 3 par jour', span: '3 à 5 jours', level: 'Débutant',
  goal: 'Votre chien s’assoit sur signal, avec ou sans geste, dans plusieurs situations.',
  why: 'Assis est le comportement « à tout faire » : il remplace sauter, aboyer, tirer. Un chien qui sait s’asseoir a une alternative claire quand il veut quelque chose.',
  need: ['Friandises molles', 'Le marqueur « Oui ! » déjà chargé', 'Un sol non glissant'],
  steps: [
    { t: 'Guider avec la friandise (appât)', min: 3, b: 'Placez une friandise devant le museau, puis montez lentement la main au-dessus de sa tête, vers l’arrière. Naturellement, la tête se lève et l’arrière-train descend. Dès que les fesses touchent le sol : « Oui ! » et friandise donnée à hauteur du museau, sans le faire sauter.', crit: 'Il s’assoit en suivant votre main 8 fois sur 10.' },
    { t: 'Faire disparaître l’appât', min: 3, b: 'Faites le même geste avec la main vide (friandise dans l’autre main ou dans la poche). Marquez « Oui ! » puis récompensez de l’autre main. Le geste devient un signal visuel.', crit: '8 réussites sur 10 avec la main vide.' },
    { t: 'Ajouter le mot « Assis »', min: 3, b: 'Dites « Assis » UNE fois, attendez une seconde, puis faites le geste. Au bout de plusieurs répétitions, il s’assoira dès le mot, avant votre geste. À ce moment, récompensez généreusement.', crit: 'Il s’assoit au mot seul 8 fois sur 10.' },
    { t: 'Généraliser : lieux, positions, distractions', min: 5, b: 'Demandez « Assis » dans la cuisine, au jardin, dans la rue calme, devant un visiteur. Changez votre position (assis, de côté, de dos). Variez les récompenses : parfois friandise, parfois jeu, parfois caresse.', crit: '8 réussites sur 10 dans au moins 4 endroits différents.' },
    { t: 'Attendre avant la friandise', min: 3, b: 'Une fois assis, comptez 1, 2, 3 secondes avant « Oui ! ». Augmentez très progressivement. C’est la base du « Reste ».', crit: 'Il reste assis 5 secondes sans bouger.' }
  ],
  mistakes: ['Pousser sur la croupe : il s’oppose ou se crispe, sans comprendre.', 'Répéter « Assis, assis, assis ! » : dites une fois, patientez.', 'Récompenser trop haut : il se lève ou saute pour l’attraper.', 'Donner la friandise trop tard : le chien ne fait plus le lien avec l’assise.'],
  faq: [['Il recule au lieu de s’asseoir.', 'Faites l’exercice le dos contre un mur ou un meuble, il ne peut plus reculer.'], ['Il saute pour attraper la friandise.', 'Montez la main plus lentement et moins haut, ou tenez la friandise plus près du museau.'], ['Il s’assoit puis se relève tout de suite.', 'Marquez plus vite, et récompensez pendant qu’il est assis (pas après).']],
  test: 'Au mot « Assis » seul, dans 4 lieux différents, il s’assoit 8 fois sur 10.', safety: 'Pour un chiot de grande race, évitez les assis répétés à un rythme soutenu sur sol glissant : privilégiez des séances courtes.' },

{ id: 'proprete', free: true, icon: '🌳', cat: 'Chiot', title: 'Propreté du chiot', from: 8, dur: 'Tout au long de la journée', span: '2 à 8 semaines', level: 'Débutant',
  goal: 'Votre chiot fait ses besoins dehors, de plus en plus souvent seul, et attend le matin sans accident.',
  why: 'Le chiot n’a ni la maîtrise musculaire ni la capacité de se retenir avant plusieurs mois. La propreté s’apprend par la routine et la récompense sur le bon endroit, jamais par la punition, qui apprend seulement à se cacher pour faire.',
  need: ['Une sortie courte et régulière', 'Friandises appétissantes à emporter', 'Nettoyant enzymatique pour les accidents (pas d’eau de Javel ni d’ammoniaque)'],
  steps: [
    { t: 'Installer une routine de sorties', min: 0, b: 'Sortez le chiot : au réveil, après chaque repas (5 à 20 minutes), après chaque sieste, après le jeu, après avoir bu, et avant le coucher. Repère : environ une heure de retenue par mois d’âge, plus le jour que la nuit. Un chiot de 10 semaines a besoin de sortir toutes les 1 à 2 heures.', crit: 'Vous notez les horaires de 3 jours : les besoins deviennent prévisibles.' },
    { t: 'Toujours au même endroit', min: 0, b: 'Emmenez-le à la même zone, en laisse, sans jouer. Restez calme et attendez (jusqu’à 5 minutes). Ajoutez un mot neutre (« Vas-y », « Pipi ») quand il commence.', crit: 'Il fait dehors 8 fois sur 10 quand vous l’emmenez.' },
    { t: 'Récompenser tout de suite', min: 0, b: 'Dès qu’il a fini : « Oui ! » et friandise très appétissante, jubilation, PUIS jeu ou promenade. La récompense doit venir dans les 3 secondes, sur place. Un chiot qui rentre pour être récompensé n’a pas fait le lien.', crit: 'Il vous regarde en attendant sa friandise après avoir fini.' },
    { t: 'Surveiller à l’intérieur', min: 0, b: 'Un chiot qui n’est pas dehors est sous surveillance : en laisse à votre ceinture, ou dans un espace restreint. Signes d’un besoin imminent : renifle en cercle, s’arrête de jouer, va vers une porte. Emportez-le dehors, sans gronder.', crit: 'Moins d’un accident par jour.' },
    { t: 'Gérer les accidents sans punir', min: 0, b: 'Accident vu en cours : interrompez calmement (un « Oh ! » bref), emmenez-le dehors, félicitez s’il termine. Accident découvert après : nettoyez sans un mot avec un nettoyant enzymatique. Ne mettez jamais son nez dedans : il apprend seulement à se cacher.', crit: 'Aucun accident pendant 7 jours.' },
    { t: 'Espacer les sorties et allonger les nuits', min: 0, b: 'Quand il tient une semaine sans accident, espacez de 30 minutes. La nuit : dernière sortie tardive, première très tôt, puis allongez d’une demi-heure tous les 3 à 4 jours.', crit: 'Nuit complète et journée avec sorties toutes les 3 à 4 heures.' }
  ],
  mistakes: ['Punir ou gronder après coup : il ne comprend pas le lien et développe la peur de faire devant vous.', 'Sortir seulement pour la promenade et rentrer tout de suite après le besoin : il apprend que faire = fin du plaisir.', 'Ne pas nettoyer avec un nettoyant enzymatique : l’odeur résiduelle rappelle l’endroit.', 'Attendre que le chiot « demande » : il ne sait pas le faire avant plusieurs semaines. C’est à vous de proposer.', 'Donner à boire seulement le soir pour limiter les accidents : ne jamais restreindre l’eau.'],
  faq: [['Il refait sur le même endroit à l’intérieur.', 'Nettoyez très bien avec un produit enzymatique, et bloquez l’accès à cette zone quelques semaines.'], ['Il fait dehors mais aussi à l’intérieur juste après.', 'Il n’a pas fini : restez dehors plus longtemps (5 à 10 minutes) et répétez une seconde sortie brève avant de rentrer.'], ['À quel âge est-il propre ?', 'Très variable : la plupart des chiots sont fiables entre 4 et 6 mois, certains plus tard (petites races). Un retour en arrière est normal, surtout à l’adolescence.'], ['Il fait beaucoup, souvent, ou avec des douleurs.', 'Consultez : infection urinaire, parasites, diarrhée ou trouble hormonal peuvent expliquer des accidents.']],
  test: 'Une semaine entière sans accident à l’intérieur, avec des sorties espacées de 3 à 4 heures.', safety: 'Ne sortez pas un chiot non protégé dans les lieux fréquentés par des chiens inconnus tant que son protocole de vaccination n’est pas terminé (voir avec votre vétérinaire).' },

/* ---------------- WOUF PLUS ---------------- */
{ id: 'coucher', free: false, icon: '🛏️', cat: 'Bases', title: 'Coucher', from: 10, dur: '3 min × 3 par jour', span: '3 à 6 jours', level: 'Débutant',
  goal: 'Votre chien se couche sur signal et y reste quelques secondes, détendu.',
  why: 'Le coucher est une position de calme : il prépare la « Place », le « Reste » et la gestion de l’excitation. C’est aussi l’exercice où l’on apprend le plus sur la patience du chien… et la nôtre.',
  need: ['Friandises molles de bonne valeur', 'Un sol confortable (tapis ou herbe) : un chien qui a mal aux coudes ne se couchera pas'],
  steps: [
    { t: 'Assis, puis appât vers le sol', min: 3, b: 'Chien assis. Placez la friandise devant son museau, puis descendez lentement la main entre ses pattes avant jusqu’au sol. Attendez sans rien dire : quand les coudes touchent le sol, « Oui ! » et friandise DONNÉE AU SOL (pour qu’il reste couché).', crit: 'Il se couche en suivant la main 8 fois sur 10.' },
    { t: 'Si le chien ne se couche pas : le tunnel', min: 3, b: 'Asseyez-vous sur le sol, genoux levés, et guidez la friandise sous vos genoux comme dans un tunnel : il doit ramper pour l’atteindre. Marquez dès que les coudes touchent.', crit: 'Il rampe puis se couche.' },
    { t: 'Retirer l’appât', min: 3, b: 'Même geste avec la main vide (elle pointe vers le sol), récompensez de l’autre main. Le geste devient un signal.', crit: '8 réussites sur 10 main vide.' },
    { t: 'Ajouter le mot « Couché »', min: 3, b: 'Dites « Couché » une fois, patientez 1 seconde, puis faites le geste. Répétez jusqu’à ce qu’il se couche dès le mot.', crit: 'Il se couche au mot seul 8 fois sur 10.' },
    { t: 'Rester couché et généraliser', min: 5, b: 'Ajoutez 2, 3, 5 secondes avant « Oui ! ». Changez d’endroit, de position, de sol. Récompensez parfois d’un « Oui ! » puis d’un jeu.', crit: 'Couché 5 secondes dans 3 lieux différents.' }
  ],
  mistakes: ['Appuyer sur son dos : il résiste, ou le vit comme une contrainte.', 'Attendre trop longtemps : marquez la moindre descente des coudes au début.', 'Donner la friandise en hauteur : il se relève. Récompensez au sol.', 'Exiger le coucher sur un sol froid, dur ou glissant.'],
  faq: [['Il se relève à chaque fois.', 'Donnez la récompense plus vite et au sol, plusieurs petites friandises à la suite tant qu’il reste couché (« nourrir en position »).'], ['Il s’assoit en boucle.', 'Descendez la main plus lentement, ou essayez la méthode du tunnel.'], ['Il aboie ou gémit.', 'Vous exigez trop : revenez à une étape plus courte, faites-le plus fatigué.']],
  test: 'Au mot « Couché » seul, dans 3 pièces différentes, il se couche 8 fois sur 10 et reste 5 secondes.', safety: 'Un chien qui a soudain du mal à se coucher ou à se relever peut avoir mal (hanches, coudes, dos) : consultez.' },

{ id: 'reste', free: false, icon: '✋', cat: 'Bases', title: 'Reste : l’attente et la maîtrise de soi', from: 12, dur: '3 min × 3 par jour', span: '1 à 3 semaines', level: 'Intermédiaire',
  goal: 'Votre chien reste immobile à sa place jusqu’à ce que vous le libériez (mot de libération).',
  why: 'Le « Reste » enseigne le contrôle de soi, essentiel pour la sécurité (porte ouverte, traversée, arrivée de visiteurs). On l’enseigne en respectant les trois D : durée, distance, distraction, une seule à la fois.',
  need: ['Assis et Couché acquis', 'Un mot de libération (« Ok ! » ou « Libre ! »)', 'Friandises'],
  steps: [
    { t: 'Le mot de libération', min: 2, b: 'Choisissez un mot (« Libre ! »). Chien assis : dites « Libre ! », lancez une friandise ou encouragez-le à bouger. Il apprend que « Libre ! » = il peut bouger. Répétez 10 fois.', crit: 'Il comprend qu’il bouge seulement après « Libre ! ».' },
    { t: 'Durée : 1 à 5 secondes', min: 3, b: 'Assis face à vous. Dites « Reste » (main ouverte, paume vers lui), comptez 1 seconde, puis « Oui ! », friandise, et « Libre ! ». Augmentez par paliers : 2, 3, 5, 8, 10 secondes. Variez : 3, 1, 5, 2, 8. Si le chien bouge, revenez à une durée plus courte, sans gronder.', crit: '8 réussites sur 10 à 10 secondes.' },
    { t: 'Distance : un pas à la fois', min: 3, b: 'Gardez la durée courte (2 secondes). Faites un pas en arrière, revenez, « Oui ! » puis friandise (récompensez auprès de lui, ne l’appelez pas). Puis 2 pas, 3 pas, 5 pas. Retour TOUJOURS jusqu’au chien avant de récompenser.', crit: '8 réussites sur 10 à 5 pas.' },
    { t: 'Distraction : faible à moyenne', min: 4, b: 'Marchez autour de lui, faites tomber un objet, sautez sur place. Recommencez à durée et distance courtes quand vous ajoutez une distraction.', crit: '8 réussites sur 10 avec un mouvement léger.' },
    { t: 'Le reste en situation réelle', min: 5, b: 'Attendre avant de sortir de la voiture, avant la gamelle, à la porte, au bord d’un trottoir. Libérez toujours par « Libre ! ». Récompensez parfois de façon aléatoire.', crit: 'Il attend à la porte ouverte 5 secondes.' }
  ],
  mistakes: ['Augmenter deux critères à la fois (distance ET durée).', 'Appeler le chien pendant qu’il est en « Reste » : il apprend à se lever pour venir. Allez le voir.', 'Le libérer sans mot, ou avec un mot qu’il entend dans la conversation.', 'Gronder lorsqu’il bouge : c’est vous qui avez été trop vite. Recommencez plus court.'],
  faq: [['Il se lève dès que je bouge.', 'Restez collé à lui et ne bougez qu’un pied. Faites des paliers minuscules.'], ['Il tient à la maison mais pas dehors.', 'Normal : recommencez à 1 seconde et à 1 pas dans chaque nouveau lieu.'], ['Il se couche quand je demande « Reste » assis.', 'Récompensez plus vite, et au niveau de son museau, pas en bas.']],
  test: 'Assis, 10 secondes à 5 pas de vous avec un léger mouvement de distraction, 8 fois sur 10, dans 2 lieux.', safety: 'Ne demandez jamais un « Reste » long à un chien stressé ou dans un environnement dangereux : c’est un exercice, pas une garantie de sécurité (gardez-le en laisse).' },

{ id: 'rappel', free: false, icon: '📣', cat: 'Sécurité', title: 'Rappel : « Ici ! » fiable', from: 10, dur: '5 min × 2-3 par jour', span: '4 à 8 semaines', level: 'Intermédiaire',
  goal: 'Votre chien revient vers vous quand vous l’appelez, même face à une distraction.',
  why: 'Le rappel est le comportement qui peut sauver la vie de votre chien. Il se construit en le rendant toujours plus intéressant que le reste du monde : jamais de punition au retour, des récompenses de grande valeur, et un signal utilisé rarement et pour de bonnes raisons.',
  need: ['Friandises très appétissantes (poulet, fromage)', 'Une longe de 5 à 10 mètres (pour la sécurité)', 'Un mot de rappel exclusif (« Ici ! », un sifflet…)', 'Un harnais pour la longe'],
  steps: [
    { t: 'Le jeu du rappel en intérieur', min: 3, b: 'À 2 ou 3 mètres, appelez d’une voix joyeuse « Ici ! » et reculez de quelques pas. Quand il arrive : « Oui ! » puis fête et une à trois friandises consécutives. Ajoutez un contact léger du collier (avec récompense) pour qu’il s’habitue à ce qu’on le touche à l’arrivée.', crit: 'Il vient au galop 8 fois sur 10.' },
    { t: 'Le rappel avec distance et vitesse', min: 5, b: 'Dans un jardin fermé, augmentez la distance progressivement (5, 10, 15 m). Cachez-vous derrière un arbre, appelez, félicitez. Faites-le à deux : « ping-pong » entre deux personnes avec récompenses.', crit: '8 réussites sur 10 à 10 mètres.' },
    { t: 'Ajouter des distractions faibles', min: 5, b: 'Jouet au sol, autre personne éloignée, odeurs. Utilisez la longe pour éviter qu’il « apprenne » à l’ignorer. Si vous devez tirer sur la longe, c’est que l’exercice est trop dur.', crit: '8 réussites sur 10 avec une distraction faible.' },
    { t: 'Dehors sur longe', min: 10, b: 'Dans un lieu calme sécurisé, longe de 10 m. Laissez-le explorer, appelez, récompensez fortement (jackpot : 5 friandises ou un jeu). Puis dites « Libre ! » et retournez à l’exploration : le rappel ne doit pas signifier « fin du plaisir ».', crit: 'Il revient de 8 mètres devant un chien lointain.' },
    { t: 'Le « jackpot » et la vie réelle', min: 10, b: 'Rappelez-le parfois sans raison et récompensez toujours royalement. Pendant plusieurs mois, gardez la longe dans les endroits où il pourrait poursuivre un animal, une route, un autre chien.', crit: 'Rappel sur plusieurs lieux, avec longe, pendant plusieurs semaines.' }
  ],
  mistakes: ['Gronder ou punir quand il revient tard : il apprend que revenir est mauvais.', 'Appeler pour terminer la promenade tout le temps.', 'Répéter le rappel 5 fois : il apprend à le rater. Appelez une fois, puis aidez-le.', 'Lâcher un chiot non rappelable dans un endroit ouvert.'],
  faq: [['Il ne revient que si j’ai des friandises.', 'Au début, oui. Ensuite variez les récompenses (jeu, caresses, liberté) et cachez les friandises, mais gardez-en toujours d’excellentes pour les rappels difficiles.'], ['Il vient mais s’arrête à 2 mètres.', 'Il s’attend à être attrapé. Récompensez sur place, ne l’attrapez pas, et reculez pour l’encourager.'], ['Il a un très fort instinct de chasse.', 'Sécurité avant tout : longe ou espace clos, et travail d’un éducateur formé pour renforcer la maîtrise (jeu de rapport, marche au pied).']],
  test: 'En espace ouvert, il revient de 15 mètres au premier appel 8 fois sur 10 avec une distraction faible, en étant sur longe.', safety: 'Un rappel n’est jamais fiable à 100 %. Près d’une route ou en présence de bétail ou de faune : gardez toujours votre chien en laisse.' },

{ id: 'laisse', free: false, icon: '🦮', cat: 'Balades', title: 'Marcher en laisse sans tirer', from: 12, dur: '10 min × 2 par jour', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien marche à vos côtés avec une laisse détendue en forme de « J ».',
  why: 'Le chien tire parce que ça marche : tirer le fait avancer. On inverse la règle : laisse tendue = on s’arrête, laisse détendue = on avance. Le chien apprend que marcher près de vous est plus payant que tirer.',
  need: ['Un harnais bien ajusté (préférez-le au collier pour un chien qui tire)', 'Une laisse de 1,5 à 2 mètres (pas de laisse à enrouleur)', 'Friandises en poche ou dans une banane'],
  steps: [
    { t: 'La position gagnante', min: 3, b: 'À la maison, sur place : chaque fois que votre chien est à votre côté, laisse molle, « Oui ! » et friandise à hauteur de votre jambe, du côté choisi. Créez un « aimant » : il apprend que cette zone est très payante.', crit: 'Il reste près de votre jambe et lève la tête vers vous 8 fois sur 10.' },
    { t: 'Un pas, deux pas, trois pas', min: 5, b: 'Avancez de 1 à 3 pas. S’il reste à hauteur avec la laisse molle : « Oui ! » et friandise. Progressivement : 5, 8, 10 pas. Marchez lentement au début.', crit: '10 pas consécutifs laisse molle, 8 fois sur 10.' },
    { t: 'Laisse tendue : on s’arrête', min: 5, b: 'À l’instant où la laisse se tend, arrêtez-vous complètement (comme un arbre), sans tirer, sans parler. Dès qu’il revient vers vous ou détend la laisse (même de 2 cm) : « Oui ! », friandise, on repart. Au début, cela demande de la patience : un arrêt peut durer 30 secondes.', crit: 'Il ne tend plus la laisse après 2 ou 3 arrêts.' },
    { t: 'Changer de direction', min: 5, b: 'Quand il se met à tirer ou à s’éloigner, demi-tour tranquille sans un mot et repartez : il doit vous suivre. Récompensez quand il vous rattrape. Vous devenez imprévisible, donc intéressant.', crit: 'Il se regroupe spontanément sur le côté.' },
    { t: 'Ajouter les distractions', min: 10, b: 'Autres chiens, odeurs, passants : éloignez-vous de la distraction, récompensez le fait de la regarder puis de revenir à vous (« regarde-moi »). Autorisez des pauses « reniflage » autorisées par un mot (« Libre ! ») : elles font partie de la balade.', crit: 'Laisse molle 80 % de la promenade dans une rue calme.' }
  ],
  mistakes: ['Laisser tirer « juste jusqu’à la prochaine rue » : chaque fois qu’il tire et avance, il apprend que ça marche.', 'Tirer en arrière sur la laisse (secousses) : douleur, stress, et il tire encore plus fort (réflexe d’opposition).', 'Utiliser une laisse à enrouleur : elle apprend à tirer en permanence.', 'Balades toujours trop courtes et trop rapides : laissez-le renifler, c’est son activité principale.', 'Utiliser un collier étrangleur ou à piques : risques de blessures et de stress, sans effet éducatif.'],
  faq: [['Il tire dès qu’il voit un chien.', 'Trop près : éloignez-vous jusqu’à la distance où il vous regarde encore, récompensez, et réduisez la distance très progressivement sur plusieurs jours.'], ['Il s’arrête et refuse d’avancer.', 'Vérifiez le harnais, la douleur, la peur. Récompensez le premier pas et avancez d’un pas très court.'], ['Il tire à la maison mais pas dehors (ou l’inverse).', 'Normal : l’apprentissage est spécifique à chaque lieu. Recommencez l’étape 2 à chaque nouveau lieu.']],
  test: 'Sur 5 minutes de marche en rue calme, la laisse reste en « J » 80 % du temps.', safety: 'Un harnais qui frotte, un chien qui boite ou qui traîne sont des signaux de douleur : consultez avant de poursuivre.' },

{ id: 'laisse-le', free: false, icon: '🚫', cat: 'Sécurité', title: 'Laisse-le et Donne : ne pas ramasser, savoir lâcher', from: 12, dur: '3 min × 3 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien se détourne d’un objet ou d’une nourriture sur signal, et lâche ce qu’il a dans la gueule contre un échange.',
  why: 'Deux comportements de sécurité : « Laisse-le » l’empêche d’avaler un aliment toxique ou un déchet, « Donne » évite les batailles pour un objet. Le principe : un échange gagnant, jamais une confiscation, car le chien qui a peur qu’on lui prenne l’objet apprend à le protéger (et à grogner).',
  need: ['Deux types de friandises : de valeur moyenne et haute', 'Des jouets ou objets sans danger', 'Patience'],
  steps: [
    { t: 'Laisse-le : le poing fermé', min: 3, b: 'Friandise dans la main fermée. Le chien renifle, lèche, gratte : ne bougez pas. Dès qu’il s’écarte, même une seconde : « Oui ! » et donnez-lui une friandise de l’AUTRE main (une meilleure).', crit: 'Il s’écarte immédiatement 8 fois sur 10.' },
    { t: 'Ajouter le mot', min: 3, b: 'Dites « Laisse-le », présentez la main fermée, marquez et récompensez dès qu’il s’écarte. Puis main ouverte : s’il tente d’attraper, refermez.', crit: 'Il s’écarte au mot, main ouverte.' },
    { t: 'Friandise au sol', min: 5, b: 'Posez une friandise au sol, une main au-dessus. Il tente : recouvrez-la. Dès qu’il s’écarte ou vous regarde : « Oui ! » et friandise de l’autre main. Progressivement, laissez la friandise découverte.', crit: 'Il ignore une friandise posée à 1 m, 8 fois sur 10.' },
    { t: 'Donne : l’échange', min: 3, b: 'Proposez un jouet, laissez-le l’attraper. Présentez une friandise devant son museau : il lâche pour la manger. Dites « Donne » en même temps, puis rendez le jouet de temps en temps pour qu’il comprenne que donner n’est pas perdre.', crit: 'Il lâche l’objet au mot, 8 fois sur 10.' },
    { t: 'Vie réelle', min: 5, b: 'Pratiquez avec des objets de plus en plus intéressants (chaussette, os). Ne courez jamais après un chien qui s’enfuit avec un objet : proposez un échange ou une friandise ailleurs. En promenade, entraînez le « Laisse-le » devant des déchets.', crit: 'Il obéit à « Laisse-le » devant une friandise au sol et un déchet.' }
  ],
  mistakes: ['Arracher l’objet : il apprend à le garder plus fermement ou à mordre.', 'Courir derrière lui : il pense que c’est un jeu.', 'Punir un chien qui grogne pour un objet : il cache son avertissement et peut mordre sans prévenir.', 'Ne récompenser que la première étape et jamais l’échange final.'],
  faq: [['Il grogne dès que je m’approche de sa gamelle ou de son os.', 'Ne tentez pas de lui reprendre. Approchez-vous en jetant une friandise supérieure, puis éloignez-vous. En cas de grognement répété ou de morsure : consultez un comportementaliste.'], ['Il avale tout dans la rue.', 'Utilisez la laisse courte, l’exercice « Regarde-moi » et le « Laisse-le », et évitez les zones sales le temps d’apprendre. Envisagez une muselière anti-charognage si nécessaire.'], ['Il a avalé quelque chose de dangereux.', 'Appelez immédiatement un vétérinaire (voir l’onglet SOS).']],
  test: 'Une friandise posée au sol : il l’ignore au mot « Laisse-le » 8 fois sur 10 et lâche un jouet à « Donne » sans conflit.', safety: 'Tout objet dangereux (bâtonnet de brochette, médicament, chocolat, os cuits) doit être rangé : l’éducation ne remplace pas la prévention.' },

{ id: 'place', free: false, icon: '🧘', cat: 'Calme', title: 'La Place : un tapis pour se calmer', from: 12, dur: '3 min × 3 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien va sur son tapis (ou son panier) sur signal et s’y couche calmement pendant que vous vaquez à vos occupations.',
  why: 'La Place donne au chien un endroit sûr et un comportement alternatif à mendier, aboyer à la porte ou sauter sur les visiteurs. Un tapis bien appris est aussi précieux chez le vétérinaire, au restaurant ou en visite.',
  need: ['Un tapis ou une petite couverture (portable)', 'Friandises molles', 'Assis et Couché acquis'],
  steps: [
    { t: 'Capturer : le tapis = récompense', min: 3, b: 'Posez le tapis au sol. Chaque fois que le chien pose une patte, puis deux, puis le corps dessus : « Oui ! » et friandise DÉPOSÉE sur le tapis. Il apprend que le tapis paie.', crit: 'Il monte volontairement sur le tapis 8 fois sur 10.' },
    { t: 'Le coucher sur le tapis', min: 3, b: 'Une fois sur le tapis, demandez « Couché » (ou attendez) et récompensez. Ajoutez le mot « Place ».', crit: 'Il se couche sur le tapis à « Place » depuis 1 mètre.' },
    { t: 'Ajouter la durée', min: 4, b: 'Récompensez toutes les 3 à 5 secondes tant qu’il reste couché, puis toutes les 10, 20, 30 secondes. Utilisez « Libre ! » pour lui indiquer qu’il peut partir.', crit: 'Il reste 1 minute couché.' },
    { t: 'Ajouter la distance', min: 5, b: 'Éloignez-vous du tapis, appelez « Place » : il doit s’y rendre seul. Progressez de 1 m à 3 puis 5 m et en changeant d’angle.', crit: 'Il va au tapis depuis 3 mètres, 8 fois sur 10.' },
    { t: 'Ajouter les distractions du quotidien', min: 10, b: 'Sonnette, passage, repas familial, visiteurs. Faites travailler en visite : il va sur le tapis pendant que vous accueillez. Partez de très faible distraction et augmentez progressivement.', crit: 'Il reste sur son tapis 2 minutes pendant un repas.' }
  ],
  mistakes: ['Utiliser le tapis comme punition (« va sur ton tapis ! »).', 'Trop d’attente au début : récompensez vite, puis étirez.', 'Ne jamais le libérer clairement : il ne sait pas quand c’est fini.', 'Attendre l’effet immédiat en présence de distractions fortes sans avoir préparé.'],
  faq: [['Il quitte le tapis à chaque fois que je bouge.', 'Retournez à un délai plus court, et récompensez plus souvent (toutes les 3 secondes) puis étirez de nouveau.'], ['Il s’en va dès qu’il a mangé la friandise.', 'Donnez plusieurs petites friandises à la suite, l’une après l’autre, tant qu’il reste couché.']],
  test: 'Il va sur le tapis depuis 3 mètres au mot « Place » et y reste 2 minutes pendant que vous bougez dans la pièce.', safety: '' },

{ id: 'solitude', free: false, icon: '🏠', cat: 'Calme', title: 'Apprendre la solitude (et prévenir l’anxiété de séparation)', from: 8, dur: 'Séances de quelques minutes, chaque jour', span: '3 à 8 semaines', level: 'Important',
  goal: 'Votre chien reste seul, calme, une durée qui augmente lentement.',
  why: 'Le chien est un animal social : la solitude s’apprend, comme le reste. Le laisser seul brutalement (« il s’habituera ») provoque parfois une anxiété de séparation (aboiements, destruction, malpropreté, salivation). On procède par petits paliers, en restant sous le seuil de stress.',
  need: ['Un espace sûr (pièce, enclos, panier)', 'Un jouet de mastication (Kong garni, os à mâcher approprié)', 'Éventuellement une caméra pour observer sans être vu'],
  steps: [
    { t: 'Un espace confortable et positif', min: 0, b: 'Associez son coin à des choses agréables : friandises, jouet garni, repas. Il doit y aller de son propre chef, jamais y être enfermé pour le punir.', crit: 'Il se couche volontairement dans son espace.' },
    { t: 'Seconde par seconde, dans la même pièce', min: 3, b: 'Éloignez-vous d’un pas, revenez avant qu’il proteste. Ajoutez 2, 5, 10 secondes. Sortez de sa vue : ouvrez la porte, refermez, revenez. L’objectif est qu’il ne se stresse jamais.', crit: 'Il reste calme 30 secondes hors de sa vue.' },
    { t: 'De 30 secondes à 5 minutes', min: 5, b: 'Sortez brièvement de la pièce ou de la maison. Variez les durées (30 s, 2 min, 1 min, 5 min…). Ne faites pas de grands adieux ni de grandes retrouvailles : restez neutre.', crit: 'Calme 5 minutes seul, sans stress visible.' },
    { t: 'Allonger sur des durées réelles', min: 10, b: 'Passez à 10, 20, 30 minutes puis une heure. Si des signes de détresse apparaissent (gémissements, halètement, salivation, tentative de fuite), c’est trop vite : revenez à la durée précédente.', crit: 'Il reste calme 1 heure seul.' },
    { t: 'Routines de départ et retour', min: 0, b: 'Sortez le chien avant de partir (besoins, dépense physique douce), laissez un jouet de mastication, partez sans cérémonie et revenez sans excitation. Attendez qu’il soit calme avant de le saluer.', crit: 'Il vous accueille calmement.' }
  ],
  mistakes: ['Partir en cachette : il devient hypervigilant à chaque geste (clés, chaussures).', 'Punir au retour pour les dégâts : il associe votre retour à la punition et devient encore plus anxieux.', 'Augmenter la durée trop vite (passer de 5 minutes à 3 heures).', 'Ne pas se préoccuper des signes de stress subtils (halètement, salive, cœur qui bat vite).'],
  faq: [['Il aboie ou détruit quand je pars.', 'Consultez votre vétérinaire : un trouble de la séparation nécessite un accompagnement par un comportementaliste, parfois avec un traitement. Filmez-le pendant votre absence pour aider le diagnostic.'], ['Faut-il un deuxième chien ?', 'Pas forcément : un autre chien ne règle pas l’anxiété de séparation et peut la multiplier.'], ['Combien de temps un chien adulte peut-il rester seul ?', 'Généralement pas plus de 4 à 6 heures selon l’âge, la personnalité et l’habitude. Un chiot beaucoup moins. En cas d’absence longue, faites appel à un pet-sitter.']],
  test: 'Il reste calme (pas de gémissements ni de destruction) pendant 1 heure, vérifiez à la caméra.', safety: 'Signes d’anxiété de séparation (destruction, cris prolongés, salivation, malpropreté, automutilation) : ne pas attendre, consultez un vétérinaire.' },

{ id: 'socialisation', free: false, icon: '🌍', cat: 'Chiot', title: 'Socialisation et habituation : bien grandir dans le monde', from: 7, dur: '1 nouvelle expérience positive par jour', span: 'De 7 semaines à 6 mois', level: 'Essentiel',
  goal: 'Votre chiot rencontre positivement une grande variété de personnes, animaux, bruits, sols et situations avant 4 à 6 mois.',
  why: 'Entre 3 et 14 semaines environ, le cerveau du chiot est particulièrement ouvert à la nouveauté ; ce qu’il n’a pas connu positivement à cet âge peut devenir une source de peur plus tard. Socialiser, ce n’est pas « le confronter » mais lui offrir des expériences douces et récompensées, à son rythme.',
  need: ['Une liste de situations à faire découvrir', 'Friandises', 'Vaccinations à jour selon les conseils de votre vétérinaire'],
  steps: [
    { t: 'Une liste de « premières fois » positives', min: 0, b: 'Cochez au fil des semaines : hommes et femmes, enfants calmes, casque, parapluie, capuche, lunettes ; sols (carrelage, grille, herbe, gravier, escaliers) ; bruits (aspirateur, sonnette, casseroles, tonnerre en enregistrement) ; voiture, cage de transport ; manipulation (pattes, oreilles, gueule) ; chiens adultes calmes et vaccinés ; chats amicaux.', crit: 'Au moins 30 expériences différentes vécues sans stress.' },
    { t: 'Toujours à son rythme', min: 0, b: 'Laissez le chiot venir vers la nouveauté. Récompensez la curiosité. S’il se fige, recule ou tremble : augmentez la distance, laissez-le observer, récompensez calmement, puis recommencez plus doucement. Ne le forcez jamais et ne le portez pas vers ce qui l’effraie.', crit: 'Il s’approche spontanément de la nouveauté.' },
    { t: 'Les rencontres avec les chiens', min: 0, b: 'Privilégiez des chiens adultes connus, équilibrés et vaccinés, plutôt que les contacts inconnus. Les cours pour chiots encadrés par un éducateur sont une excellente option (dès la première vaccination, selon les conseils du vétérinaire).', crit: '3 chiens différents rencontrés dans de bonnes conditions.' },
    { t: 'Avant la fin du protocole vaccinal', min: 0, b: 'Portez-le en ville, faites-lui observer la rue depuis vos bras ou un sac, invitez des amis à la maison, roulez en voiture. Évitez les lieux très fréquentés par des chiens inconnus (parcs, caniveaux) jusqu’à validation de votre vétérinaire.', crit: 'Sorties « en sécurité » chaque semaine.' },
    { t: 'Continuer à l’adolescence', min: 0, b: 'Vers 5 à 8 mois, une seconde période sensible peut apparaître (peurs soudaines). Continuez les expériences positives, sans rien forcer.', crit: 'Stabilité et sérénité dans les nouveautés.' }
  ],
  mistakes: ['Attendre la fin des vaccins pour ne rien faire : la période sensible est déjà en cours.', 'Le forcer à approcher (« ça va aller ») : cela crée des peurs.', 'Le laisser jouer avec un chien qui le malmène.', 'Trop d’expériences dans la même journée : la fatigue suscite l’irritabilité.'],
  faq: [['Mon chiot a peur de tout depuis quelques jours.', 'C’est une phase de peur classique. Réduisez les nouveautés, restez rassurant, sans surprotéger, et reprenez doucement.'], ['Il est en surexcitation face à tout le monde.', 'Apprenez-lui à saluer calmement : assis, laisse molle, la rencontre a lieu seulement s’il reste calme.'], ['Mon chien adulte n’a pas été socialisé.', 'Un chien adulte peut apprendre aussi, plus lentement : désensibilisation progressive avec un éducateur formé.']],
  test: 'Le chiot aborde avec curiosité une dizaine de situations nouvelles sans peur excessive et se remet vite d’un bruit soudain.', safety: 'Consultez un comportementaliste si votre chiot manifeste une peur intense (tremblements persistants, évitement, agressivité de peur).' },

{ id: 'manipulations', free: false, icon: '🩺', cat: 'Soins', title: 'Manipulations et soins coopératifs (vétérinaire, griffes, brossage)', from: 8, dur: '3 min × 2 par jour', span: '4 à 8 semaines', level: 'Essentiel',
  goal: 'Votre chien accepte, voire apprécie, d’être touché, brossé, examiné, et de subir les soins de base (pattes, oreilles, gueule, griffes).',
  why: 'Les soins et le vétérinaire deviennent des moments de stress quand ils sont subis. Les enseigner comme un jeu, geste par geste, avec récompense et possibilité de dire stop, transforme la relation : moins de contention, moins de stress, et un examen vétérinaire bien plus serein.',
  need: ['Friandises très appétissantes', 'Brosse, coupe-griffes ou lime, coton, brosse à dents pour chien', 'Un tapis (Place)'],
  steps: [
    { t: 'Toucher = récompense', min: 2, b: 'Chien détendu, touchez une épaule un instant : « Oui ! » et friandise. Puis le dos, la poitrine, la patte, l’oreille, le museau, la queue. Un geste, une récompense. S’il se raidit, lèche sa truffe ou s’écarte, vous êtes allé trop vite.', crit: 'Il accepte le toucher sur les zones principales, détendu.' },
    { t: 'Le signal « stop » : le menton dans la main', min: 3, b: 'Apprenez-lui à poser le menton dans votre main pour dire « oui, allons-y ». S’il retire la tête, on s’arrête. Cela lui donne un choix et du contrôle : il coopère mieux.', crit: 'Il pose le menton et reste 3 secondes.' },
    { t: 'Pattes et griffes', min: 3, b: 'Prenez une patte 1 seconde, récompensez. Puis 3 secondes. Touchez la griffe. Montrez le coupe-griffes sans couper. Coupez une seule pointe, marquez, récompensez. Une griffe par séance au début.', crit: 'Il laisse couper une griffe calmement.' },
    { t: 'Oreilles, yeux, gueule, dents', min: 3, b: 'Soulevez la babine 1 seconde, récompensez. Touchez une dent avec le doigt. Introduisez la brosse à dents avec un peu d’enduit appétissant (spécial chien, jamais de dentifrice humain). Nettoyez les oreilles avec un coton humide sans enfoncer.', crit: 'Il accepte l’examen de la gueule et des oreilles.' },
    { t: 'Jouer au vétérinaire', min: 5, b: 'Simulez une consultation : table, examen de tout le corps, stéthoscope factice, prise de température (avec l’aide de votre vétérinaire si nécessaire), pesée sur une balance. Faites des visites « pour rien » chez le vétérinaire : friandises, caresse de l’équipe, départ.', crit: 'Il entre calmement dans la salle d’examen.' }
  ],
  mistakes: ['Contraindre un chien qui se débat : il associe les soins à la peur.', 'Enchaîner toutes les manipulations en une fois.', 'Négliger les signaux de stress (léchage de truffe, halètement, œil en coin).', 'Attendre le jour où une griffe est douloureuse pour commencer.'],
  faq: [['Il mord ou grogne quand on touche une zone.', 'La douleur est une cause fréquente : faites examiner par un vétérinaire. Ne le grondez pas : travaillez à distance de la zone sensible, avec un professionnel.'], ['Il déteste le coupe-griffes.', 'Commencez par la simple présence de l’outil, puis coupez une petite pointe, ou utilisez une lime électrique. En cas d’échec, faites appel à un toiletteur ou à la clinique.'], ['Il tremble chez le vétérinaire.', 'Faites des visites de familiarisation, arrivez tôt, attendez dehors, et parlez-en au vétérinaire (approche « sans peur »).']],
  test: 'Il accepte calmement 5 manipulations (patte, oreille, gueule, griffe, brossage) pendant 10 secondes chacune.', safety: 'Une douleur soudaine lors du toucher justifie une consultation ; ne forcez jamais un chien qui montre les dents.' },

{ id: 'sauter', free: false, icon: '🙌', cat: 'Savoir-vivre', title: 'Ne plus sauter sur les gens : saluer poliment', from: 10, dur: '3 min × 3 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien salue les personnes en gardant les quatre pattes au sol, même quand il est excité.',
  why: 'Le chien saute pour se rapprocher de notre visage, et parce qu’il est récompensé par de l’attention (même un « non ! » est de l’attention). On lui apprend une alternative plus payante : les pattes au sol, ou assis. Toute la famille et les visiteurs doivent appliquer la même règle.',
  need: ['Friandises', 'Une laisse pour la gestion', 'La collaboration des visiteurs'],
  steps: [
    { t: 'Récompenser les quatre pattes au sol', min: 3, b: 'Approchez-vous de votre chien : dès que ses quatre pattes sont au sol : « Oui ! » et friandise au sol. S’il saute, tournez le dos (sans parler, sans repousser) jusqu’à ce que les pattes touchent le sol. Attention : aucun contact visuel ni contact tant qu’il saute.', crit: 'Il ne saute plus vers vous dans la maison, 8 fois sur 10.' },
    { t: 'Une alternative : assis pour saluer', min: 3, b: 'Approchez-vous en demandant « Assis ». S’il s’assoit, récompensez et caressez. Un chien qui sait qu’asseoir fait venir l’attention essaiera d’abord de s’asseoir.', crit: 'Il s’assoit quand vous vous approchez, 8 fois sur 10.' },
    { t: 'Saluer un visiteur (sur laisse)', min: 5, b: 'Chien en laisse à la porte. Le visiteur avance seulement si le chien est calme ou assis ; s’il saute, le visiteur recule ou s’arrête. Le visiteur récompense l’assis. Répétez avec plusieurs personnes.', crit: 'Il reste assis pendant que le visiteur entre.' },
    { t: 'Généraliser', min: 5, b: 'Dans la rue, au parc, avec des enfants (sous surveillance étroite). Toujours la même règle : la personne n’approche et ne caresse que si le chien garde les pattes au sol.', crit: 'Salue poliment 5 personnes différentes.' }
  ],
  mistakes: ['Repousser ou crier : c’est de l’attention et parfois un jeu.', 'Genoux dans la poitrine ou marcher sur les pattes : dangereux et inutile.', 'Autoriser certains jours et pas d’autres : incohérence.', 'Laisser les enfants provoquer l’excitation.'],
  faq: [['Il saute seulement sur certaines personnes.', 'Ce sont celles qui l’encouragent (bruits aigus, câlins). Demandez-leur de rester calmes ou faites-les participer à l’exercice.'], ['Il saute après un long moment seul.', 'Faites-le sortir, dépenser de l’énergie, puis saluez calmement. Ne saluez pas en excitation.']],
  test: 'Il salue 5 personnes différentes avec les quatre pattes au sol ou assis.', safety: 'Un grand chien qui saute sur un enfant ou une personne âgée peut blesser : gardez-le en laisse pendant l’apprentissage.' }
];

/* Programme guidé Plus : 8 semaines pour un chiot */
const PROGRAMS = [
  { id: 'chiot8', icon: '🐶', title: 'Programme chiot : 8 semaines', sub: 'De l’arrivée à la maison au chiot serein', weeks: [
    ['Semaine 1', 'Installer les bases', ['marqueur', 'proprete', 'solitude']],
    ['Semaine 2', 'Premiers signaux', ['assis', 'manipulations', 'socialisation']],
    ['Semaine 3', 'Se poser', ['coucher', 'place']],
    ['Semaine 4', 'La maîtrise de soi', ['reste', 'laisse-le']],
    ['Semaine 5', 'Savoir-vivre', ['sauter']],
    ['Semaines 6 à 8', 'Dehors, en sécurité', ['laisse', 'rappel']]
  ] }
];
