/* Wouf Éducation — leçons chien (Wouf Plus), 6ᵉ série : soins du quotidien, santé et vie pratique.
   Renforcement positif uniquement, aucune contrainte physique ni punition.
   Contenu à faire relire par un vétérinaire ou un éducateur diplômé avant communication commerciale. */
LESSONS.push(

{ id: 'medicaments', free: false, icon: '💊', cat: 'Soins', title: 'Prendre un comprimé, des gouttes ou une pommade sans lutte', from: 10, dur: '2 min × 2 par jour', span: '1 à 3 semaines', level: 'Essentiel',
  goal: 'Votre chien avale ses comprimés sans les recracher, accepte les gouttes dans les yeux et les oreilles et se laisse appliquer une pommade, calmement.',
  why: 'Un jour ou l’autre, tout chien a besoin d’un traitement. Si chaque prise devient une bagarre, le traitement est mal suivi, le chien apprend à fuir et la relation en souffre. En préparant ces gestes à l’avance, « à blanc » et avec de bonnes récompenses, les soins deviennent une routine sans stress.',
  need: ['Friandises molles pour enrober (fromage frais, pâté, boulette de pâtée)', 'Un flacon vide de collyre ou d’oreilles pour l’entraînement', 'Le marqueur « Oui ! » déjà chargé', 'Une serviette et un tapis antidérapant'],
  steps: [
    { t: 'Le jeu des trois boulettes', min: 2, b: 'Préparez trois petites boulettes de fromage frais ou de pâté. Donnez la première (vide), puis la deuxième (avec le comprimé), puis tout de suite la troisième (vide). Le chien avale la deuxième sans la mâcher, pressé d’avoir la suivante. Entraînez-vous d’abord sans comprimé, plusieurs jours avant d’en avoir besoin.', crit: 'Il avale 3 boulettes d’affilée sans les mâcher ni les renifler longuement.' },
    { t: 'Donner un comprimé à la main (si nécessaire)', min: 2, b: 'Si le comprimé ne peut pas être caché, entraînez à blanc : main douce sur le museau, lèvre soulevée, friandise glissée au fond, bouche relâchée, puis caresse de la gorge et grosse récompense. Faites-le d’abord avec une friandise à la place du comprimé : le geste doit annoncer quelque chose de bon.', crit: 'Il vous laisse ouvrir doucement la gueule 3 secondes, 8 fois sur 10.' },
    { t: 'Les gouttes dans les yeux', min: 2, b: 'Placez-vous derrière ou à côté du chien, main en appui sous le menton. Approchez le flacon vide par le dessus de la tête (hors de son champ de vision), faites semblant, récompensez. Puis une vraie goutte de sérum physiologique, et récompense. Le flacon ne doit jamais arriver de face vers l’œil.', crit: 'Il reste immobile pendant qu’on approche le flacon de l’œil, 8 fois sur 10.' },
    { t: 'Les gouttes dans les oreilles', min: 3, b: 'Soulevez le pavillon, récompensez. Touchez l’entrée du conduit avec l’embout du flacon vide, récompensez. Massez la base de l’oreille comme lors d’un vrai soin, récompensez. Ajoutez ensuite une goutte de sérum tiédi dans la main (jamais froid). Laissez-le se secouer, c’est normal.', crit: 'Il accepte le massage de la base de l’oreille avec le flacon, 8 fois sur 10.' },
    { t: 'Le jour du vrai traitement', min: 3, b: 'Suivez exactement l’ordonnance (dose, horaire, durée) et notez chaque prise dans Wouf. Enchaînez toujours soin puis récompense spéciale (réservée aux soins). Si le chien se dérobe, ne le poursuivez pas : revenez à l’étape à blanc pendant un jour, puis réessayez.', crit: 'Le traitement est donné en entier, à l’heure, sans lutte.' }
  ],
  plan: [['Jours 1 à 3', 'Jeu des trois boulettes à vide, 2 fois par jour, et manipulation douce de la gueule.'], ['Jours 4 à 7', 'Flacon vide près des yeux et des oreilles, puis sérum physiologique.'], ['Semaine 2', 'Enchaîner une petite séance complète (bouche, yeux, oreilles) en 2 minutes.'], ['Ensuite', 'Une séance « à blanc » par semaine pour garder l’habitude, même sans traitement.']],
  next: ['Habituer le chien à la seringue sans aiguille (sirop, eau) avec du bouillon.', 'Apprendre le « menton posé » : il pose sa tête dans votre main et reste immobile pendant le soin.', 'Suivre la leçon « Manipulations et soins coopératifs ».'],
  mistakes: ['Écraser un comprimé ou l’ouvrir sans avis vétérinaire : certains ne doivent pas l’être.', 'Cacher le comprimé dans un aliment interdit (chocolat, raisin, xylitol, gros morceau de fromage gras).', 'Poursuivre le chien dans la maison : il apprend à fuir dès qu’il voit la boîte.', 'Arrêter le traitement dès que le chien va mieux sans l’accord du vétérinaire.'],
  faq: [['Il trie et recrache le comprimé.', 'Utilisez le jeu des trois boulettes avec une texture plus collante (pâtée écrasée), ou demandez au vétérinaire une forme appétente ou liquide.'], ['Il secoue la tête après les gouttes d’oreille.', 'C’est normal : massez avant de le lâcher pour faire descendre le produit, et essuyez l’excès avec une compresse.']],
  test: 'Il avale un comprimé caché, accepte une goutte dans chaque œil et dans chaque oreille, en moins de 2 minutes et sans chercher à fuir.', safety: 'Ne donnez jamais un médicament humain (paracétamol, ibuprofène…) sans avis vétérinaire : beaucoup sont toxiques pour le chien. En cas d’oubli ou de double dose, appelez votre vétérinaire.' },

{ id: 'griffes', free: false, icon: '✂️', cat: 'Soins', title: 'Couper les griffes sans stress', from: 10, dur: '2 min × 1 par jour', span: '2 à 6 semaines', level: 'Utile',
  goal: 'Votre chien donne sa patte, se laisse couper ou limer les griffes, une par une, en restant détendu, et vous savez éviter la partie vivante de l’ongle.',
  why: 'Des griffes trop longues déforment l’appui, font glisser, cassent et peuvent devenir douloureuses. Beaucoup de chiens redoutent la coupe à cause d’une mauvaise expérience (ongle coupé trop court). Une habituation lente, une griffe à la fois, permet de rendre ce soin rapide et serein.',
  need: ['Coupe-griffes adapté à la taille du chien, ou lime électrique', 'Poudre hémostatique (en cas de saignement)', 'Friandises très appréciées ou tapis de léchage', 'Une bonne lumière'],
  steps: [
    { t: 'Toucher et tenir la patte', min: 2, b: 'Touchez une patte, récompensez. Tenez-la 1 seconde, récompensez. Puis 3 secondes, puis écartez doucement les doigts. Travaillez les quatre pattes. Si le chien retire sa patte, lâchez, attendez qu’il se détende et reprenez plus facile.', crit: 'Il vous laisse tenir chaque patte 5 secondes, doigts écartés.' },
    { t: 'Présenter l’outil', min: 2, b: 'Montrez le coupe-griffes, récompensez. Faites-le claquer à distance, récompensez. Touchez une griffe avec l’outil fermé, récompensez. Pour une lime électrique : allumez-la à distance, puis rapprochez progressivement. Chaque apparition de l’outil annonce une friandise.', crit: 'Il reste détendu quand l’outil touche ses griffes.' },
    { t: 'Repérer la partie vivante', min: 3, b: 'Sur une griffe claire, la zone rosée (vaisseau et nerf) est visible : coupez 2 mm avant. Sur une griffe noire, coupez par très fines tranches : quand le centre de la tranche devient grisâtre, humide ou fait apparaître un point sombre, arrêtez-vous. En cas de doute, demandez une démonstration à votre vétérinaire.', crit: 'Vous savez où couper sur les griffes claires et comment procéder sur les griffes noires.' },
    { t: 'Une griffe par jour, puis plus', min: 2, b: 'Coupez une seule griffe, puis jackpot (plusieurs friandises) et fin de séance. Le lendemain, une autre. Quand c’est facile, passez à une patte par séance. Beaucoup de chiens acceptent mieux avec un tapis de léchage garni de pâté posé devant eux.', crit: 'Il accepte la coupe d’une patte entière sans se débattre.' },
    { t: 'L’entretien régulier', min: 2, b: 'Recoupez toutes les 3 à 6 semaines selon l’usure. N’oubliez pas l’ergot (le « pouce » à l’intérieur de la patte avant, parfois arrière) qui ne s’use jamais. Repère simple : quand le chien est debout, les griffes ne doivent pas toucher le sol.', crit: 'Les griffes ne touchent plus le sol quand il est debout.' }
  ],
  plan: [['Semaine 1', 'Toucher, tenir et écarter les doigts des 4 pattes, 2 minutes par jour.'], ['Semaine 2', 'Présenter l’outil et toucher les griffes sans couper.'], ['Semaines 3 et 4', 'Une griffe par jour, avec jackpot.'], ['Semaines 5 et 6', 'Une patte par séance, puis les 4 pattes en une séance.']],
  next: ['Apprendre au chien à gratter lui-même une planche recouverte de papier abrasif (griffes limées en jouant).', 'Faire contrôler les griffes à chaque visite vétérinaire.', 'Suivre « Debout : un chien facile à examiner ».'],
  mistakes: ['Couper toutes les griffes d’un coup avec un chien qui a peur.', 'Couper trop court : la douleur et le saignement laissent un souvenir durable.', 'Tenir le chien de force à plusieurs : il apprend que la coupe est une lutte.', 'Oublier les ergots, qui peuvent s’incarner.'],
  faq: [['J’ai coupé trop court, ça saigne.', 'Pas de panique : appliquez de la poudre hémostatique (ou de la farine) en pressant 1 à 2 minutes. Récompensez et arrêtez la séance. Consultez si le saignement ne s’arrête pas.'], ['Mon chien panique totalement.', 'Revenez aux premières étapes pendant plusieurs semaines, et demandez à votre vétérinaire ou toiletteur de le faire en attendant.']],
  test: 'Vous coupez les griffes des quatre pattes en une séance, sans saignement, et le chien reste sur place en prenant ses friandises.', safety: 'Une griffe cassée, arrachée ou qui saigne abondamment, ou un doigt gonflé, doivent être vus par un vétérinaire. Une griffe incarnée (souvent l’ergot) nécessite des soins.' },

{ id: 'brossage', free: false, icon: '🪮', cat: 'Soins', title: 'Brossage du pelage et entretien selon le type de poil', from: 8, dur: '5 min × 3 par semaine', span: '2 à 4 semaines', level: 'Utile',
  goal: 'Votre chien apprécie le brossage, vous utilisez la bonne brosse pour son pelage, et son poil reste propre, sans nœuds ni bourre accumulée.',
  why: 'Le brossage enlève les poils morts, évite les nœuds (qui tirent sur la peau et peuvent causer des lésions), permet de repérer tiques, grosseurs ou plaies, et limite les poils dans la maison. Chaque type de pelage a ses outils : une mauvaise brosse irrite la peau et dégoûte le chien du brossage.',
  need: ['La brosse adaptée (voir étape 1)', 'Un peigne métallique', 'Friandises', 'Un tapis ou une table antidérapante'],
  steps: [
    { t: 'Choisir le bon outil', min: 5, b: 'Poil court (labrador, beagle) : gant en caoutchouc ou brosse à poils souples. Poil mi-long avec sous-poil (berger, golden) : râteau et brosse étrille en période de mue. Poil long ou bouclé (caniche, bichon, yorkshire) : brosse carde souple et peigne, et toilettage professionnel régulier. Poil dur (terriers) : épilation (trimming) par un toiletteur. Demandez conseil si vous hésitez.', crit: 'Vous avez l’outil adapté au pelage de votre chien.' },
    { t: 'Un brossage qui fait du bien', min: 3, b: 'Commencez par les zones qu’il aime (dos, poitrail), quelques passages dans le sens du poil, puis friandise. Évitez au début les zones sensibles (pattes, queue, ventre, oreilles). Séances très courtes, arrêtées avant qu’il ne s’agite.', crit: 'Il reste détendu pendant 2 minutes de brossage sur le dos.' },
    { t: 'Les zones sensibles', min: 3, b: 'Ajoutez une zone sensible par séance : derrière les oreilles, sous les aisselles, culotte, queue, pattes. Ce sont les zones où se forment les nœuds. Tenez la peau à la base d’un nœud pour ne pas tirer, démêlez avec les doigts puis le peigne, ou coupez prudemment au ciseau à bouts ronds.', crit: 'Il accepte le peigne derrière les oreilles et sous les aisselles.' },
    { t: 'Inspecter en brossant', min: 2, b: 'Profitez du brossage pour vérifier la peau : rougeurs, pellicules, puces (petits grains noirs qui deviennent rouges sur un papier mouillé), tiques, grosseurs, plaies. Notez toute anomalie dans le journal de Wouf et montrez-la au vétérinaire.', crit: 'Vous inspectez la peau à chaque séance.' },
    { t: 'La routine selon la saison', min: 5, b: 'Poil court : 1 fois par semaine. Poil mi-long : 2 à 3 fois par semaine, tous les jours pendant la mue. Poil long : quotidien. Un chien bien brossé a moins besoin de bains. Ne rasez pas un chien à double pelage (husky, berger) : son sous-poil le protège aussi de la chaleur.', crit: 'Le brossage est fait au rythme adapté à son pelage.' }
  ],
  plan: [['Semaine 1', '2 minutes de brossage sur les zones agréables, 3 fois dans la semaine.'], ['Semaine 2', 'Ajouter une zone sensible par séance.'], ['Semaine 3', 'Brossage complet de 5 minutes avec inspection de la peau.'], ['Semaine 4 et suivantes', 'Routine adaptée au pelage, plus fréquente pendant la mue.']],
  next: ['Suivre « Bain, séchage et toilettage sans stress ».', 'Préparer le chien au toiletteur (table, sèche-cheveux, tondeuse) avec les mêmes étapes.', 'Suivre « Couper les griffes sans stress ».'],
  mistakes: ['Tirer sur les nœuds : c’est douloureux et le chien fuira la brosse.', 'Utiliser une brosse trop dure sur un poil court (irritations).', 'Raser un chien à double pelage en été.', 'Faire de longues séances quand le chien n’est pas encore habitué.'],
  faq: [['Il mord la brosse.', 'Donnez-lui un tapis de léchage ou une mâchouille pendant le brossage, et faites des séances plus courtes.'], ['Son poil est plein de nœuds serrés.', 'Ne forcez pas : un toiletteur professionnel pourra tondre les zones feutrées sans douleur, puis vous reprendrez un entretien régulier.']],
  test: 'Il accepte un brossage complet de 5 minutes, zones sensibles comprises, sans chercher à partir.', safety: 'Une peau rouge, suintante, qui sent mauvais, ou une perte de poils par plaques justifie une consultation. Attention aux épillets (graminées) pris dans les poils entre les doigts et dans les oreilles en été : ils peuvent s’enfoncer sous la peau.' },

{ id: 'canicross', free: false, icon: '🏃', cat: 'Bien-être', title: 'Courir avec son chien : canicross, jogging et vélo', from: 52, dur: '15 à 30 min × 2 par semaine', span: '6 à 10 semaines', level: 'Intermédiaire',
  goal: 'Votre chien court avec vous à un rythme adapté, en harnais de traction ou en laisse, répond aux signaux de direction et termine ses sorties en forme.',
  why: 'Courir ensemble est idéal pour un chien énergique : dépense physique, complicité, meilleur équilibre émotionnel. Mais un chien n’est pas un coureur de fond instantané : croissance, chaleur, coussinets et cœur imposent une progression aussi prudente que pour un humain.',
  need: ['Harnais de traction adapté (canicross), ceinture et ligne élastique', 'Eau et gamelle pliable', 'Un vétérinaire pour un bilan avant de commencer', 'Des chemins en terre plutôt que du bitume'],
  steps: [
    { t: 'Vérifier l’âge et la forme', min: 5, b: 'Attendez la fin de la croissance (environ 12 mois pour les petits et moyens gabarits, 18 mois pour les grands) avant la course régulière. Faites faire un bilan (articulations, cœur, poids). Les chiens à museau court ou très lourds ne sont pas faits pour la course.', crit: 'Le vétérinaire a validé la course pour votre chien.' },
    { t: 'Apprendre les signaux', min: 5, b: 'En marchant, apprenez « Droite », « Gauche », « Doucement », « Stop » et « En avant », en récompensant chaque réponse. Ces signaux permettront de courir en sécurité sans tirer sur la ligne.', crit: 'Il répond à « Stop » et « Doucement » en marchant, 8 fois sur 10.' },
    { t: 'Commencer par l’alternance marche-course', min: 20, b: 'Première semaine : 1 minute de course, 2 minutes de marche, 5 fois. Augmentez de 10 % par semaine environ. Laissez des pauses reniflage : elles font partie du plaisir. Arrêtez-vous au moindre signe de fatigue (langue très pendante, ralentissement, envie de se coucher).', crit: 'Il enchaîne 20 minutes d’alternance sans fatigue excessive.' },
    { t: 'Adapter le terrain et la météo', min: 5, b: 'Privilégiez la terre, l’herbe, les chemins forestiers. Évitez de courir au-dessus de 20 °C (15 °C pour un chien sensible), et jamais aux heures chaudes. Consultez la météo balade de Wouf. Emportez de l’eau et proposez-la toutes les 10 à 15 minutes.', crit: 'Vous ne courez que par temps frais et sur sol souple.' },
    { t: 'Le vélo en sécurité', min: 10, b: 'Pour le vélo, utilisez une barre d’attelage spécifique (jamais la laisse tenue à la main). Commencez par marcher à côté du vélo, puis rouler au pas. Le chien doit trotter, pas galoper. Sorties courtes, sur chemins calmes.', crit: 'Il trotte régulièrement à côté du vélo pendant 10 minutes.' }
  ],
  plan: [['Semaine 1', 'Bilan vétérinaire et apprentissage des signaux en marchant.'], ['Semaines 2 à 4', 'Alternance marche-course, 2 sorties par semaine.'], ['Semaines 5 à 7', 'Course continue de 15 à 20 minutes.'], ['Semaines 8 à 10', 'Sorties de 30 minutes, ou premiers essais à vélo.']],
  next: ['Rejoindre un club de canicross pour découvrir la discipline en groupe.', 'Suivre « Partir en randonnée avec son chien ».', 'Tenir le compte des sorties dans les balades Wouf pour suivre la progression.'],
  mistakes: ['Courir avec un chiot : risque pour les articulations.', 'Courir par forte chaleur ou juste après le repas (risque de retournement d’estomac chez les grands chiens).', 'Augmenter trop vite la distance.', 'Utiliser un collier au lieu d’un harnais de traction.'],
  faq: [['Il tire trop fort.', 'En canicross, la traction est souhaitée mais doit rester contrôlée : utilisez une ligne élastique et travaillez « Doucement ».'], ['Il s’arrête tout le temps.', 'C’est peut-être trop long ou trop chaud : réduisez la durée et laissez-lui du temps pour renifler.']],
  test: 'Il court 20 minutes à vos côtés, répond à « Stop » et « Doucement », et récupère normalement dans l’heure qui suit.', safety: 'Ne faites jamais courir un chien juste après un repas : attendez 2 heures (risque de dilatation-torsion de l’estomac chez les grands chiens). Signes d’alerte à la course : boiterie, halètement intense, gencives très rouges ou pâles, titubation : arrêtez immédiatement et mettez-le au frais.' },

{ id: 'parcours', free: false, icon: '🏅', cat: 'Jeu', title: 'Mini-agility à la maison et au jardin', from: 26, dur: '10 min × 2 par semaine', span: '4 à 8 semaines', level: 'Intermédiaire',
  goal: 'Votre chien franchit un petit parcours (tunnel, slalom, sauts bas, table) sur vos signaux, avec entrain et en sécurité.',
  why: 'L’agility développe la coordination, la confiance, la complicité et fatigue autant le corps que l’esprit. Un parcours maison, avec des obstacles bas et sûrs, suffit à apporter ces bienfaits sans risque pour les articulations.',
  need: ['Manches à balai et plots ou livres (sauts bas)', 'Un tunnel pour enfant ou des chaises recouvertes d’un drap', 'Cônes ou bouteilles pour le slalom', 'Friandises et jouet préféré'],
  steps: [
    { t: 'Le saut bas', min: 5, b: 'Posez un manche au sol entre deux livres. Guidez le chien avec une friandise pour qu’il l’enjambe, dites « Hop ! », récompensez. Montez à peine la barre (hauteur du poignet au maximum). Le but est la coordination, pas la hauteur.', crit: 'Il franchit la barre basse sur « Hop ! », 8 fois sur 10.' },
    { t: 'Le tunnel', min: 5, b: 'Commencez avec un tunnel très court ou replié. Une personne tient le chien à l’entrée, l’autre l’appelle depuis la sortie avec une friandise. Allongez progressivement. Ne poussez jamais un chien dans le tunnel.', crit: 'Il traverse le tunnel entier seul sur « Tunnel ! ».' },
    { t: 'Le slalom', min: 5, b: 'Placez 4 plots espacés d’un mètre. Guidez le chien lentement à la friandise entre les plots, entrée par la droite du premier. Récompensez à la sortie. Rapprochez progressivement les plots. Allez lentement : la précision avant la vitesse.', crit: 'Il fait le slalom de 4 plots guidé par votre main.' },
    { t: 'La table (l’arrêt)', min: 3, b: 'Utilisez un tapis ou une plateforme stable et basse. Faites monter le chien, « Couché », comptez 3 secondes, puis « Libre ! ». C’est l’obstacle de la maîtrise de soi, utile pour calmer l’excitation au milieu du parcours.', crit: 'Il se couche sur la plateforme 3 secondes au milieu du jeu.' },
    { t: 'Enchaîner le parcours', min: 10, b: 'Reliez deux obstacles, puis trois, puis tout le parcours. Courez à côté du chien en montrant l’obstacle avec votre bras. Finissez toujours par un grand jeu. Si le chien se trompe, recommencez joyeusement, sans reproche.', crit: 'Il enchaîne 4 obstacles sur vos signaux, avec entrain.' }
  ],
  plan: [['Semaines 1 et 2', 'Saut bas et tunnel, séparément.'], ['Semaines 3 et 4', 'Slalom guidé et table.'], ['Semaines 5 et 6', 'Enchaînements de 2 et 3 obstacles.'], ['Semaines 7 et 8', 'Parcours complet, changement d’ordre des obstacles.']],
  next: ['Rejoindre un club d’agility pour du matériel adapté et un encadrement.', 'Travailler l’envoi à distance : « Tunnel ! » depuis 3 mètres.', 'Suivre « La gym du chien : équilibre, force et conscience du corps ».'],
  mistakes: ['Faire sauter haut un jeune chien ou un chien lourd.', 'Utiliser des obstacles instables ou glissants.', 'Faire de longues séances : l’excitation augmente les risques de blessure.', 'Gronder une erreur : le chien perd confiance et entrain.'],
  faq: [['Il contourne le saut.', 'Placez le saut entre deux murs ou meubles pour guider sa trajectoire, puis retirez-les peu à peu.'], ['Il a peur du tunnel.', 'Raccourcissez-le à l’extrême, voire commencez sans drap, et récompensez chaque pas dedans.']],
  test: 'Il enchaîne saut, tunnel, slalom de 4 plots et table sur vos signaux, avec entrain, sans faute de sécurité.', safety: 'Pas de sauts avant la fin de la croissance, ni pour un chien en surpoids, âgé ou avec des problèmes articulaires. Travaillez sur un sol non glissant et arrêtez au moindre signe de boiterie.' },

{ id: 'tir', free: false, icon: '🪢', cat: 'Jeu', title: 'Le jeu de tir (tug) avec des règles : « Prends » et « Lâche »', from: 12, dur: '5 min × 1 par jour', span: '1 à 3 semaines', level: 'Débutant',
  goal: 'Votre chien joue à tirer sur un jouet avec entrain, lâche immédiatement sur « Lâche », attend « Prends » pour reprendre, et ne touche jamais vos mains.',
  why: 'Contrairement à une idée reçue, jouer à tirer ne rend pas un chien dominant ou agressif. Avec des règles claires, c’est même un excellent outil : dépense d’énergie, récompense puissante, maîtrise de soi (lâcher en pleine excitation) et complicité.',
  need: ['Un jouet long et solide (corde, boudin de traction)', 'Friandises', 'Un endroit dégagé'],
  steps: [
    { t: 'Donner envie de prendre', min: 3, b: 'Faites bouger le jouet au sol comme une proie qui s’enfuit, pas vers le visage du chien. Dès qu’il l’attrape, dites « Prends ! » et tirez doucement, à l’horizontale, sans secouer sa tête. Laissez-le gagner souvent : c’est ce qui rend le jeu motivant.', crit: 'Il attrape le jouet et tire avec entrain.' },
    { t: 'Apprendre « Lâche »', min: 3, b: 'Arrêtez de tirer : tenez le jouet immobile contre votre jambe, le jeu devient ennuyeux. Présentez une friandise devant sa truffe. Dès qu’il ouvre la gueule, « Lâche ! », friandise, puis relancez tout de suite le jeu avec « Prends ! ». Il apprend que lâcher relance le jeu.', crit: 'Il lâche en moins de 3 secondes sur « Lâche », 8 fois sur 10.' },
    { t: 'Attendre le signal pour reprendre', min: 3, b: 'Après « Lâche », tenez le jouet quelques secondes. S’il saute dessus, cachez-le derrière votre dos. Quand il attend (assis ou simplement calme), « Prends ! ». Il apprend à contrôler son excitation.', crit: 'Il attend « Prends » 3 secondes après avoir lâché.' },
    { t: 'La règle des dents', min: 2, b: 'Si ses dents touchent votre main, même par accident, dites calmement « Oups », et arrêtez le jeu 10 secondes (jouet caché). Utilisez un jouet long pour éloigner vos mains. Il apprend à viser le jouet avec précision.', crit: 'Aucun contact de dents sur la peau pendant 3 séances.' },
    { t: 'Utiliser le jeu comme récompense', min: 5, b: 'Une fois les règles acquises, le jeu de tir devient une récompense pour les exercices difficiles (rappel, au pied, Stop). Terminez toujours par un « Lâche » réussi, puis rangez le jouet : il reste précieux.', crit: 'Vous utilisez le jeu de tir pour récompenser un rappel.' }
  ],
  plan: [['Jours 1 à 3', 'Donner envie de prendre, jeu de 2 minutes.'], ['Jours 4 à 7', 'Lâche contre friandise, puis relance.'], ['Semaine 2', 'Attente avant « Prends », règle des dents.'], ['Semaine 3', 'Le jeu comme récompense des exercices.']],
  next: ['Utiliser le jeu de tir pour récompenser le rappel.', 'Voir « Laisse-le et Donne : ne pas ramasser, savoir lâcher ».', 'Suivre « Maîtrise de soi : le jeu du « c’est ton choix » ».'],
  mistakes: ['Tirer de haut en bas ou secouer fort : risque pour le cou et les dents, surtout chez le chiot.', 'Ne jamais le laisser gagner : il se décourage.', 'Laisser le jouet en libre accès : il perd sa valeur.', 'Jouer avec un chien qui grogne réellement en gardant le jouet : voir la leçon sur la garde de ressources.'],
  faq: [['Il ne lâche jamais.', 'Rendez le jouet inintéressant (immobile), et proposez une friandise très alléchante ; il apprendra vite que lâcher est payant.'], ['Il grogne en jouant.', 'Un grognement de jeu est normal s’il reste joyeux (corps souple, queue qui bouge). S’il se fige ou fixe, arrêtez et consultez un professionnel.']],
  test: 'Pendant un jeu intense, il lâche sur « Lâche » en moins de 3 secondes, attend « Prends » et ne touche jamais vos mains.', safety: 'Évitez le jeu de tir avec un chiot en poussée dentaire (secouez peu, tirez doucement) et avec un chien qui a des problèmes de dos ou de cou. Les enfants ne doivent jouer qu’avec un chien qui maîtrise parfaitement « Lâche », sous surveillance.' },

{ id: 'longe', free: false, icon: '🧵', cat: 'Balades', title: 'La longe : de la liberté en toute sécurité', from: 12, dur: 'À chaque balade', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien profite de la balade au bout d’une longe de 5 à 10 mètres sans s’y emmêler, revient quand vous l’appelez, et vous manipulez la longe sans vous brûler les mains.',
  why: 'La longe est le lien entre la laisse et la liberté : elle permet au chien de courir, de renifler et d’explorer tout en restant en sécurité, pendant l’apprentissage du rappel ou pour un chien qui chasse ou fugue. Mal utilisée, elle peut blesser ; bien utilisée, elle transforme les balades.',
  need: ['Une longe de 5 à 10 mètres, plate et légère (biothane de préférence)', 'Un harnais (jamais un collier)', 'Des gants si le chien tire', 'Friandises'],
  steps: [
    { t: 'Toujours sur un harnais', min: 3, b: 'Attachez la longe à l’anneau dorsal d’un harnais bien ajusté. Un arrêt brusque au bout de 10 mètres sur un collier peut blesser gravement la gorge et les cervicales. Vérifiez l’ajustement : deux doigts sous les sangles.', crit: 'La longe est toujours attachée à un harnais bien ajusté.' },
    { t: 'Manier la longe en boucles', min: 5, b: 'Tenez la longe en boucles souples dans une main, l’extrémité passée autour du poignet (pas autour des doigts). Laissez filer ou reprenez selon la distance. Gardez-la légèrement tendue au sol, sans la laisser traîner en tas où le chien pourrait s’emmêler.', crit: 'Vous laissez filer et reprenez 5 mètres sans vous emmêler.' },
    { t: 'Freiner en douceur', min: 5, b: 'Quand le chien arrive au bout, ralentissez la longe progressivement (comme un frein), jamais d’un coup sec. Mieux : dites « Doucement » avant qu’il n’arrive au bout, récompensez quand il ralentit. Il apprend à respecter la longueur.', crit: 'Il ralentit sur « Doucement » avant la fin de la longe, 8 fois sur 10.' },
    { t: 'Rappels récompensés', min: 5, b: 'Pendant la balade, appelez-le souvent, récompensez généreusement, puis relâchez-le avec « Va jouer ! ». La plupart des rappels ne doivent pas signifier la fin de la liberté. Si besoin, reprenez doucement la longe pour l’aider à revenir.', crit: 'Il revient au rappel sur longe, 9 fois sur 10.' },
    { t: 'Choisir le bon terrain', min: 3, b: 'Évitez les zones avec arbres serrés, ronces, routes, vélos, et les parcs très fréquentés. Préférez les grands espaces ouverts. Ne laissez jamais traîner une longe près de la route.', crit: 'Vous utilisez la longe dans des lieux adaptés.' }
  ],
  plan: [['Semaine 1', 'Longe de 5 mètres, manipulation et freinage progressif.'], ['Semaine 2', 'Rappels réguliers récompensés, relâchés.'], ['Semaine 3', 'Longe de 10 mètres, terrains variés.'], ['Semaine 4', 'Laisser traîner la longe (en lieu sûr) pour préparer la liberté.']],
  next: ['Suivre « Rappel : « Ici ! » fiable ».', 'Suivre « Stop et demi-tour d’urgence ».', 'Suivre « Instinct de chasse : vélos, joggers, chats et gibier ».'],
  mistakes: ['Utiliser une longe sur un collier.', 'Enrouler la longe autour des doigts : risque de brûlure ou de fracture.', 'Laisser le chien atteindre le bout à pleine vitesse.', 'Utiliser une laisse enrouleur comme longe : elle apprend à tirer et peut blesser.'],
  faq: [['La longe s’emmêle dans les jambes.', 'Gardez-la en boucles, légèrement tendue, et apprenez au chien à passer d’un côté à l’autre à l’arrêt.'], ['Il tire toujours au bout.', 'Travaillez « Doucement » et récompensez beaucoup quand il reste proche.']],
  test: 'Pendant une balade de 30 minutes, il explore librement sur longe, ralentit sur « Doucement » et revient au rappel 9 fois sur 10.', safety: 'Ne laissez jamais traîner une longe sans surveillance (risque d’étranglement). Évitez les longes rondes et fines qui brûlent les mains. Ne remplacez pas la laisse par une longe en ville ou près d’une route.' },

{ id: 'equipement', free: false, icon: '🦺', cat: 'Soins', title: 'Accepter le harnais, le manteau, les bottines et le gilet', from: 8, dur: '3 min × 2 par jour', span: '1 à 3 semaines', level: 'Utile',
  goal: 'Votre chien tend la tête dans le harnais, accepte le manteau, marche normalement avec des bottines et porte un gilet réfléchissant ou de flottaison sans stress.',
  why: 'Beaucoup de chiens se figent, se roulent ou fuient à la vue du harnais ou d’un manteau, car on leur impose d’un coup quelque chose d’étrange. Une habituation progressive permet d’utiliser l’équipement utile (sécurité, froid, sel, blessure) sans conflit.',
  need: ['Harnais en Y bien ajusté', 'Manteau, bottines ou gilet adapté', 'Friandises', 'Un endroit calme'],
  steps: [
    { t: 'Rendre l’objet attrayant', min: 2, b: 'Posez le harnais au sol, laissez-le le renifler, récompensez. Tenez-le en main, récompensez chaque fois que le chien s’en approche. L’objet doit annoncer quelque chose de bon.', crit: 'Il s’approche volontairement du harnais.' },
    { t: 'La tête dans le harnais', min: 3, b: 'Tenez l’ouverture du harnais, placez une friandise de l’autre côté. Le chien passe la tête pour la prendre, puis ressort. Répétez. Ensuite, attendez une seconde avant de donner la friandise, puis fermez une boucle, récompensez, retirez.', crit: 'Il passe la tête dans le harnais de lui-même, 8 fois sur 10.' },
    { t: 'Le manteau', min: 3, b: 'Posez le manteau sur son dos 2 secondes, récompensez, retirez. Puis fermez une sangle, puis toutes. Faites quelques pas dans la maison avec des friandises. Choisissez un manteau qui ne gêne pas les pattes ni les besoins.', crit: 'Il marche normalement avec le manteau fermé.' },
    { t: 'Les bottines', min: 5, b: 'Une bottine à la fois, 2 secondes, puis retirez. Au début, le chien lève les pattes de façon comique : c’est normal. Marchez avec lui, lancez un jeu pour qu’il oublie ses pattes. Ajoutez une bottine par séance.', crit: 'Il marche normalement avec 4 bottines pendant 5 minutes.' },
    { t: 'L’utiliser dehors', min: 10, b: 'Dès que le chien le porte sans gêne à la maison, faites une vraie balade. Vérifiez l’ajustement (pas de frottement sous les aisselles), et retirez l’équipement au retour. Le chien associe le harnais à la balade : il finira par venir de lui-même.', crit: 'Il vient spontanément quand il voit son harnais.' }
  ],
  plan: [['Jours 1 à 3', 'Harnais au sol, puis tête dans le harnais avec friandise.'], ['Jours 4 à 7', 'Harnais fermé, manteau sur le dos.'], ['Semaine 2', 'Bottines une par une, marche dans la maison.'], ['Semaine 3', 'Sorties avec l’équipement complet.']],
  next: ['Utiliser les bottines en montagne, sur le sel de déneigement ou pour une plaie aux coussinets.', 'Voir « Aimer l’eau : baignade et sécurité aquatique » pour le gilet de flottaison.', 'Voir « Muselière : un conditionnement positif ».'],
  mistakes: ['Enfiler le harnais de force en tenant le chien.', 'Choisir un harnais qui bloque les épaules (sangle horizontale devant le poitrail).', 'Laisser le manteau toute la journée, même à la maison.', 'Mettre les 4 bottines d’un coup et partir en balade.'],
  faq: [['Il se fige avec le manteau.', 'C’est fréquent au début : restez calme, lancez un jeu ou une friandise pour qu’il bouge, et raccourcissez la durée.'], ['Le harnais frotte.', 'Vérifiez les sangles sous les aisselles : il faut deux doigts d’espace ; changez de modèle si besoin.']],
  test: 'Il tend la tête dans le harnais, porte un manteau et 4 bottines, et marche normalement pendant une balade de 15 minutes.', safety: 'Vérifiez chaque semaine que l’équipement ne blesse pas (poils cassés, rougeurs). Retirez toujours le harnais et le manteau pour laisser le chien seul, afin d’éviter qu’il ne s’y accroche.' },

{ id: 'relaxation', free: false, icon: '😌', cat: 'Calme', title: 'Le protocole de relaxation : apprendre à se détendre sur demande', from: 12, dur: '5 à 10 min × 1 par jour', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien se couche sur son tapis, se détend (hanche basculée, respiration lente) et reste calme pendant que vous vous déplacez, ouvrez une porte ou qu’on sonne.',
  why: 'Beaucoup de chiens ne savent pas « ne rien faire ». Apprendre à se détendre sur son tapis, par petites étapes récompensées, est un outil très puissant contre l’excitation, l’anxiété et la réactivité. Le tapis devient un refuge apaisant, emportable partout.',
  need: ['Un tapis ou une couverture qui ne sert qu’à cela', 'Friandises calmes (pas trop excitantes)', 'Une pièce calme', 'Un minuteur'],
  steps: [
    { t: 'Le tapis, un endroit qui rapporte', min: 5, b: 'Posez le tapis. Récompensez chaque fois que le chien le regarde, s’en approche, pose une patte, puis s’y couche. Déposez les friandises entre ses pattes, calmement, sans parole excitante. Voir aussi la leçon « La Place ».', crit: 'Il va se coucher sur le tapis de lui-même dès que vous le posez.' },
    { t: 'Récompenser les signes de détente', min: 5, b: 'Quand il est couché, récompensez les petits signes de relâchement : hanche basculée sur le côté, tête posée, soupir, clignement lent. Ne demandez rien : vous observez et récompensez calmement.', crit: 'Il bascule sur une hanche et pose sa tête en moins de 2 minutes.' },
    { t: 'Ajouter de la durée', min: 5, b: 'Espacez les récompenses : toutes les 3 secondes, puis 5, 10, 20, 30. S’il se lève, pas de reproche : retournez vers le tapis et reprenez plus facile.', crit: 'Il reste détendu 2 minutes entre deux récompenses.' },
    { t: 'Ajouter vos mouvements', min: 10, b: 'Faites un pas en arrière, récompensez. Puis tournez-vous, asseyez-vous, levez-vous, faites 5 pas, ouvrez un placard, frappez à la porte. Une seule difficulté à la fois, en récompensant le calme. C’est le cœur du protocole : il apprend à rester calme pendant que le monde bouge.', crit: 'Il reste couché pendant que vous marchez dans la pièce.' },
    { t: 'L’emmener partout', min: 10, b: 'Emportez le tapis au café, chez le vétérinaire, chez des amis, en vacances. Son effet apaisant voyage avec lui. Terminez toujours la séance par « Libre ! » : c’est vous qui décidez quand le calme s’arrête.', crit: 'Il se détend sur son tapis dans un lieu extérieur.' }
  ],
  plan: [['Semaine 1', 'Le tapis rapporte, signes de détente récompensés.'], ['Semaine 2', 'Durée de 30 secondes à 2 minutes.'], ['Semaines 3 et 4', 'Vos mouvements autour, puis bruits (porte, sonnette).'], ['Semaines 5 et 6', 'Le tapis dans d’autres lieux (café, vétérinaire).']],
  next: ['Utiliser le tapis pendant l’arrivée des visiteurs.', 'Suivre « Chien réactif en laisse » en utilisant le tapis comme lieu de repos.', 'Suivre « Bruits forts, orages et pétards ».'],
  mistakes: ['Donner les friandises de façon excitante (voix aiguë, gestes rapides).', 'Aller trop vite dans la durée ou la difficulté.', 'Utiliser le tapis comme une punition (« Va au panier ! »).', 'Oublier le signal de fin : il se lève quand il veut.'],
  faq: [['Il ne tient pas en place.', 'Faites d’abord une balade ou un jeu de flair, puis commencez la séance quand il est un peu fatigué.'], ['Il s’endort sur le tapis.', 'Excellent : c’est exactement le but. Laissez-le dormir.']],
  test: 'Il reste couché et détendu sur son tapis pendant 5 minutes pendant que vous vous déplacez, ouvrez une porte et qu’on frappe.', safety: 'Un chien qui n’arrive jamais à se détendre, halète ou tourne en rond sans raison peut souffrir ou être très anxieux : parlez-en à votre vétérinaire.' },

{ id: 'train-avion', free: false, icon: '✈️', cat: 'Voyage', title: 'Voyager en train et en avion avec son chien', from: 16, dur: 'Préparation sur 3 à 6 semaines', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien voyage en train ou en avion sereinement, dans son sac ou sa caisse, avec tous les documents et l’équipement nécessaires.',
  why: 'Chaque compagnie a ses règles (poids, taille du sac, muselière, soute ou cabine) et certains pays exigent des vaccins, tests ou traitements précis. Une préparation soigneuse évite les refus d’embarquement et un stress inutile pour le chien.',
  need: ['Sac ou caisse de transport conforme à la compagnie', 'Passeport européen et vaccins à jour (selon destination)', 'Muselière conditionnée (souvent exigée en train pour les grands chiens)', 'Tapis absorbant, eau, friandises'],
  steps: [
    { t: 'Se renseigner sur les règles', min: 15, b: 'Vérifiez sur le site de la compagnie : taille et poids maximum en cabine, tarif, muselière, nombre d’animaux par voyage. Pour l’étranger, consultez les exigences du pays (vaccin antirabique, identification, parfois titrage ou traitement antiparasitaire) plusieurs mois à l’avance avec votre vétérinaire.', crit: 'Vous connaissez les règles de la compagnie et du pays de destination.' },
    { t: 'Habituer au sac ou à la caisse', min: 5, b: 'Laissez la caisse ouverte à la maison, avec couverture et friandises. Fermez-la quelques secondes, puis minutes. Portez-la en marchant. Le chien doit s’y reposer volontairement avant le voyage.', crit: 'Il reste 30 minutes détendu dans sa caisse fermée.' },
    { t: 'Simuler le voyage', min: 20, b: 'Faites un trajet court en bus, en tram ou en voiture avec le sac ou la caisse. Allez à la gare ou à l’aéroport sans voyager, pour l’habituer aux bruits et à la foule. Récompensez le calme.', crit: 'Il reste calme dans son sac au milieu d’une gare.' },
    { t: 'Le jour du voyage', min: 10, b: 'Léger repas 4 heures avant, sortie juste avant de partir, tapis absorbant dans la caisse, eau à proposer pendant les pauses. Ne donnez jamais de calmant sans avis vétérinaire : certains sont déconseillés en avion. Arrivez tôt pour éviter la précipitation.', crit: 'Le chien part le ventre léger, la vessie vide et son équipement prêt.' },
    { t: 'À l’arrivée', min: 10, b: 'Faites faire ses besoins dès que possible, proposez de l’eau, laissez-le explorer calmement. Installez son tapis et ses affaires familières. Repérez le vétérinaire le plus proche avec Wouf (onglet SOS).', crit: 'Il retrouve rapidement ses habitudes à l’arrivée.' }
  ],
  plan: [['2 à 3 mois avant', 'Règles du pays et de la compagnie, vaccins et documents.'], ['3 à 6 semaines avant', 'Habituation au sac ou à la caisse, muselière.'], ['2 semaines avant', 'Simulations dans les transports et à la gare.'], ['Le jour J', 'Repas léger, sortie avant le départ, arrivée en avance.']],
  next: ['Suivre « Partir en vacances avec son chien ».', 'Suivre « Muselière : un conditionnement positif ».', 'Préparer la fiche gardien si vous confiez le chien à quelqu’un sur place.'],
  mistakes: ['Découvrir les règles à la gare ou à l’aéroport.', 'Utiliser la caisse pour la première fois le jour du voyage.', 'Donner un calmant sans avis vétérinaire.', 'Oublier l’eau et les pauses.'],
  faq: [['Mon chien peut-il voyager en soute ?', 'C’est possible mais stressant ; renseignez-vous auprès du vétérinaire et de la compagnie, et évitez-le pour les chiens à museau court (risques respiratoires).'], ['Il aboie dans le train.', 'Réduisez le stress par l’habituation préalable, donnez-lui un jouet à mâcher et restez près de lui.']],
  test: 'Il reste calme 1 heure dans son sac ou sa caisse lors d’un trajet en train, sans aboyer ni gratter.', safety: 'Les chiens à museau court (bouledogues, carlins) sont très sensibles à la chaleur et au stress respiratoire : de nombreuses compagnies les refusent en soute. Demandez toujours l’avis de votre vétérinaire avant un vol.' },

{ id: 'pension', free: false, icon: '🏨', cat: 'Voyage', title: 'Préparer une garde : pension, pet-sitter ou famille', from: 12, dur: 'Préparation sur 2 à 4 semaines', span: '2 à 4 semaines', level: 'Utile',
  goal: 'Votre chien passe une garde (pension, pet-sitter ou famille) sans stress, avec ses habitudes respectées et toutes les informations transmises.',
  why: 'Une absence est plus facile pour le chien s’il connaît déjà le lieu ou la personne, et si ses repères (nourriture, rythme, objets) sont conservés. Une préparation progressive et une fiche claire évitent les oublis et les incidents.',
  need: ['La fiche gardien de Wouf', 'Vaccins et antiparasitaires à jour (souvent exigés par les pensions)', 'Sa nourriture habituelle, son couchage et un vêtement à votre odeur', 'Numéros utiles : vétérinaire, vous, une personne de confiance'],
  steps: [
    { t: 'Choisir la bonne garde', min: 20, b: 'Visitez la pension (propreté, espaces, promenades, nombre de chiens, surveillance la nuit) ou rencontrez le pet-sitter. Posez vos questions : que se passe-t-il en cas de problème de santé ? Quel vétérinaire ? Vérifiez les avis et les assurances.', crit: 'Vous avez visité le lieu ou rencontré la personne.' },
    { t: 'Un essai court', min: 60, b: 'Organisez une demi-journée ou une nuit d’essai, quelques semaines avant. Observez l’état du chien au retour. C’est l’occasion d’ajuster les consignes.', crit: 'Le chien revient détendu d’un essai court.' },
    { t: 'Remplir la fiche gardien', min: 15, b: 'Dans Wouf, remplissez la fiche gardien : repas (quantité, horaires), traitements, habitudes, peurs, signes à surveiller, contacts. Imprimez-la ou envoyez-la. Précisez aussi les règles importantes : laisse obligatoire, pas de contact avec d’autres chiens, etc.', crit: 'La fiche gardien est complète et transmise.' },
    { t: 'Préparer ses affaires', min: 10, b: 'Nourriture habituelle pesée en portions (un changement brutal donne souvent la diarrhée), son couchage, un jouet, un vêtement à votre odeur, laisse et harnais de rechange, carnet de santé et traitements.', crit: 'Son sac est prêt avec la nourriture en portions.' },
    { t: 'Le départ et le retour', min: 5, b: 'Au moment de le déposer, restez bref et calme. Au retour, retrouvailles calmes, repas léger, beaucoup de repos. Une légère fatigue ou des selles molles les premiers jours sont fréquentes ; consultez si cela dure.', crit: 'Il retrouve son rythme dans les 48 heures.' }
  ],
  plan: [['4 semaines avant', 'Choisir la pension ou le pet-sitter, vérifier vaccins et antiparasitaires.'], ['2 semaines avant', 'Essai d’une demi-journée ou d’une nuit.'], ['1 semaine avant', 'Fiche gardien complétée, sac préparé.'], ['Le jour J', 'Départ bref et calme, retour tranquille.']],
  next: ['Utiliser la fiche gardien de Wouf pour chaque garde.', 'Suivre « Apprendre la solitude ».', 'Suivre « Partir en vacances avec son chien » si vous l’emmenez.'],
  mistakes: ['Changer d’alimentation juste avant la garde.', 'Partir sans essai préalable.', 'Faire des adieux longs et émouvants.', 'Oublier les traitements ou les consignes importantes.'],
  faq: [['La pension demande la vaccination contre la toux de chenil.', 'C’est fréquent : demandez à votre vétérinaire, idéalement 2 à 3 semaines avant.'], ['Il ne mange pas à la pension.', 'C’est fréquent le premier jour. Au-delà de 48 heures, le gardien doit vous prévenir et contacter le vétérinaire.']],
  test: 'Il passe une nuit en garde, revient détendu, et la personne a pu suivre toutes les consignes grâce à la fiche.', safety: 'Laissez une autorisation de soins signée et un moyen de paiement ou d’avance pour le vétérinaire, ainsi que les coordonnées de votre vétérinaire habituel.' }

);
