/* Wouf Éducation — leçons chat supplémentaires (Wouf Plus), 3ᵉ série : comportement, santé et changements de vie.
   Même méthode : renforcement positif, aucune punition (jamais de jet d’eau, de cri ni de contrainte).
   Contenu à faire relire par un vétérinaire ou un comportementaliste félin diplômé avant communication commerciale. */
LESSONS.push(

{ id: 'c-mord', sp: 'cat', free: false, icon: '🐾', cat: 'Comportement', title: 'Griffes et morsures pendant le jeu : rediriger l’énergie', from: 8, dur: '5 min × 3 par jour', span: '2 à 4 semaines', level: 'Essentiel',
  goal: 'Votre chat joue avec des jouets (et non avec vos mains ou vos chevilles), s’arrête quand vous stoppez le jeu et se calme après la chasse.',
  why: 'Un chat qui attaque les mains ou les chevilles ne « cherche pas à vous faire mal » : il chasse. Les chatons élevés sans frères et sœurs, ou joués avec la main, apprennent que la peau humaine est une proie. La solution : lui offrir de vraies proies (jouets), au bon rythme, et ne jamais jouer avec les mains.',
  need: ['Canne à pêche ou jouet sur ficelle', 'Petites proies souples (souris, plumes)', 'Friandises', 'Un coin calme pour la pause'],
  steps: [
    { t: 'Ne plus jouer avec les mains', min: 2, b: 'Dès aujourd’hui, aucune main ni pied n’est un jouet : ni doigts qui bougent, ni chatouilles du ventre. Si le chat attrape votre main, restez immobile et calme, puis retirez-la doucement. Il apprend que la peau humaine n’est pas intéressante.', crit: 'Plus aucun jeu avec les mains depuis 7 jours.' },
    { t: 'Des séances de chasse simulée', min: 5, b: 'Trois fois par jour, faites bouger un jouet au bout d’une canne comme une proie : fuite, pause, cachette. Laissez-le attraper, mordre, griffer. Finissez toujours par une capture, puis un repas ou une friandise : c’est le cycle naturel chasser – attraper – manger – se laver – dormir.', crit: 'Il attrape le jouet et se calme ensuite, 3 séances par jour.' },
    { t: 'Repérer les signes avant l’attaque', min: 3, b: 'Queue qui fouette, oreilles couchées, pupilles dilatées, corps ramassé : le chat est trop excité ou irrité. Arrêtez immédiatement le jeu et laissez-lui un temps de calme. Ne le grondez pas : il ne comprend pas.', crit: 'Vous interrompez le jeu avant la morsure, 8 fois sur 10.' },
    { t: 'La pause quand ça dérape', min: 2, b: 'S’il mord ou griffe, figez-vous, dites calmement « Aïe » et quittez la pièce 30 secondes, sans crier. Il apprend que la morsure met fin au jeu. Revenez ensuite avec un jouet, pas votre main.', crit: 'Les morsures diminuent de moitié en 2 semaines.' },
    { t: 'Dépenser l’énergie autrement', min: 10, b: 'Multipliez les occasions de chasser : tunnels, boîtes en carton, balles, distributeurs de croquettes, perchoirs. Un chat qui s’ennuie transforme les propriétaires en proies. Des séances plus courtes et plus fréquentes valent mieux qu’une longue.', crit: 'Il dispose de 3 jeux d’enrichissement différents chaque jour.' }
  ],
  plan: [['Jours 1 à 3', 'Plus aucun jeu avec les mains ; 3 séances de canne à pêche de 5 minutes.'], ['Jours 4 à 7', 'Repérer les signes d’excitation et arrêter avant la morsure.'], ['Semaines 2 et 3', 'Ajouter tunnels, boîtes, distributeurs de croquettes.'], ['Semaine 4', 'Séance du soir plus longue pour apaiser la nuit.']],
  next: ['Suivre la leçon « Jeu et enrichissement : la chasse simulée ».', 'Envisager un compagnon félin adapté si le chat est jeune et seul (avis de votre vétérinaire).', 'Consulter un comportementaliste si les attaques sont intenses ou soudaines.'],
  mistakes: ['Punir, crier, taper ou vaporiser de l’eau : il ne comprend pas et devient méfiant.', 'Jouer avec les mains « pour rire » : vous encouragez la morsure.', 'Ne pas finir le jeu par une capture : la frustration augmente l’agressivité.', 'Croire que « c’est juste un chaton » : sans correction douce, cela s’ancre.'],
  faq: [['Il attaque mes chevilles quand je marche.', 'Emportez un jouet dans la poche, lancez-le avant qu’il n’attaque et jouez avec lui : c’est la redirection.'], ['Il mord soudain alors qu’il ne le faisait pas avant.', 'Une douleur ou une maladie peut changer le comportement : consultez votre vétérinaire.']],
  test: 'En 2 semaines, il joue avec les jouets, s’arrête quand vous stoppez et n’attaque plus vos mains ni vos chevilles.', safety: 'Une morsure ou une griffure de chat peut s’infecter : nettoyez la plaie à l’eau et au savon et consultez rapidement un médecin si elle est profonde, rouge ou douloureuse. Une agression soudaine ou intense doit faire consulter le vétérinaire.' },

{ id: 'c-pipi', sp: 'cat', free: false, icon: '🚽', cat: 'Santé et propreté', title: 'Pipi hors de la litière : comprendre et résoudre', from: 8, dur: '5 min × 2 par jour', span: '2 à 6 semaines', level: 'Essentiel',
  goal: 'Votre chat retrouve l’usage de sa litière, avec une cause identifiée (médicale, environnementale ou émotionnelle) et des solutions adaptées.',
  why: 'Un chat qui urine ou défèque hors de sa litière ne le fait jamais « par vengeance ». C’est le signe d’un problème : cystite ou maladie urinaire (à écarter en premier), litière qui ne lui convient pas, stress, marquage, douleur. La punition aggrave toujours la situation.',
  need: ['Une ou plusieurs litières supplémentaires', 'Nettoyant enzymatique (pas d’eau de Javel ni d’ammoniaque)', 'Litière neutre non parfumée', 'Un rendez-vous chez le vétérinaire'],
  steps: [
    { t: 'Consulter d’abord le vétérinaire', min: 5, b: 'Toute malpropreté soudaine impose une consultation : cystite, calculs urinaires, infection, diabète, arthrose douloureuse. Notez la fréquence, la quantité, la présence de sang, les efforts. Emportez une photo de la litière ou un échantillon si demandé.', crit: 'Une visite vétérinaire a écarté ou traité une cause médicale.' },
    { t: 'Revoir la litière', min: 10, b: 'Règle d’or : une litière par chat, plus une. Grand bac ouvert, au moins 1,5 fois la longueur du chat, litière fine non parfumée, 5 à 7 cm de hauteur, ramassée chaque jour, changée entièrement régulièrement, en des endroits calmes et accessibles. Évitez de changer de marque brutalement.', crit: 'Le nombre, la taille et l’emplacement des litières respectent la règle « n + 1 ».' },
    { t: 'Nettoyer sans laisser d’odeur', min: 10, b: 'Nettoyez toutes les zones souillées avec un nettoyant enzymatique : l’odeur restante attire le chat. Évitez les produits ammoniaqués ou javellisés qui ressemblent à l’odeur d’urine. Rendez les endroits désagréables (papier aluminium, mobilier) ou installez un bol de nourriture, jamais une punition.', crit: 'Aucune odeur résiduelle aux endroits souillés.' },
    { t: 'Réduire le stress et enrichir', min: 10, b: 'Un déménagement, un nouvel animal, un bébé, des chats de l’extérieur qui rôdent peuvent provoquer du stress. Multipliez les cachettes, les perchoirs, les diffuseurs de phéromones félines, et gardez une routine stable. Jouez chaque jour, offrez de la verticalité.', crit: 'Le chat dispose de cachettes, perchoirs et d’une routine stable.' },
    { t: 'Récompenser les bons choix', min: 2, b: 'Quand il utilise la litière, ne le dérangez pas ; félicitez-le doucement une fois sorti. Ne le suivez pas, ne le grondez jamais. Suivez un carnet de bord : chaque semaine, notez les accidents et comparez.', crit: 'Le nombre d’accidents diminue de semaine en semaine.' }
  ],
  plan: [['Jours 1 à 2', 'Rendez-vous chez le vétérinaire, notez les symptômes.'], ['Jours 3 à 7', 'Ajouter une litière, changer de litière progressivement, nettoyer avec un enzymatique.'], ['Semaines 2 et 3', 'Enrichir l’environnement, calmer les tensions entre animaux.'], ['Semaines 4 à 6', 'Suivi des accidents ; consulter un comportementaliste si le problème persiste.']],
  next: ['Suivre la leçon « Litière : les bons réglages ».', 'Lire « Aménager sa maison pour un chat épanoui ».', 'Consulter un comportementaliste félin si le problème persiste après le traitement médical.'],
  mistakes: ['Punir, crier, mettre le nez dans l’urine : le chat n’y comprend rien et il a peur.', 'Croire que c’est de la vengeance : c’est un signal de mal-être.', 'Utiliser un produit ammoniaqué pour nettoyer : cela attire encore le chat.', 'Attendre plusieurs jours : une infection urinaire peut être grave.'],
  faq: [['Il urine debout contre un mur.', 'C’est du marquage : stress, chats du voisinage, non-stérilisation. Consultez pour identifier la cause.'], ['Il urine seulement sur mes affaires.', 'Il cherche un endroit imprégné de votre odeur pour se rassurer : signe d’anxiété, à traiter.']],
  test: 'Pendant 4 semaines consécutives, plus aucun accident hors de la litière.', safety: 'URGENCE : un chat (surtout un mâle) qui fait de gros efforts pour uriner sans rien produire, qui crie, se cache ou vomit peut avoir une obstruction urinaire mortelle en quelques heures. Consultez immédiatement un vétérinaire.' },

{ id: 'c-demenagement', sp: 'cat', free: false, icon: '📦', cat: 'Changements de vie', title: 'Déménagement et changements : préserver la sérénité', from: 8, dur: 'Préparation sur 2 semaines', span: '2 à 4 semaines', level: 'Utile',
  goal: 'Votre chat s’adapte à un nouveau logement, une arrivée ou un changement de rythme avec un minimum de stress, mange, joue et utilise sa litière normalement.',
  why: 'Le chat est un animal territorial : son sentiment de sécurité vient de ses repères. Un déménagement, des travaux ou un bébé bouleversent son monde. Avec de la préparation, des repères olfactifs et un accès progressif au territoire, l’adaptation se passe bien.',
  need: ['Caisse de transport habituée', 'Diffuseur de phéromones félines (facultatif)', 'Litière, gamelles, couverture familières', 'Une pièce « refuge » dans le nouveau logement'],
  steps: [
    { t: 'Habituer à la caisse avant', min: 5, b: 'Laissez la caisse ouverte plusieurs jours avant, avec une couverture et des friandises. Le voyage sera moins stressant si la caisse est un lieu connu. Vérifiez que la puce est à jour (coordonnées).', crit: 'Il entre dans la caisse de lui-même, 8 fois sur 10.' },
    { t: 'Préserver les repères olfactifs', min: 5, b: 'Ne lavez pas ses couvertures, arbre à chat et jouets juste avant le départ : leur odeur le rassure. Frottez un chiffon sur ses joues et déposez-le dans le nouveau logement. Utilisez un diffuseur de phéromones félines si vous le souhaitez.', crit: 'Les objets familiers sont emportés non lavés.' },
    { t: 'Aménager une pièce refuge', min: 15, b: 'Dans le nouveau logement, préparez une pièce calme avec litière, eau, nourriture, couchage, cachette et jouets. Le chat y reste 2 à 3 jours pour s’habituer aux odeurs, avant de découvrir le reste. Ne le laissez jamais sortir le premier jour.', crit: 'Il mange, boit et utilise la litière dans la pièce refuge.' },
    { t: 'Ouvrir le territoire progressivement', min: 10, b: 'Quand il est détendu, ouvrez une pièce de plus par jour, portes ouvertes, sans le forcer. Récompensez sa curiosité. Fermez fenêtres, balcons et bouches d’aération ; vérifiez les recoins dangereux.', crit: 'Il explore une nouvelle pièce spontanément chaque jour.' },
    { t: 'La sortie extérieure (si chat d’extérieur)', min: 5, b: 'Attendez au moins 3 à 4 semaines avant toute sortie, sinon il risque de fuguer pour retrouver son ancien territoire. Sortez d’abord en harnais, sous surveillance. Vérifiez la puce, le collier et les coordonnées.', crit: 'Il est identifié et reste calme lors de la première sortie accompagnée.' }
  ],
  plan: [['2 semaines avant', 'Habituer à la caisse, préparer une trousse : croquettes, litière, gamelles.'], ['Le jour J', 'Caisse, voyage calme, pièce refuge prête à l’arrivée.'], ['Jours 2 à 7', 'Ouverture progressive du logement, jeux et repas réguliers.'], ['Semaines 2 à 4', 'Retour à la routine ; première sortie accompagnée si chat d’extérieur.']],
  next: ['Faire vérifier l’identification à jour après le changement d’adresse.', 'Lire « Aménager sa maison pour un chat épanoui ».', 'Consulter votre vétérinaire si le chat mange peu pendant plus de 24 heures.'],
  mistakes: ['Le laisser explorer tout le logement dès le premier jour : trop de stimulations.', 'Laver toutes ses affaires avant : il perd ses repères.', 'Le laisser sortir dès les premiers jours : risque de fugue.', 'Oublier de mettre à jour la puce avec la nouvelle adresse.'],
  faq: [['Il se cache depuis 2 jours.', 'C’est normal : laissez-le tranquille, restez calme, offrez nourriture et eau à proximité. Consultez si ça dépasse 48 h sans manger.'], ['Il miaule la nuit.', 'Signe de stress : offrez jeux le soir et repères familiers ; voir la leçon « Miaulements et réveils la nuit ».']],
  test: 'Après 7 jours, il mange, joue, utilise sa litière et explore le logement sans se cacher.', safety: 'Un chat qui ne mange plus depuis plus de 24 à 48 heures peut développer une maladie du foie grave : consultez sans attendre. Vérifiez que les fenêtres sont sécurisées (filets) : le syndrome du chat parachutiste est fréquent après un déménagement.' },

{ id: 'c-solitude', sp: 'cat', free: false, icon: '🏡', cat: 'Changements de vie', title: 'Laisser son chat seul : week-ends, journées et vacances', from: 12, dur: 'Préparation progressive', span: '2 à 3 semaines', level: 'Utile',
  goal: 'Votre chat supporte vos absences (journée, week-end, vacances) sans stress, avec ses besoins vitaux assurés, en sécurité et occupé.',
  why: 'Le chat est plus autonome que le chien, mais il n’est pas « indépendant » : il a besoin d’eau, de nourriture fraîche, d’une litière propre et de contacts. Une préparation soignée et une visite quotidienne d’une personne de confiance évitent le stress et les accidents.',
  need: ['Plusieurs points d’eau', 'Distributeur de croquettes (facultatif)', 'Personne de confiance ou pet-sitter', 'Fiche gardien de Wouf'],
  steps: [
    { t: 'Journées de travail', min: 10, b: 'Prévoyez de l’eau fraîche à plusieurs endroits, une litière propre, un perchoir près de la fenêtre et des jouets. Un jouet fourré ou un distributeur de croquettes occupe l’esprit. Jouez avant de partir et à votre retour.', crit: 'Il s’occupe calmement pendant vos absences de la journée.' },
    { t: 'Week-end (1 à 2 nuits)', min: 10, b: 'Doublez les litières, multipliez les gamelles d’eau, et laissez de la nourriture en quantité mesurée (distributeurs programmables). Une visite quotidienne est fortement conseillée, même pour un week-end, pour vérifier que tout va bien.', crit: 'Vous avez prévu une visite quotidienne, même pour un week-end.' },
    { t: 'Vacances : pension ou visite à domicile', min: 20, b: 'La plupart des chats supportent mieux de rester chez eux, avec une visite ou un séjour du pet-sitter chaque jour. Utilisez la fiche gardien de Wouf pour transmettre habitudes, repas, traitements, contacts d’urgence. Testez la personne avant le grand départ.', crit: 'La fiche gardien est remplie et testée avec la personne de confiance.' },
    { t: 'Sécuriser le logement', min: 10, b: 'Fermez ou sécurisez fenêtres et balcons, cachez câbles et objets dangereux, retirez les plantes toxiques (lys, etc.). Laissez plusieurs cachettes et un accès aux pièces habituelles.', crit: 'Le logement est sécurisé : fenêtres, câbles, plantes toxiques.' },
    { t: 'Le départ et le retour', min: 5, b: 'Évitez les longs adieux ou les retrouvailles exubérantes : restez calme. Gardez vos habitudes (heure des repas, jeu). Observez au retour l’appétit, la litière, l’état de la fourrure et le comportement.', crit: 'Il retrouve rapidement sa routine après votre retour.' }
  ],
  plan: [['2 semaines avant', 'Tester une absence courte, présenter la personne de confiance.'], ['1 semaine avant', 'Remplir la fiche gardien, prévoir litières et gamelles supplémentaires.'], ['Le jour du départ', 'Sécuriser le logement, routine calme, contacts d’urgence à disposition.'], ['Au retour', 'Vérifier appétit, litière et comportement ; reprendre la routine.']],
  next: ['Utiliser la fiche gardien de Wouf pour tous vos départs.', 'Lire « Aménager sa maison pour un chat épanoui ».', 'Consulter le vétérinaire si le chat mange moins ou change de comportement après votre retour.'],
  mistakes: ['Le laisser seul plus de 24 à 48 heures sans visite.', 'Laisser une seule gamelle d’eau qui peut se renverser.', 'Compter sur un distributeur de croquettes sans vérifier.', 'Changer de nourriture juste avant votre départ.'],
  faq: [['Puis-je partir 3 jours en le laissant seul ?', 'Ce n’est pas recommandé sans visite : un problème de santé ou d’eau peut vite devenir grave. Demandez à quelqu’un de passer chaque jour.'], ['Il fait des bêtises quand je pars.', 'C’est souvent de l’ennui ou du stress : enrichissez son environnement et jouez avant de partir.']],
  test: 'Pendant une absence de 2 jours avec visite quotidienne, il mange, boit, utilise la litière et reste détendu à votre retour.', safety: 'Un chat dépendant de traitements (diabète, insuffisance rénale) ne doit pas être laissé sans personne compétente. Laissez toujours les coordonnées de votre vétérinaire et une autorisation de soins d’urgence.' },

{ id: 'c-dents', sp: 'cat', free: false, icon: '🦷', cat: 'Soins', title: 'Dents du chat : brossage et repérage des problèmes', from: 10, dur: '2 min × 1 par jour', span: '3 à 4 semaines', level: 'Utile',
  goal: 'Votre chat accepte qu’on touche sa bouche et, si possible, le brossage régulier, et vous savez repérer les signes de douleur dentaire.',
  why: 'Les maladies dentaires sont très fréquentes chez le chat adulte (gingivite, résorptions dentaires, tartre) et souvent silencieuses : un chat cache sa douleur. Une bonne habituation permet de vérifier régulièrement la bouche, de brosser si possible et de consulter à temps.',
  need: ['Doigtier ou petite brosse pour chat', 'Dentifrice pour chat (jamais humain)', 'Friandises très alléchantes', 'Un moment calme, après le jeu'],
  steps: [
    { t: 'Le contact avec la tête et la bouche', min: 2, b: 'Caressez les joues et le menton, puis soulevez doucement la lèvre 1 seconde. « Oui ! » (ou une caresse) et friandise. Augmentez très lentement. Arrêtez dès qu’il se raidit.', crit: 'Il tolère qu’on soulève sa lèvre 2 secondes.' },
    { t: 'Le goût du dentifrice', min: 2, b: 'Proposez du dentifrice pour chat sur votre doigt : il doit s’agir d’un moment agréable. Choisissez un goût qu’il aime (volaille, poisson). Il se lèche, puis vient de lui-même.', crit: 'Il lèche le dentifrice avec plaisir.' },
    { t: 'Frotter les dents et les gencives', min: 3, b: 'Avec le doigt enduit de dentifrice, frottez une dent, puis quelques-unes, en petits cercles vers la gencive. Augmentez sur plusieurs jours avant d’introduire le doigtier puis la brosse.', crit: 'Il accepte 10 secondes de frottement.' },
    { t: 'Brossage régulier', min: 2, b: 'Brossez les côtés externes des dents, 30 secondes par côté, au même moment chaque jour, en finissant par un jeu ou une friandise. Même 3 fois par semaine est bénéfique.', crit: 'Il accepte 1 minute de brossage, 3 fois par semaine.' },
    { t: 'Reconnaître les signes d’alerte', min: 2, b: 'Mauvaise haleine forte, gencives rouges ou qui saignent, tartre épais, salivation, aliment mâché d’un seul côté ou qui tombe, perte d’appétit, patte sur la bouche : consultez rapidement. Un contrôle dentaire annuel est conseillé.', crit: 'Vous connaissez les signes d’alerte et un contrôle est programmé.' }
  ],
  plan: [['Jours 1 à 3', 'Caresses sur les joues et le menton, lèvre soulevée 1 seconde.'], ['Jours 4 à 7', 'Goût du dentifrice sur le doigt, puis frottement d’une dent.'], ['Semaines 2 et 3', 'Brossage d’un côté, 30 secondes, tous les jours.'], ['Semaine 4 et suivantes', 'Brossage complet, contrôle vétérinaire annuel.']],
  next: ['Demander un contrôle dentaire à chaque visite annuelle.', 'Utiliser des aliments ou friandises d’hygiène dentaire reconnus (avis du vétérinaire).', 'Lire « Bien nourrir son chat : eau, ration et poids ».'],
  mistakes: ['Utiliser du dentifrice humain : le fluor et le xylitol sont toxiques pour les chats.', 'Forcer le chat : il associera la bouche au conflit.', 'Compter uniquement sur les croquettes « dentaires » : elles ne remplacent pas un vrai brossage.', 'Attendre que l’appétit diminue : la douleur est déjà installée.'],
  faq: [['Il se débat dès que je touche sa bouche.', 'Repartez très lentement : quelques secondes de caresses sur les joues, sans forcer, avec des friandises.'], ['Mon chat ne veut pas de brosse.', 'Commencez par le doigt ou une compresse humide, puis la brosse ; quelques passages valent mieux que rien.']],
  test: 'Il accepte 1 minute de brossage, 3 fois par semaine, ou un contrôle de la bouche sans stress.', safety: 'Ne jamais utiliser de dentifrice humain (fluor, xylitol toxiques). Un chat qui mange moins, bave ou se cache peut souffrir d’une dent : consultez rapidement, un chat qui ne mange plus depuis 24 à 48 heures est en danger.' }

);

PROGRAMS.push(
  { id: 'chat-detente4', sp: 'cat', icon: '🧘', title: 'Programme chat épanoui : 4 semaines', sub: 'Jeu, propreté et sérénité au quotidien', weeks: [
    ['Semaine 1', 'Chasser sans mordre', ['c-mord', 'c-jeu']],
    ['Semaine 2', 'Une litière parfaite', ['c-litiere', 'c-pipi']],
    ['Semaine 3', 'Absences et changements', ['c-solitude', 'c-demenagement']],
    ['Semaine 4', 'Santé de la bouche et des soins', ['c-dents', 'c-soins']]
  ] }
);
