/* Wouf Éducation — leçons supplémentaires (Wouf Plus), 5ᵉ série : chien (vétérinaire, eau, premières nuits, jeux d’intelligence,
   arrivée d’un bébé, chien craintif, deux chiens) et chat (bébé, eau, poids, sorties). Renforcement positif uniquement.
   Contenu à faire relire par un vétérinaire ou un comportementaliste diplômé avant communication commerciale. */
LESSONS.push(

{ id: 'veto', free: false, icon: '🩺', cat: 'Soins', title: 'Chez le vétérinaire sans stress : les visites de plaisir', from: 8, dur: '5 à 10 min × 2 par semaine', span: '3 à 6 semaines', level: 'Essentiel',
  goal: 'Votre chien entre chez le vétérinaire détendu, monte sur la table ou la balance, se laisse examiner et repart heureux.',
  why: 'Un chien qui a peur du cabinet devient difficile à soigner et à examiner, ce qui nuit à sa santé. La peur s’installe vite (odeurs, sols glissants, contention). En associant le lieu à des friandises et des visites « pour rien », on change durablement son ressenti.',
  need: ['Friandises très appréciées', 'Un vétérinaire ou une clinique qui accepte les visites de plaisir', 'Une muselière conditionnée (utile, jamais une punition)', 'Son tapis ou sa couverture'],
  steps: [
    { t: 'Des visites de plaisir', min: 10, b: 'Passez à la clinique sans rendez-vous, juste pour une pesée et une friandise donnée par l’équipe. Repartez tout de suite après. Répétez 3 à 4 fois avant tout soin. Le chien apprend que le lieu n’annonce pas toujours quelque chose de désagréable.', crit: 'Il entre volontairement et prend des friandises à la réception.' },
    { t: 'Répéter les gestes à la maison', min: 5, b: 'Entraînez l’examen : regarder les oreilles, soulever la lèvre, toucher les pattes, palper le ventre, prendre la température de la queue, en récompensant chaque geste. Faites intervenir plusieurs personnes. Voir la leçon « Manipulations et soins coopératifs ».', crit: 'Il accepte 6 gestes d’examen, 8 fois sur 10.' },
    { t: 'La table, la balance et les sols glissants', min: 5, b: 'Habituez-le à monter sur une surface surélevée ou une balance (vous pouvez utiliser un tapis antidérapant chez vous). Récompensez la position immobile. Sur les sols glissants de la clinique, placez son tapis pour lui donner de l’adhérence.', crit: 'Il monte sur la balance et reste immobile 5 secondes.' },
    { t: 'La muselière comme alliée', min: 5, b: 'Conditionnez la muselière avec des friandises : le chien y glisse le nez pour être récompensé (voir la leçon dédiée). Une muselière bien acceptée protège tout le monde et permet des soins plus sereins.', crit: 'Il met le nez dans la muselière de lui-même.' },
    { t: 'Le jour du rendez-vous', min: 10, b: 'Prévenez l’équipe que votre chien est anxieux. Emportez ses friandises préférées, arrivez en avance ou attendez dehors. Gardez une voix calme, récompensez chaque geste sans le forcer. Demandez si la clinique applique des pratiques « sans peur » (fear free).', crit: 'Il ressort détendu et mange encore ses friandises.' }
  ],
  plan: [['Semaine 1', 'Une visite de plaisir (pesée + friandise) et manipulations à la maison.'], ['Semaine 2', 'Deuxième visite, montée sur la balance.'], ['Semaine 3', 'Muselière conditionnée à la maison.'], ['Semaines 4 à 6', 'Visite complète avec examen, friandises et récompense.']],
  next: ['Répéter une visite de plaisir avant chaque rappel annuel.', 'Apprendre à prendre les médicaments avec des friandises.', 'Travailler l’acceptation de la caisse de transport.'],
  mistakes: ['Ne venir que pour les soins : le lieu devient synonyme de douleur.', 'Forcer un chien qui refuse d’entrer : il retient l’expérience.', 'Le rassurer en le caressant beaucoup quand il tremble : récompensez plutôt le calme.', 'Arriver à jeun sans friandises : la nourriture est votre meilleur outil.'],
  faq: [['Il refuse de manger chez le vétérinaire.', 'Signe de stress important : réduisez la difficulté (rester dehors, distance plus grande) et essayez des friandises plus fortes.'], ['Il tremble dans la salle d’attente.', 'Attendez dehors ou en voiture et faites entrer seulement au moment de l’examen.']],
  test: 'Il entre, se laisse peser et examiner chez le vétérinaire, en prenant des friandises, 8 fois sur 10.', safety: 'Un chien très craintif ou agressif chez le vétérinaire doit être signalé à l’équipe avant la consultation : muselière conditionnée, médicaments anxiolytiques prescrits ou consultation à domicile peuvent aider.' },

{ id: 'eau', free: false, icon: '🏊', cat: 'Voyage', title: 'Aimer l’eau : baignade et sécurité aquatique', from: 20, dur: '10 min × 2 par semaine', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien entre dans l’eau volontairement, à son rythme, porte un gilet de flottaison si besoin et sort en sécurité.',
  why: 'Tous les chiens ne savent pas nager et tous n’aiment pas l’eau. Une introduction progressive évite la panique et les noyades. Les plages, rivières et lacs présentent aussi des risques : courants, algues bleues toxiques, eau salée avalée, hypothermie, fatigue.',
  need: ['Gilet de flottaison adapté au chien', 'Longe de 5 mètres', 'Serviette et eau douce potable', 'Friandises et jouet flottant'],
  steps: [
    { t: 'Se familiariser avec l’eau peu profonde', min: 10, b: 'Faites marcher votre chien au bord de l’eau, pieds mouillés, sur une plage à pente douce ou un ruisseau. Récompensez chaque pas dans l’eau. Ne le poussez jamais. Laissez-le renifler et explorer à son rythme.', crit: 'Il entre volontairement dans l’eau jusqu’aux coudes, 8 fois sur 10.' },
    { t: 'Habituer au gilet de flottaison', min: 5, b: 'À la maison d’abord, faites-lui porter le gilet quelques minutes en le récompensant. Vérifiez qu’il le supporte et qu’il ne gêne pas sa marche. Choisissez-en un bien ajusté, avec poignée sur le dos pour le sortir de l’eau.', crit: 'Il porte le gilet sans se gratter ni se figer.' },
    { t: 'Nager avec vous', min: 10, b: 'Restez à hauteur du chien, sur longe, dans un endroit sans courant. Restez dans l’eau avec lui si vous pouvez. Jouez avec un jouet flottant lancé à quelques mètres, puis appelez-le. Interrompez la séance dès qu’il montre de la fatigue.', crit: 'Il nage 2 minutes en respirant calmement et revient.' },
    { t: 'Repérer les eaux dangereuses', min: 5, b: 'Évitez les eaux stagnantes, colorées ou avec écume verte (algues bleues toxiques), les courants, les barrages et les canaux. En mer, ne le laissez pas boire l’eau salée. Respectez les interdictions locales de baignade.', crit: 'Vous savez reconnaître 3 signes d’eau dangereuse.' },
    { t: 'La sortie de l’eau et le rinçage', min: 5, b: 'Apprenez-lui à sortir à côté de vous, par un endroit facile (rampe, plage). Après la baignade, rincez-le à l’eau douce (sel, algues, produits) et séchez bien les oreilles et les plis pour éviter les infections.', crit: 'Il sort seul de l’eau et accepte le rinçage.' }
  ],
  plan: [['Semaine 1', 'Marche au bord de l’eau, pieds mouillés, récompenses.'], ['Semaine 2', 'Gilet à la maison puis dans l’eau peu profonde.'], ['Semaines 3 et 4', 'Petites nages de 2 minutes sur longe.'], ['Semaines 5 et 6', 'Sorties en eau surveillée, rinçage et séchage systématiques.']],
  next: ['Apprendre le rappel depuis l’eau.', 'Pratiquer une activité comme le paddle avec gilet et supervision.', 'Consulter votre vétérinaire pour la protection contre la leptospirose.'],
  mistakes: ['Jeter un chien dans l’eau « pour qu’il apprenne » : il peut paniquer et se noyer.', 'Le laisser sans surveillance près de l’eau, même un instant.', 'Le laisser boire l’eau de mer ou de mare : risques de déshydratation et d’intoxication.', 'Oublier de sécher les oreilles.'],
  faq: [['Il a peur de l’eau.', 'Ne forcez pas : récompensez chaque pas vers l’eau, sur plusieurs semaines. Certains chiens préfèrent rester au bord.'], ['Tous les chiens savent-ils nager ?', 'Non : les chiens à museau court ou aux pattes très courtes (bouledogues, carlins, bassets) coulent plus facilement. Un gilet est indispensable.']],
  test: 'Il entre dans l’eau volontairement, nage 2 minutes avec son gilet, ressort seul et accepte le rinçage.', safety: 'Les algues bleues (cyanobactéries) peuvent être mortelles en quelques heures : ne laissez pas votre chien boire ni se baigner dans une eau verte, écumeuse ou stagnante. En cas de vomissements ou de faiblesse après une baignade, consultez en urgence.' },

{ id: 'nuits', free: false, icon: '🌙', cat: 'Chiot', title: 'Les premières nuits du chiot', from: 8, dur: 'Chaque nuit', span: '1 à 3 semaines', level: 'Essentiel',
  goal: 'Votre chiot dort dans son coin, se réveille de moins en moins souvent et apprend à faire ses nuits, sans pleurs prolongés.',
  why: 'Les premières nuits sont difficiles : le chiot vient de quitter sa mère et sa fratrie, sa vessie est petite, et tout est nouveau. Une routine douce, un couchage rassurant et des sorties calmes lui apprennent que la nuit est faite pour dormir, et non pour jouer.',
  need: ['Une caisse ou un panier dans la chambre', 'Une couverture et un jouet doux', 'Une lampe douce', 'Friandises'],
  steps: [
    { t: 'Un coin de nuit rassurant', min: 5, b: 'Installez la caisse ou le panier dans votre chambre les premières nuits, près de votre lit. Votre présence rassure. Ajoutez une couverture qui porte l’odeur de sa mère ou du refuge si possible, et un jouet doux. Une lumière tamisée peut aider.', crit: 'Le chiot s’endort dans son coin en moins de 20 minutes.' },
    { t: 'Un rituel du soir', min: 20, b: 'Dernier repas 2 à 3 heures avant le coucher, dernière sortie juste avant, calme et courte, puis rituel identique : lumière basse, caresses douces, « Bonne nuit ». Évitez les jeux excitants après 20 h.', crit: 'Le rituel du soir est identique chaque jour.' },
    { t: 'Les sorties de nuit', min: 5, b: 'Un chiot de 2 à 4 mois doit sortir 1 à 2 fois la nuit. Quand il pleure et s’agite, sortez-le sans un mot, lumière faible, en laisse, sur le lieu habituel. Récompensez calmement, puis recouchez-le sans jeu. Réduisez d’une sortie toutes les 1 à 2 semaines.', crit: 'Il fait ses besoins dehors la nuit puis se rendort sans jouer.' },
    { t: 'Les pleurs : que faire ?', min: 5, b: 'Vérifiez d’abord ses besoins (sortie, faim, chaud/froid). S’il s’agit d’un appel pour de la compagnie, restez calme, parlez doucement sans le sortir de son coin, et récompensez le moindre silence. Ne le punissez jamais : il apprendrait que la nuit fait peur.', crit: 'Les pleurs diminuent de moitié en 5 nuits.' },
    { t: 'Progressivement l’éloigner', min: 10, b: 'Quand le chiot dort bien, éloignez la caisse de quelques mètres par semaine jusqu’à l’emplacement souhaité. Gardez le même rituel. La nuit suffisante à cet âge : 6 à 8 heures d’affilée vers 4 mois pour beaucoup de chiots.', crit: 'Il dort 6 heures d’affilée dans son coin définitif.' }
  ],
  plan: [['Nuits 1 à 3', 'Caisse dans la chambre, sorties de nuit calmes.'], ['Nuits 4 à 10', 'Réduire à une sortie, rituel identique.'], ['Semaines 2 et 3', 'Éloigner la caisse, dernières sorties nocturnes.'], ['Mois 4', 'Nuits complètes dans le coin définitif.']],
  next: ['Suivre la leçon « La caisse : une chambre à soi ».', 'Suivre « Propreté du chiot ».', 'Préparer « Apprendre la solitude ».'],
  mistakes: ['Le prendre dans le lit à chaque pleur puis vouloir l’en sortir : la règle change tout le temps.', 'Jouer pendant les sorties de nuit : il apprend que la nuit est un moment de jeu.', 'Punir ou crier : la peur augmente les pleurs.', 'Donner à boire et à manger tard le soir.'],
  faq: [['Il pleure très fort dès qu’on éteint.', 'C’est fréquent la première semaine. Restez près de lui, récompensez le silence et n’ouvrez pas la caisse tant qu’il pleure fort.'], ['Il se réveille à 5 h du matin.', 'Décalez progressivement le coucher, sortez-le calmement, sans jeu, et récompensez le retour au calme.']],
  test: 'Il dort au moins 6 heures d’affilée dans son coin, sans pleurer ni se lever.', safety: 'Un chiot qui vomit, a la diarrhée ou est très abattu la nuit doit voir un vétérinaire rapidement. Ne laissez jamais un chiot dans une caisse trop chaude ou sans eau accessible dans la journée.' },

{ id: 'cerveau', free: false, icon: '🧠', cat: 'Jeu', title: 'Jeux d’intelligence : occuper l’esprit à la maison', from: 12, dur: '10 min × 1 à 2 par jour', span: 'Toute la vie', level: 'Tous niveaux',
  goal: 'Votre chien joue chaque jour à des jeux de recherche et de réflexion, se fatigue mentalement et devient plus calme à la maison.',
  why: 'Dix minutes de réflexion fatiguent autant qu’une longue balade. Les jeux d’intelligence réduisent l’ennui, les destructions et l’excitation, aident les chiens blessés, âgés ou en convalescence, et renforcent votre complicité. Ils ne remplacent toutefois pas l’exercice physique.',
  need: ['Tapis de fouille (snuffle mat)', 'Jouets distributeurs de nourriture', 'Gobelets ou boîtes en carton', 'Friandises ou croquettes du repas'],
  steps: [
    { t: 'Le repas dans un jouet', min: 10, b: 'Remplacez la gamelle par un jouet distributeur, un Kong ou un tapis de fouille. Commencez par des versions faciles (grands trous, croquettes visibles). Augmentez la difficulté progressivement.', crit: 'Il vide un jouet distributeur facile en moins de 5 minutes.' },
    { t: 'Le jeu du gobelet', min: 5, b: 'Cachez une friandise sous l’un de trois gobelets, laissez-le chercher avec son nez. Récompensez chaque bonne réponse. Puis mélangez les gobelets pour ajouter de la difficulté.', crit: 'Il trouve la friandise sous le bon gobelet, 8 fois sur 10.' },
    { t: 'La chasse au trésor', min: 10, b: 'Cachez des friandises ou des jouets dans la pièce, puis dites « Cherche ! ». Commencez à vue, puis cachés. Terminez chaque séance par une réussite facile.', crit: 'Il retrouve 5 friandises cachées dans la pièce.' },
    { t: 'Apprendre un nouveau petit tour', min: 5, b: 'Utilisez le marqueur « Oui ! » pour enseigner un mouvement (toucher une cible, contourner un objet, fermer une porte). Apprendre est un excellent exercice mental. Séances de 3 à 5 minutes.', crit: 'Il apprend un nouveau geste en 3 séances.' },
    { t: 'Varier et surveiller la frustration', min: 5, b: 'Changez les jeux chaque jour, adaptez la difficulté. Si votre chien abandonne, s’agite, aboie ou détruit le jouet, c’est trop difficile : simplifiez. Surveillez les jouets pour éviter l’ingestion de morceaux.', crit: 'Il termine ses jeux sans frustration excessive.' }
  ],
  plan: [['Jours 1 à 3', 'Repas dans un jouet facile, 1 à 2 fois par jour.'], ['Jours 4 à 7', 'Jeu du gobelet et chasse au trésor.'], ['Semaine 2', 'Difficulté supérieure, nouveau petit tour.'], ['Semaines 3 et suivantes', 'Rotation des jeux, deux séances de 10 minutes par jour.']],
  next: ['Suivre « Cherche ! Les jeux d’odorat ».', 'Fabriquer ses propres jeux avec du carton ou des serviettes.', 'Congeler un Kong rempli pour prolonger l’activité.'],
  mistakes: ['Choisir un jeu trop difficile : il abandonne ou détruit le jouet.', 'Laisser un jouet dangereux sans surveillance.', 'Remplacer toute activité physique par des jeux mentaux.', 'Donner tous les jeux en même temps : le chien s’en lasse.'],
  faq: [['Il mange le jouet.', 'Choisissez un jouet plus solide et de taille adaptée, et surveillez.'], ['Il s’en désintéresse.', 'Utilisez des friandises plus alléchantes, faites varier les jeux et gardez des séances courtes.']],
  test: 'Il joue 10 minutes à un jeu de recherche et termine calme et satisfait.', safety: 'Surveillez toujours les jouets distributeurs et les jeux de fouille : un morceau avalé peut obstruer l’intestin. Si votre chien est au régime, prélevez les friandises sur sa ration quotidienne.' },

{ id: 'bebe', free: false, icon: '👶', cat: 'Cohabitation', title: 'Chien et arrivée d’un bébé', from: 26, dur: 'Préparation sur 3 à 6 mois', span: '3 à 6 mois', level: 'Essentiel',
  goal: 'Votre chien accueille le bébé calmement, s’habitue à ses sons et odeurs, reste sur sa place et n’est jamais laissé seul avec lui.',
  why: 'L’arrivée d’un bébé bouleverse le quotidien du chien : moins d’attention, nouveaux sons, odeurs, règles. Sans préparation, il peut développer du stress ou des comportements indésirables. Une préparation progressive et une surveillance permanente protègent bébé et chien.',
  need: ['Une barrière ou porte de sécurité', 'Le tapis du chien', 'Enregistrements de sons de bébé', 'Friandises'],
  steps: [
    { t: 'Adapter les routines avant la naissance', min: 10, b: 'Changez dès maintenant ce qui va changer : horaires, promenades, lieux de repos, pièce interdite. Réduisez progressivement l’attention exclusive. Habituez-le à la barrière et à son coin de repos.', crit: 'Il accepte sans stress les nouvelles routines et la barrière.' },
    { t: 'Habituer aux sons et aux odeurs', min: 5, b: 'Faites écouter des pleurs de bébé à faible volume en donnant des friandises, puis augmentez peu à peu. Faites-lui sentir les objets de bébé (lotion, lange propre). Sons et odeurs deviennent connus et associés à quelque chose d’agréable.', crit: 'Il reste calme en entendant des pleurs de bébé enregistrés.' },
    { t: 'La place et le calme', min: 5, b: 'Renforcez « Place » et « Reste ». Le chien doit pouvoir se retirer à tout moment sur son tapis sans être dérangé. Préparez aussi « Laisse-le » pour les jouets et les objets de bébé.', crit: 'Il reste sur sa place 5 minutes pendant que vous vous occupez d’un poupon.' },
    { t: 'La rencontre', min: 10, b: 'À l’arrivée, laissez un proche s’occuper du chien pendant que vous entrez. Puis présentez-le calmement, chien en laisse ou derrière la barrière, en récompensant le calme. Laissez-le sentir de loin, sans forcer, sans contact direct au début.', crit: 'Il regarde le bébé calmement et se retire spontanément.' },
    { t: 'Une surveillance de tous les instants', min: 5, b: 'Ne laissez JAMAIS le chien seul avec le bébé, même un instant. Séparez-les avec une barrière ou une porte quand vous ne pouvez pas surveiller. Continuez les promenades, les jeux et l’affection : le chien ne doit pas associer bébé à une privation.', crit: 'Le chien reçoit du temps et de l’attention chaque jour, séparé du bébé quand nécessaire.' }
  ],
  plan: [['3 mois avant', 'Changer les routines, habituer à la barrière et à la place.'], ['2 mois avant', 'Sons de bébé à volume croissant, odeurs de bébé.'], ['1 mois avant', 'Place, Reste, Laisse-le avec distractions.'], ['Après la naissance', 'Rencontre progressive, surveillance permanente, temps quotidien pour le chien.']],
  next: ['Suivre la leçon « Chien et enfants : cohabiter en sécurité ».', 'Consulter un comportementaliste si le chien montre des signes de stress ou d’agressivité.', 'Apprendre aux enfants plus grands à respecter le chien.'],
  mistakes: ['Punir le chien qui grogne : il cache alors ses signaux et peut mordre sans prévenir.', 'Laisser bébé et chien seuls « une minute ».', 'Négliger le chien : la jalousie n’existe pas, mais le stress oui.', 'Découvrir l’odeur du bébé seulement le jour de l’arrivée.'],
  faq: [['Il grogne près du bébé.', 'Séparez-les immédiatement, ne le punissez pas et consultez un comportementaliste.'], ['Il veut lécher le bébé.', 'Ne le laissez pas s’approcher du visage ; redirigez-le vers sa place et récompensez.']],
  test: 'Le chien reste calme, sur sa place ou près de la barrière, pendant que vous vous occupez du bébé, plusieurs fois par jour.', safety: 'Les enfants très jeunes ne doivent jamais être laissés seuls avec un chien, quel que soit son caractère. Les morsures graves touchent surtout les jeunes enfants, souvent avec le chien de la maison. Signes de stress à repérer : léchage de museau, bâillements, évitement, raideur, grognement.' },

{ id: 'craintif', free: false, icon: '🫣', cat: 'Émotions', title: 'Chien craintif avec les inconnus : gagner confiance', from: 12, dur: '5 à 10 min × 1 par jour', span: '6 à 12 semaines', level: 'Avancé',
  goal: 'Votre chien reste détendu en présence d’inconnus, choisit d’aller vers eux à son rythme et n’a plus besoin de fuir ou d’aboyer.',
  why: 'La peur des inconnus vient d’un manque d’habituation, d’expériences négatives ou de la génétique. La forcer par le contact ou la punition l’aggrave. La méthode qui fonctionne : laisser le chien choisir, l’exposer à faible intensité et associer l’inconnu à quelque chose de très bon.',
  need: ['Friandises de haute valeur', 'Un lieu calme avec une échappatoire', 'Des complices calmes', 'Harnais confortable'],
  steps: [
    { t: 'Repérer les signes de peur', min: 5, b: 'Oreilles couchées, queue basse, léchage de museau, bâillements, évitement du regard, tremblements, halètement, fuite : ces signes montrent que l’inconnu est trop proche. Arrêtez-vous et reculez avant que la peur n’explose en aboiement ou en morsure.', crit: 'Vous repérez 5 signes de stress précocement.' },
    { t: 'Trouver la bonne distance', min: 5, b: 'Repérez la distance à laquelle il voit un inconnu sans stress et mange encore les friandises. Travaillez à cette distance. Toute la méthode repose sur cette distance de confort.', crit: 'Il mange des friandises en regardant un inconnu à distance.' },
    { t: 'L’inconnu qui ignore le chien', min: 10, b: 'Un complice reste de profil, ne regarde pas le chien, ne lui parle pas. Vous donnez des friandises quand il regarde le complice. Puis rapprochez-vous de quelques pas, si le chien reste détendu.', crit: 'Il reste détendu à 3 mètres d’un inconnu qui l’ignore.' },
    { t: 'Le laisser choisir', min: 10, b: 'Le complice laisse tomber des friandises derrière lui, sans regarder le chien. Le chien s’approche s’il le veut. Ne l’y poussez jamais ; c’est lui qui décide. Ne laissez jamais quelqu’un le caresser sans qu’il soit venu chercher lui-même le contact.', crit: 'Il s’approche volontairement d’un inconnu pour prendre une friandise.' },
    { t: 'Généraliser', min: 10, b: 'Répétez avec des personnes différentes, dans des lieux différents. Expliquez à vos visiteurs de l’ignorer, de ne pas se pencher, de ne pas le regarder dans les yeux. Chaque expérience positive consolide la confiance.', crit: 'Il reste détendu avec 3 inconnus différents.' }
  ],
  plan: [['Semaines 1 et 2', 'Repérer les signes de stress, trouver la distance de confort.'], ['Semaines 3 et 4', 'Travailler avec un complice qui ignore le chien.'], ['Semaines 5 à 8', 'Friandises lancées, le chien choisit de s’approcher.'], ['Semaines 9 à 12', 'Généraliser à d’autres personnes et d’autres lieux.']],
  next: ['Travailler avec un comportementaliste diplômé si la peur est intense ou s’il y a eu des morsures.', 'Suivre « Socialisation et habituation » et « Rencontrer d’autres chiens sereinement ».', 'Demander l’avis de votre vétérinaire : la douleur ou la maladie peuvent expliquer une peur soudaine.'],
  mistakes: ['Forcer le contact : « Il va bien s’y habituer » : cela aggrave la peur.', 'Punir les grognements ou aboiements : le chien cache alors ses signaux.', 'Laisser des inconnus le caresser sur la tête ou se pencher sur lui.', 'Le rassurer excessivement quand il tremble : récompensez plutôt le calme.'],
  faq: [['Il aboie sur les visiteurs.', 'Enfermez-le calmement dans une autre pièce avec un jouet fourré pendant l’arrivée, puis reprenez le travail en douceur.'], ['Il a mordu.', 'Ne prenez aucun risque : consultez un comportementaliste diplômé et votre vétérinaire.']],
  test: 'Il reste détendu et mange des friandises en présence de 3 inconnus différents, à 3 mètres, et choisit parfois de s’approcher.', safety: 'Un chien qui a déjà mordu ou tenté de mordre nécessite l’avis d’un comportementaliste diplômé. Ne laissez jamais un enfant ou un inconnu s’approcher d’un chien qui montre des signes de peur.' },

{ id: 'deux-chiens', free: false, icon: '🐕‍🦺', cat: 'Cohabitation', title: 'Deux chiens à la maison : les présenter et les faire cohabiter', from: 26, dur: 'Préparation sur 2 semaines', span: '2 à 8 semaines', level: 'Intermédiaire',
  goal: 'Vos deux chiens se présentent sereinement, partagent la maison, jouent sans conflit et disposent chacun de leurs ressources.',
  why: 'L’arrivée d’un second chien peut être un bonheur ou une source de tensions si elle est précipitée. Une présentation progressive sur terrain neutre, des ressources séparées et une attention équitable évitent la plupart des conflits.',
  need: ['Deux laisses et deux harnais', 'Deux gamelles, deux couchages, plusieurs jouets', 'Un espace neutre', 'Une barrière'],
  steps: [
    { t: 'Terrain neutre', min: 20, b: 'Première rencontre dehors, dans un lieu inconnu des deux, chacun tenu par une personne différente, en laisse détendue. Marchez à distance en parallèle, puis rapprochez-vous. Laissez-les se renifler quelques secondes, puis éloignez-les calmement.', crit: 'Ils marchent côte à côte sans tension.' },
    { t: 'L’entrée à la maison', min: 15, b: 'Entrez d’abord avec le chien résident, puis le nouveau, en laisse. Rangez avant les jouets, os et gamelles susceptibles de provoquer des tensions. Séparez-les avec une barrière la nuit et en votre absence les premiers jours.', crit: 'Ils explorent la maison sans conflit.' },
    { t: 'Des ressources pour chacun', min: 10, b: 'Deux gamelles, deux couchages, deux endroits de repos, plusieurs jouets. Nourrissez-les séparément, dans des pièces différentes. Ne donnez pas d’os à mâcher ensemble au début. La garde de ressources est la première cause de bagarres.', crit: 'Chacun mange et se repose sans surveiller l’autre.' },
    { t: 'Du temps individuel', min: 10, b: 'Chacun doit bénéficier de promenades, de jeux et d’éducation en solo chaque jour. Le chien résident ne doit pas « payer » l’arrivée du nouveau. Donnez-lui un temps de qualité, une attention particulière, et respectez sa place.', crit: 'Chaque chien a du temps individuel chaque jour.' },
    { t: 'Repérer et gérer les tensions', min: 5, b: 'Raideur, regard fixe, grognement, babines relevées, corps figé : intervenez calmement en éloignant l’un des chiens, sans crier ni les séparer à mains nues. Le jeu est sain s’il est réciproque, avec des pauses et des rôles qui alternent.', crit: 'Vous repérez la montée de tension avant le conflit.' }
  ],
  plan: [['Jour 1', 'Rencontre en terrain neutre, promenade en parallèle.'], ['Jours 2 à 7', 'Cohabitation à la maison avec barrière la nuit et en votre absence.'], ['Semaines 2 à 4', 'Repas séparés, promenades individuelles, jeux surveillés.'], ['Semaines 5 à 8', 'Alléger la séparation progressivement.']],
  next: ['Consulter un comportementaliste en cas de tensions répétées.', 'Voir « Partage serein : prévenir la garde de ressources ».', 'Faire stériliser si le vétérinaire le recommande pour réduire les tensions.'],
  mistakes: ['Les laisser « régler ça entre eux » : cela peut finir par une blessure.', 'Favoriser le nouveau au détriment du résident.', 'Donner les gamelles ou les os côte à côte au début.', 'Séparer en tirant sur le collier ou en mettant les mains entre les chiens : risque de morsure.'],
  faq: [['Ils se battent pour les jouets.', 'Retirez les jouets qui posent problème, proposez-en plusieurs identiques et travaillez « Laisse-le » et « Donne ».'], ['Le résident s’isole.', 'Donnez-lui un espace protégé et du temps de qualité, sans le forcer à interagir.']],
  test: 'Après 4 semaines, les deux chiens mangent, se reposent et jouent ensemble sans conflit.', safety: 'Ne séparez jamais deux chiens qui se battent avec les mains : utilisez un bruit fort, un objet large ou de l’eau à distance. En cas de blessure, consultez un vétérinaire : les morsures s’infectent vite.' }

);

PROGRAMS.push(
  { id: 'famille4', sp: 'dog', icon: '👨‍👩‍👧', title: 'Programme famille qui s’agrandit : 4 semaines', sub: 'Bébé, enfants ou second chien : bien préparer l’arrivée', weeks: [
    ['Semaine 1', 'Le calme et la place', ['place', 'attente']],
    ['Semaine 2', 'Maîtrise de soi', ['impulsions', 'laisse-le']],
    ['Semaine 3', 'Cohabiter en sécurité', ['bebe', 'enfants']],
    ['Semaine 4', 'Partager la maison', ['deux-chiens', 'ressources']]
  ] },
  { id: 'chiot-nuit3', sp: 'dog', icon: '🌙', title: 'Programme premières semaines du chiot : 3 semaines', sub: 'Nuits, propreté et confiance dès l’arrivée', weeks: [
    ['Semaine 1', 'Les premières nuits', ['nuits', 'caisse']],
    ['Semaine 2', 'Propreté et rituel', ['proprete', 'marqueur']],
    ['Semaine 3', 'Confiance et visite chez le véto', ['veto', 'manipulations']]
  ] }
);
