/* Wouf Éducation — leçons chien supplémentaires (Wouf Plus), 4ᵉ série : émotions, attention, maîtrise de soi,
   vie quotidienne et santé. Même méthode : renforcement positif, aucune contrainte physique ni punition.
   Contenu à faire relire par un éducateur ou un comportementaliste diplômé avant communication commerciale. */
LESSONS.push(

{ id: 'focus', free: false, icon: '👀', cat: 'Bases', title: 'Regarde-moi : l’attention à la demande', from: 10, dur: '3 min × 3 par jour', span: '1 à 3 semaines', level: 'Débutant',
  goal: 'Votre chien vous regarde dans les yeux dès que vous dites « Regarde », dans le calme puis avec des distractions, et garde son attention quelques secondes.',
  why: 'Un chien qui sait vous regarder à la demande a une réponse simple pour toutes les situations difficiles : croiser un chien, traverser une rue, patienter chez le vétérinaire. C’est la base de presque tous les autres exercices, et un excellent moyen de « recentrer » un chien excité.',
  need: ['Friandises très petites et appétissantes', 'Le marqueur « Oui ! » déjà chargé', 'Une pièce calme pour commencer'],
  steps: [
    { t: 'Récompenser le regard spontané', min: 3, b: 'Asseyez-vous, friandises en main. Dès que votre chien tourne les yeux vers votre visage, dites « Oui ! » et donnez la friandise. Pas de mot pour l’instant : il découvre que vous regarder rapporte. Répétez une vingtaine de fois par séance.', crit: 'Il vous regarde de lui-même au moins 10 fois en 2 minutes.' },
    { t: 'Attirer le regard et ajouter le mot', min: 3, b: 'Tenez une friandise à bout de bras, puis ramenez la main près de votre œil. Quand il vous regarde, « Oui ! » et récompensez avec l’autre main. Quand le regard arrive avant le geste, dites « Regarde » juste avant qu’il vous regarde.', crit: 'Il vous regarde au mot « Regarde », 8 fois sur 10, dans une pièce calme.' },
    { t: 'Allonger la durée', min: 3, b: 'Comptez « un » dans votre tête avant « Oui ! », puis deux, trois, jusqu’à cinq secondes. Augmentez d’une seconde seulement quand 8 réussites sur 10 sont acquises. Si le regard part, revenez à la durée précédente sans le gronder.', crit: 'Il tient le regard 5 secondes, 8 fois sur 10.' },
    { t: 'Ajouter des distractions', min: 5, b: 'Répétez dans le jardin, puis dans la rue calme, puis avec une personne qui passe, un jouet au sol, un bruit. Une distraction à la fois, et une récompense plus généreuse quand la difficulté monte. Si votre chien ne vous répond plus, éloignez-vous de la distraction.', crit: 'Il vous regarde au mot « Regarde » avec une distraction moyenne, 8 fois sur 10.' },
    { t: 'L’utiliser dans la vraie vie', min: 5, b: 'Demandez « Regarde » avant de traverser, avant de descendre de voiture, avant de saluer quelqu’un. Récompensez toujours ce regard, même une fois l’exercice bien installé, par une friandise ou un jeu.', crit: 'Il vous regarde spontanément avant de traverser, 8 fois sur 10.' }
  ],
  plan: [['Jours 1 à 3', 'Regard spontané : 2 séances de 2 minutes par jour, à la maison.'], ['Jours 4 à 7', 'Ajout du mot « Regarde » et regard de 1 à 3 secondes.'], ['Semaine 2', 'Regard de 5 secondes, au jardin puis dans la rue calme.'], ['Semaine 3', 'Distractions moyennes et utilisation avant chaque traversée.']],
  next: ['Enchaîner « Regarde » puis « Au pied » pour croiser des chiens sereinement.', 'Travailler le regard en marchant, à côté de vous.', 'Apprendre à votre chien à se tourner vers vous quand il entend son prénom malgré l’excitation.'],
  mistakes: ['Dire « Regarde » en boucle : dites-le une fois et attendez.', 'Tenir la friandise devant votre visage en permanence : le chien regarde la main, pas vos yeux.', 'Demander trop tôt avec de fortes distractions : commencez calme.', 'Fixer un chien craintif dans les yeux : certains chiens vivent cela comme une menace, laissez-le venir vers vous.'],
  faq: [['Il regarde la friandise, pas mes yeux.', 'Cachez d’abord la friandise dans votre poing, récompensez de l’autre main, ou récompensez uniquement quand le regard monte vers votre visage.'], ['Il détourne les yeux, il a l’air mal à l’aise.', 'Ne forcez pas : récompensez le moindre regard vers vous, même bref, et travaillez à un rythme plus lent.']],
  test: 'Dans la rue calme, il vous regarde 5 secondes au mot « Regarde », 8 fois sur 10.', safety: 'Ne fixez jamais un chien inconnu ou craintif dans les yeux : c’est un signe de défi dans son langage.' },

{ id: 'impulsions', free: false, icon: '🧘', cat: 'Calme', title: 'Maîtrise de soi : le jeu du « c’est ton choix »', from: 12, dur: '3 min × 3 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien choisit de lui-même de ne pas se jeter sur la nourriture ou le jouet qu’on lui propose, et attend calmement qu’on l’autorise.',
  why: 'La maîtrise de soi n’est pas de l’obéissance : c’est une compétence qui se muscle. Un chien qui a appris que « se retenir fait ouvrir la main » saute moins, ne vole pas et supporte mieux l’attente. C’est l’exercice le plus utile pour un chien excitable.',
  need: ['Friandises courantes (croquettes)', 'Friandises très appréciées', 'Un tapis ou un coin calme'],
  steps: [
    { t: 'La main fermée', min: 3, b: 'Placez une friandise dans votre main fermée, puis tendez-la vers le chien. S’il pousse, lèche ou gratte, ne bougez pas et ne dites rien. Dès qu’il s’éloigne, même un peu, dites « Oui ! » et donnez une friandise DIFFÉRENTE de l’autre main.', crit: 'Il s’éloigne de la main fermée dans les 5 secondes, 8 fois sur 10.' },
    { t: 'La main ouverte', min: 3, b: 'Ouvrez la main : s’il fonce, refermez-la aussitôt. Dès qu’il se retient, même une demi-seconde, « Oui ! » et récompensez de l’autre main. Puis laissez-le prendre cette friandise avec un « Libre ! » quand il vous regarde.', crit: 'Il se retient main ouverte 3 secondes, 8 fois sur 10.' },
    { t: 'La friandise au sol', min: 5, b: 'Posez la friandise au sol, la main prête à la couvrir. S’il se précipite, couvrez-la sans un mot. Quand il recule ou vous regarde, « Oui ! » puis récompense de votre main. Ensuite laissez-le la prendre avec « Libre ! ».', crit: 'Il ne se jette pas sur une friandise au sol pendant 5 secondes, 8 fois sur 10.' },
    { t: 'Le jouet, la porte, la gamelle', min: 5, b: 'Appliquez le même principe à d’autres situations : jouet lancé, porte qui s’ouvre, gamelle posée. Le chien apprend que se retenir est TOUJOURS payant. Utilisez vos meilleures récompenses pour les plus grandes tentations.', crit: 'Il se retient dans 3 situations différentes.' },
    { t: 'Relâcher sur signal, sans tricher', min: 3, b: 'Choisissez un mot de libération unique (« Libre ! ») et ne l’utilisez que pour cela. Variez le délai : 1 seconde, puis 10, puis 30 avant de dire « Libre ! ». Vous exercez un vrai « muscle d’attente ».', crit: 'Il attend 10 secondes devant une friandise au sol, 8 fois sur 10.' }
  ],
  plan: [['Jours 1 à 3', 'Main fermée : 3 séances de 10 répétitions.'], ['Jours 4 à 7', 'Main ouverte, puis friandise au sol couverte.'], ['Semaine 2', 'Friandise libre au sol, délais de 1 à 5 secondes.'], ['Semaines 3 et 4', 'Jouet, porte, gamelle ; délai de 10 à 30 secondes.']],
  next: ['Passer sur des tentations plus fortes (poulet, saucisse).', 'Jouer à « c’est ton choix » en marchant, avec une friandise posée sur le trottoir.', 'Associer cette maîtrise à « Laisse-le » et « Reste ».'],
  mistakes: ['Punir ou gronder quand il fonce : il apprend à guetter votre main, pas à se retenir.', 'Donner la friandise de la main d’où il voulait la prendre : récompensez toujours de l’autre main.', 'Aller trop vite en ouvrant la main : progressez seulement à 8 réussites sur 10.', 'Dire « Non ! » en boucle : le silence est plus clair.'],
  faq: [['Il n’arrête pas de gratter ma main.', 'C’est normal au début, attendez sans bouger : c’est l’absence de résultat qui lui apprend à changer de stratégie.'], ['Il se retient seulement quand j’ai la main sur la friandise.', 'Allongez très progressivement la distance de la main avant de la retirer.']],
  test: 'Une friandise posée au sol : il attend 10 secondes sans y toucher, puis la prend au mot « Libre ! », 8 fois sur 10.', safety: 'Ce jeu est fait pour votre chien seul : pour les enfants, ne le pratiquez que sous surveillance directe d’un adulte.' },

{ id: 'reactivite', free: false, icon: '🐕‍🦺', cat: 'Émotions', title: 'Chien réactif en laisse : aboiements et fonçages', from: 26, dur: '10 min × 1 à 2 par jour', span: '6 à 12 semaines', level: 'Avancé',
  goal: 'Votre chien reste calme en croisant un autre chien (ou un déclencheur) à une distance de plus en plus courte, sans aboyer ni foncer, et se tourne vers vous de lui-même.',
  why: 'Les aboiements et fonçages en laisse viennent presque toujours de la peur, de la frustration ou d’un excès d’excitation, pas de « dominance ». Punir augmente le stress et associe l’autre chien à quelque chose de désagréable. La bonne méthode : rester sous le seuil de réaction et associer la vue du déclencheur à quelque chose d’excellent.',
  need: ['Friandises de très haute valeur (poulet, fromage en dés)', 'Harnais bien ajusté et laisse de 1,5 à 2 mètres', 'Un endroit calme avec de l’espace (parc peu fréquenté)', 'Un ami avec un chien calme (idéal)'],
  steps: [
    { t: 'Trouver la distance de sécurité', min: 5, b: 'Repérez la distance à laquelle votre chien voit l’autre chien sans réagir (il regarde, mais reste détendu, prend encore les friandises). C’est son « seuil » : on travaille toujours en deçà. Si un chien de 30 mètres déclenche déjà tout, on démarre à 40 ou 50 mètres.', crit: 'Vous connaissez la distance où il reste détendu et prend des friandises.' },
    { t: 'Jeu « Regarde ça »', min: 5, b: 'Dès que le déclencheur apparaît à bonne distance et que votre chien le regarde calmement : « Oui ! » et friandise. Le message : voir un chien = poulet. Puis il se tourne vers vous en attendant la récompense. C’est le signe que l’émotion se transforme.', crit: 'Il se tourne vers vous après avoir regardé le chien, 8 fois sur 10.' },
    { t: 'Réduire la distance par petits paliers', min: 10, b: 'Quand le chien est détendu 8 fois sur 10 à une distance donnée, rapprochez-vous de quelques pas seulement. S’il réagit (raideur, aboiement), reculez de plusieurs mètres et recommencez plus loin : vous êtes allé trop vite. Une séance réussie se termine toujours sur un succès.', crit: 'Il reste détendu à la distance choisie, 3 séances de suite.' },
    { t: 'Le demi-tour d’urgence', min: 5, b: 'Entraînez « Par ici » (demi-tour joyeux) à froid, puis utilisez-le AVANT la réaction dès que le chien se raidit. Éloignez-vous calmement, récompensez au retour au calme. Fuir n’est pas un échec : cela protège la relation et le seuil.', crit: 'Il fait demi-tour sur « Par ici » en présence d’un chien à distance moyenne.' },
    { t: 'Croiser en pratique', min: 10, b: 'Croisez sur un trottoir large ou en arc de cercle : passez du côté opposé, en marchant sans vous arrêter, friandises à la volée. Ne laissez pas les chiens se saluer en tirant sur leur laisse. Gardez une laisse souple, votre respiration calme et votre voix joyeuse.', crit: 'Il croise un chien à 5 mètres sans aboyer, 8 fois sur 10.' }
  ],
  plan: [['Semaine 1', 'Repérer le seuil et jouer à « Regarde ça » à cette distance, 1 séance par jour.'], ['Semaines 2 et 3', 'Se rapprocher de 2 à 3 mètres par séance réussie, avec un chien « complice » si possible.'], ['Semaines 4 à 6', 'Demi-tour d’urgence à froid, puis avant la réaction lors des vrais croisements.'], ['Semaines 7 à 12', 'Croisements sur trottoir large, puis étroits, puis avec plusieurs chiens.']],
  next: ['Travailler avec un éducateur ou comportementaliste diplômé si la réaction est intense.', 'Ajouter le « Regarde-moi » et « Au pied » pour choisir vos trajectoires.', 'Travailler la tolérance aux vélos, joggers et enfants avec la même méthode.'],
  mistakes: ['Tirer sur la laisse ou utiliser un collier étrangleur ou à pointes : la douleur associée à l’autre chien aggrave le problème.', 'Attendre que le chien aboie pour récompenser le retour au calme : récompensez avant la réaction.', 'Laisser les chiens « se dire bonjour » en laisse tendue : c’est le moment où cela dégénère.', 'Aller trop près, trop vite : chaque échec renforce la réactivité.'],
  faq: [['Il aboie même de très loin.', 'Reculez encore : votre point de départ est trop près. À 60 ou 80 mètres, c’est déjà un bon départ.'], ['Il ne prend plus les friandises.', 'Il est trop stressé, sous le seuil de travail : augmentez la distance, utilisez une friandise plus appétissante et arrêtez la séance.']],
  test: 'Il croise un chien inconnu à 5 mètres sur le trottoir sans aboyer ni foncer, et vous regarde de lui-même, 8 fois sur 10.', safety: 'Si votre chien a déjà mordu ou tenté de mordre, consultez un comportementaliste diplômé avant de continuer. Écartez toujours le risque de douleur : un chien réactif peut avoir mal, faites vérifier sa santé par votre vétérinaire.' },

{ id: 'destruction', free: false, icon: '🦴', cat: 'Savoir-vivre', title: 'Mâchouiller sans tout détruire', from: 12, dur: '5 min × 2 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien mâche ses propres jouets et mâchouilles à la maison, laisse meubles et chaussures tranquilles, et se détend en travaillant un jouet fourré.',
  why: 'Mâcher est un besoin naturel qui apaise le chien et soigne les dents chez le chiot. Détruire vient souvent de l’ennui, du manque d’activité ou du stress. L’objectif n’est pas d’empêcher de mâcher, mais de lui offrir de bonnes choses à mâcher, et de sécuriser la maison.',
  need: ['Plusieurs jouets à mâcher de textures différentes', 'Un jouet à fourrer (type Kong) et de la pâtée', 'Tapis de léchage ou boîte à fouiller', 'Barrières, porte de pièce'],
  steps: [
    { t: 'Sécuriser la maison', min: 5, b: 'Rangez chaussures, câbles, télécommandes et vêtements hors de portée. Utilisez une barrière ou une porte pour limiter l’accès aux pièces à risque quand vous ne pouvez pas surveiller. Aider le chien à réussir vaut mieux que le punir pour ce qu’il a détruit.', crit: 'Aucun objet précieux n’est accessible sans surveillance.' },
    { t: 'Rendre les bons jouets irrésistibles', min: 5, b: 'Proposez 3 à 4 objets à mâcher, en changeant chaque jour pour garder la nouveauté. Frottez-les de pâté, remplissez-les d’aliments. Dès qu’il prend un bon objet, « Oui ! » et félicitations calmes, sans jeu excité.', crit: 'Il choisit spontanément un de ses jouets pour mâcher, 8 fois sur 10.' },
    { t: 'L’échange plutôt que la confiscation', min: 3, b: 'S’il a pris un objet interdit, ne criez pas et ne courez pas après lui : proposez une friandise ou un jouet plus attractif à l’opposé de la pièce. Quand il lâche, récompensez, puis rendez-lui un objet autorisé.', crit: 'Il lâche un objet contre une friandise, 8 fois sur 10.' },
    { t: 'Occuper l’esprit et le corps', min: 10, b: 'Avant vos absences ou les moments d’excitation : promenade avec reniflage, jeu de recherche, repas distribué dans un jouet. Un chien fatigué et rassasié mentalement détruit beaucoup moins. Pensez aussi aux pauses de calme (30 minutes) après l’activité.', crit: 'Il s’occupe calmement avec un jouet fourré pendant 15 minutes.' },
    { t: 'Repérer les vraies causes', min: 5, b: 'Si les dégâts n’ont lieu qu’en votre absence, avec plaintes, salivation ou agitation, c’est probablement de l’anxiété de séparation : travaillez la leçon « Apprendre la solitude ». Si le chiot est en poussée dentaire, les jouets frais aident.', crit: 'Vous savez si les dégâts sont liés à l’ennui, à la dentition ou à l’anxiété.' }
  ],
  plan: [['Jours 1 à 2', 'Sécuriser la maison, préparer 3 jouets à mâcher et un jouet fourré.'], ['Jours 3 à 7', 'Un jouet fourré par jour, échange « lâche » contre friandise.'], ['Semaines 2 et 3', 'Séances de 15 minutes de jouet fourré pendant vos moments de calme.'], ['Semaine 4', 'Alléger la surveillance et surveiller les dégâts : ajustez selon les causes.']],
  next: ['Faire congeler les jouets fourrés pour prolonger l’effet apaisant.', 'Apprendre « Donne » et « Laisse-le » pour les objets dangereux.', 'Créer un coin « bureau » où il mâche à côté de vous pendant que vous travaillez.'],
  mistakes: ['Gronder après coup : le chien ne relie pas votre colère à ce qu’il a fait il y a une heure.', 'Lui donner de vieilles chaussures « à mâcher » : il ne fait pas la différence avec les neuves.', 'Offrir des jouets durs qui peuvent casser les dents (os cuits, bois, pierres).', 'Ne jamais le fatiguer : un chien qui s’ennuie s’occupe tout seul.'],
  faq: [['Il détruit seulement quand je pars.', 'C’est le signe classique de stress de séparation : la solution est la préparation à la solitude, pas de punir.'], ['Mon chiot mâche tout, tout le temps.', 'C’est normal jusqu’à 6 à 8 mois : proposez des jouets frais et texturés, et surveillez-le de près.']],
  test: 'Pendant 15 minutes, il mâche un jouet autorisé sans toucher aux meubles ni aux chaussures accessibles.', safety: 'Choisissez des jouets de taille adaptée (jamais assez petits pour être avalés) et surveillez les morceaux : jetez un jouet abîmé ou percé. Un chien qui avale des morceaux de tissu ou de plastique nécessite un avis vétérinaire en urgence.' },

{ id: 'poursuite', free: false, icon: '🚴', cat: 'Sécurité', title: 'Instinct de chasse : vélos, joggers, chats et gibier', from: 20, dur: '5 à 10 min × 1 à 2 par jour', span: '6 à 12 semaines', level: 'Avancé',
  goal: 'Votre chien remarque un cycliste, un coureur ou un animal en mouvement, mais se tourne vers vous au lieu de poursuivre, et vous suit sur « Par ici » ou « Stop ».',
  why: 'Poursuivre est un instinct génétique, particulièrement chez les chiens de troupeau, les lévriers ou les terriers. C’est auto-récompensant : chaque poursuite renforce l’envie. On ne supprime pas l’instinct, on le canalise vers des jeux acceptables et on apprend au chien à se maîtriser en présence de l’excitant.',
  need: ['Longe de 5 à 10 mètres et harnais', 'Jouet de traction ou balle sur cordelette', 'Friandises très alléchantes', 'Un ami à vélo ou qui court, pour l’entraînement'],
  steps: [
    { t: 'Gérer pour ne plus réussir la poursuite', min: 5, b: 'Tant que le chien n’est pas fiable, ne le lâchez jamais en présence de déclencheurs : longe ou laisse sur harnais. Chaque poursuite réussie est une répétition qui renforce l’instinct, alors que chaque poursuite évitée le fait s’éteindre.', crit: 'Aucune poursuite réussie sur les 7 derniers jours.' },
    { t: 'Récompenser le regard vers vous', min: 5, b: 'À grande distance d’un déclencheur, dès que votre chien vous regarde au lieu de fixer la proie : « Oui ! » et friandise généreuse. Recommencez en réduisant lentement la distance. Il apprend que résister à la course est rentable.', crit: 'Il vous regarde spontanément à 30 mètres d’un cycliste, 8 fois sur 10.' },
    { t: 'Offrir un exutoire : le jeu de proie', min: 10, b: 'Un jouet lié à une longe ou une balle sur une perche : faites-le courir, laissez le chien le poursuivre, puis capturer après un « Prêt ? » et un instant de pause. Donnez chaque jour 5 minutes de vraie chasse simulée pour combler l’instinct sans danger.', crit: 'Il attend votre signal avant de poursuivre le jouet, 8 fois sur 10.' },
    { t: 'Signal d’arrêt et retour', min: 5, b: 'Sur longe, dites « Stop » ou « Par ici » AVANT la course, dès qu’il repère le déclencheur. Récompensez lourdement. Avec un ami à vélo ou qui court à distance, enchaînez les passages, de plus en plus proches.', crit: 'Il s’arrête ou revient sur signal à 10 mètres d’un cycliste, 8 fois sur 10.' },
    { t: 'Maîtrise durable', min: 10, b: 'Continuez à garder la longe en zones à risque et faites-lui chercher des odeurs (nosework) pour dépenser son énergie. Une poursuite « échappée » ne doit jamais devenir une habitude : ne le lâchez que dans les lieux sûrs et clos.', crit: 'Il supporte un cycliste à 5 mètres sur longe sans tirer.' }
  ],
  plan: [['Semaine 1', 'Gérer le quotidien (longe partout) et jouer 5 minutes par jour au jouet de proie.'], ['Semaines 2 à 4', 'Regard vers vous à distance d’un déclencheur, avec récompenses très généreuses.'], ['Semaines 5 à 8', 'Stop et Par ici sur longe, cycliste ou coureur complice à distance décroissante.'], ['Semaines 9 à 12', 'Généraliser à d’autres déclencheurs (chats, oiseaux, lapins) en restant sur longe.']],
  next: ['Pratiquer le nosework et la recherche de friandises pour canaliser le pistage.', 'Envisager un sport adapté (canicross, agility) avec un club canin.', 'Ne lâcher le chien que dans un espace clos tant que le rappel n’est pas parfait en présence de distractions.'],
  mistakes: ['Le lâcher « pour voir » : l’échec vaut 100 séances de progrès.', 'Le rappeler quand il court déjà : il vous ignore, cela ruine le rappel.', 'Crier ou tirer sur la laisse : cela augmente l’excitation.', 'Ignorer la dépense physique et mentale quotidienne.'],
  faq: [['Il ignore complètement le rappel quand il chasse.', 'Normal : l’instinct l’emporte. Travaillez le Stop AVANT la course et gardez la longe au quotidien.'], ['Mon chien poursuit les voitures.', 'C’est un risque vital : ne le lâchez jamais près des routes, travaillez avec un éducateur diplômé.']],
  test: 'Sur longe, il voit un cycliste passer à 5 mètres, vous regarde et attend sa récompense, 8 fois sur 10.', safety: 'Les poursuites peuvent causer des accidents graves (route, chute, gibier). Ne le lâchez que dans un espace clos et sûr tant que le rappel n’est pas parfait. Respectez la réglementation sur la faune sauvage.' },

{ id: 'ville', free: false, icon: '🏙️', cat: 'Balades', title: 'Vie en ville : trottoirs, ascenseurs, terrasses, transports', from: 12, dur: '10 min × 1 par jour', span: '3 à 6 semaines', level: 'Intermédiaire',
  goal: 'Votre chien marche calmement en ville, entre dans un ascenseur, patiente sous une table de café et voyage dans les transports autorisés, sans stress.',
  why: 'La ville est riche en sons, odeurs, foules et surfaces inhabituelles (grilles, escaliers roulants, sols glissants). Une habituation progressive, par paliers courts, évite les peurs durables et fait de vos sorties de vrais moments de plaisir.',
  need: ['Harnais bien ajusté et laisse courte', 'Friandises très appréciées', 'Un tapis ou une petite couverture', 'Muselière conditionnée (selon les transports)'],
  steps: [
    { t: 'Trottoirs et bruits', min: 10, b: 'Commencez dans une rue calme, à l’heure creuse, et marchez 5 à 10 minutes. Récompensez le regard vers vous quand un bus, une moto ou une sirène passe. Augmentez progressivement l’animation de la rue. Si le chien se fige ou tire, éloignez-vous, calmez-le, réessayez plus tard.', crit: 'Il marche détendu à côté de vous dans une rue animée, 8 fois sur 10.' },
    { t: 'Sols et obstacles', min: 5, b: 'Grilles d’égout, sols brillants, escaliers ajourés : invitez-le à explorer avec une friandise posée à côté, sans le forcer. Félicitez chaque tentative. Les sols inconnus sont souvent la première cause de refus.', crit: 'Il marche sur 3 types de sols inhabituels sans hésiter.' },
    { t: 'Ascenseurs et portes automatiques', min: 5, b: 'Entrez avec le chien près de vous, assis ou en « Pied », laisse courte. Pour les portes qui s’ouvrent seules, avancez tranquillement en le récompensant. Évitez les ascenseurs bondés au début et surveillez les portes qui se ferment.', crit: 'Il entre et sort de l’ascenseur calmement, 8 fois sur 10.' },
    { t: 'La terrasse de café', min: 15, b: 'Emportez son tapis. Installez-le sous la table, demandez « Place », récompensez régulièrement le calme. Commencez par 10 minutes puis allongez. Apportez une mâchouille ou un jouet fourré pour occuper les longues attentes.', crit: 'Il reste allongé sur son tapis pendant 20 minutes, 8 fois sur 10.' },
    { t: 'Transports et foule', min: 15, b: 'Renseignez-vous sur les règles locales (petit chien en sac, muselière obligatoire pour les grands). Faites un premier trajet court, aux heures creuses, chien près de vous, friandises pour le calme. Restez à l’écoute des signes de stress (halètement, bâillements, léchage de museau).', crit: 'Il voyage 10 minutes dans les transports sans signe de stress.' }
  ],
  plan: [['Semaine 1', 'Marche en rue calme, 10 minutes par jour, avec récompense du regard vers vous.'], ['Semaine 2', 'Sols inhabituels, portes automatiques et ascenseurs vides.'], ['Semaine 3', 'Terrasse ou banc : tapis, « Place », 10 minutes.'], ['Semaines 4 à 6', 'Premiers transports courts, foule et magasins autorisés aux chiens.']],
  next: ['Habituer le chien à la muselière, utile dans certains transports.', 'Préparer les vacances en ville avec la leçon « Partir en vacances ».', 'Travailler « Reste » et « Place » dans des lieux de plus en plus animés.'],
  mistakes: ['Le confronter d’un coup à la foule : mieux vaut 5 minutes agréables qu’une heure de stress.', 'Le traîner sur un sol qu’il refuse : recommencez avec une friandise et de la patience.', 'Négliger les besoins : il faut des pauses pipi et de l’eau régulièrement.', 'Oublier la chaleur du bitume l’été : testez du dos de la main.'],
  faq: [['Il a peur des bruits de la ville.', 'Travaillez la leçon « Bruits forts, orages et pétards » et récompensez chaque réaction calme.'], ['Il refuse d’avancer.', 'Il est probablement dépassé : éloignez-vous, calmez-le et reprenez à un endroit plus tranquille.']],
  test: 'Il marche détendu en ville pendant 20 minutes, entre dans un ascenseur et reste couché 20 minutes sous une table de café.', safety: 'Utilisez un harnais bien ajusté (jamais un collier étrangleur) et gardez la laisse courte en foule. En été, le bitume brûle les coussinets : testez le sol avec le dos de la main pendant 5 secondes.' },

{ id: 'randonnee', free: false, icon: '🥾', cat: 'Voyage', title: 'Partir en randonnée avec son chien', from: 52, dur: 'Préparation sur 3 semaines', span: '3 à 4 semaines', level: 'Intermédiaire',
  goal: 'Vous partez en randonnée avec un chien en forme, préparé, équipé, qui boit régulièrement, marche à un rythme adapté et revient sans blessure ni coup de chaleur.',
  why: 'La randonnée est un bonheur partagé, mais aussi un effort important : chaleur, dénivelé, cailloux, tiques, animaux sauvages, troupeaux. Préparer l’équipement, la forme et le parcours réduit fortement les risques.',
  need: ['Harnais et longe de 2 à 5 mètres', 'Gamelle pliable et eau en quantité', 'Trousse de premiers secours canine', 'Tire-tique, friandises, sacs à déjections'],
  steps: [
    { t: 'Vérifier la forme du chien', min: 5, b: 'Faites vérifier par votre vétérinaire l’état des articulations, du cœur et des coussinets avant une sortie longue. Un chiot en croissance (avant 12 à 18 mois selon la race), un senior ou un chien en surpoids ne doivent pas enchaîner de longues distances ou de forts dénivelés.', crit: 'Votre chien est vacciné, protégé contre les parasites et apte à l’effort.' },
    { t: 'Entraîner progressivement', min: 30, b: 'Augmentez la durée de vos balades de 10 à 15 % par semaine. Ajoutez des montées et des terrains variés. Regardez l’état de ses coussinets et sa récupération : un chien fatigué, qui traîne ou halète trop doit s’arrêter.', crit: 'Il enchaîne 1 h 30 de marche sans signe d’épuisement.' },
    { t: 'Préparer l’équipement', min: 15, b: 'Emportez eau en quantité (comptez large), gamelle pliable, friandises, trousse de secours, tire-tique, couverture de survie. Un sac à dos pour chien ne doit pas dépasser 10 % de son poids, et n’est pas conseillé pour les chiots ou les chiens fragiles.', crit: 'Votre sac est prêt la veille avec eau, trousse et tire-tique.' },
    { t: 'Gérer chaleur, eau et pauses', min: 5, b: 'Partez tôt, faites des pauses à l’ombre toutes les 30 à 45 minutes et proposez de l’eau régulièrement. Par forte chaleur, renoncez : le coup de chaleur peut être mortel. Ne lui faites pas boire d’eau stagnante (cyanobactéries, leptospirose).', crit: 'Vous proposez de l’eau et une pause toutes les 30 à 45 minutes.' },
    { t: 'Croiser troupeaux, randonneurs et faune', min: 10, b: 'Tenez le chien en laisse près des troupeaux, des chiens de protection (patous) et dans les zones protégées. Restez à distance, contournez largement, ne courez pas. Ramassez les déjections et respectez la réglementation locale.', crit: 'Il reste en laisse et calme à l’approche d’un troupeau ou d’un randonneur.' }
  ],
  plan: [['Semaine 1', 'Bilan vétérinaire, vérification du matériel, balades de 1 h.'], ['Semaine 2', 'Balades de 1 h 30 avec dénivelé, contrôle des coussinets.'], ['Semaine 3', 'Sortie test de 2 h, sac prêt, pauses et eau.'], ['Le jour J', 'Départ tôt, eau, pauses ; inspection complète (tiques, coussinets) au retour.']],
  next: ['Passer à des randonnées plus longues en augmentant de 10 % par semaine.', 'Repérer à l’avance les points d’eau et les vétérinaires du secteur.', 'Apprendre le « Laisse-le » pour les charognes et déchets en chemin.'],
  mistakes: ['Partir sans avoir préparé le chien : la fatigue arrive vite.', 'Sous-estimer l’eau et la chaleur : les coups de chaleur sont fréquents.', 'Lâcher le chien près d’un troupeau ou en zone protégée.', 'Oublier de vérifier tiques et coussinets au retour.'],
  faq: [['Mon chien boite après la randonnée.', 'Repos strict, vérification des coussinets ; si la boiterie persiste plus de 24 à 48 h, consultez.'], ['Puis-je emmener mon chiot ?', 'Uniquement sur des sorties courtes et plates : les articulations sont fragiles avant 12 à 18 mois.']],
  test: 'Vous terminez une sortie de 2 heures : il a bu régulièrement, ses coussinets sont intacts et il récupère normalement en quelques heures.', safety: 'Signes d’un coup de chaleur : halètement intense, bave, langue très rouge, faiblesse, vomissements : mettez-le à l’ombre, mouillez-le à l’eau tiède (pas glacée) et partez chez le vétérinaire immédiatement.' },

{ id: 'dents', free: false, icon: '🦷', cat: 'Soins', title: 'Brossage des dents et hygiène dentaire', from: 10, dur: '2 min × 1 par jour', span: '3 à 4 semaines', level: 'Utile',
  goal: 'Votre chien accepte le brossage de ses dents plusieurs fois par semaine, voire chaque jour, sans stress, et vous repérez les signes d’un problème dentaire.',
  why: 'La majorité des chiens de plus de 3 ans ont du tartre, source d’infection des gencives, de douleur et parfois de problèmes cardiaques ou rénaux. Le brossage régulier est la meilleure prévention, et la préparation progressive évite les conflits.',
  need: ['Brosse à dents pour chien ou doigtier', 'Dentifrice pour chien (JAMAIS de dentifrice humain)', 'Friandises très alléchantes', 'Lingette ou compresse pour la 1ʳᵉ étape'],
  steps: [
    { t: 'Se laisser toucher la bouche', min: 2, b: 'Soulevez doucement la lèvre 1 seconde, « Oui ! » et friandise. Puis 2 secondes, puis frottez une gencive avec le doigt. Répétez sur plusieurs jours, toujours en récompensant. Si le chien recule, revenez à l’étape précédente.', crit: 'Il accepte que vous souleviez ses lèvres et frottiez une gencive, 8 fois sur 10.' },
    { t: 'Le goût du dentifrice', min: 2, b: 'Laissez-le lécher un peu de dentifrice pour chien sur votre doigt : ce doit être un plaisir. Si le goût lui plaît, il associera la brosse à un moment agréable. Choisissez un goût qu’il aime (volaille, bœuf).', crit: 'Il lèche le dentifrice avec enthousiasme.' },
    { t: 'Présenter la brosse', min: 2, b: 'Montrez la brosse enduite de dentifrice, laissez-le la lécher, puis la mettre en bouche. Frottez une dent, puis deux, puis une rangée, en récompensant chaque étape. Progressez très lentement.', crit: 'Il tolère 3 secondes de brossage sur une rangée de dents.' },
    { t: 'Brosser toute la bouche', min: 3, b: 'Petits cercles à 45° vers la gencive, côtés externes surtout, 30 secondes par côté. Ne cherchez pas à brosser l’intérieur des dents au début : le côté externe est le plus important. Terminez toujours par un jeu ou une friandise.', crit: 'Il accepte 1 minute de brossage complet, 8 fois sur 10.' },
    { t: 'La routine et les signaux d’alerte', min: 2, b: 'Brossez au moins 3 fois par semaine, idéalement chaque jour, au même moment. Repérez les signes qui imposent une consultation : mauvaise haleine forte, gencives rouges ou qui saignent, tartre épais, salivation, dents cassées, refus de mâcher.', crit: 'Le brossage fait partie de sa routine au moins 3 fois par semaine.' }
  ],
  plan: [['Jours 1 à 3', 'Toucher les lèvres et frotter une gencive avec le doigt, 3 fois par jour.'], ['Jours 4 à 7', 'Goût du dentifrice sur votre doigt, puis présentation de la brosse.'], ['Semaine 2', 'Brosser d’un côté, 30 secondes, avec récompense.'], ['Semaine 3 et suivantes', 'Brossage complet 1 à 2 minutes, chaque jour ou 3 fois par semaine.']],
  next: ['Demander à votre vétérinaire un détartrage si le tartre est épais.', 'Utiliser des produits d’hygiène dentaire reconnus (labels vétérinaires), en complément et non en remplacement du brossage.', 'Rester attentif à la douleur : un chien qui mange d’un côté peut souffrir d’une dent.'],
  mistakes: ['Utiliser du dentifrice humain : le fluor et le xylitol sont toxiques.', 'Forcer la bouche : le chien s’en souviendra et refusera toute manipulation.', 'Compter uniquement sur des croquettes ou os à mâcher : ils ne remplacent pas le brossage et certains cassent les dents.', 'Attendre un problème visible : consultez avant que la douleur ne s’installe.'],
  faq: [['Il refuse toute manipulation de la bouche.', 'Repartez à zéro : quelques secondes par jour, avec un excellent goût, et demandez de l’aide à un éducateur si besoin.'], ['À quelle fréquence brosser ?', 'Idéalement chaque jour. Même 3 fois par semaine est déjà utile.']],
  test: 'Il accepte 1 minute de brossage complet, 3 fois par semaine, sans se dérober.', safety: 'Ne jamais utiliser de dentifrice humain (fluor, xylitol toxiques). En cas de gencive qui saigne beaucoup, de dent cassée, de mauvaise haleine persistante ou de gonflement du visage, consultez rapidement un vétérinaire.' },

{ id: 'vol', free: false, icon: '🍗', cat: 'Savoir-vivre', title: 'Fini les vols de nourriture : plan de travail, poubelle, table', from: 12, dur: '5 min × 2 par jour', span: '2 à 4 semaines', level: 'Intermédiaire',
  goal: 'Votre chien laisse le plan de travail, la table et la poubelle tranquilles, se couche pendant que vous cuisinez ou mangez et attend sa récompense.',
  why: 'Voler de la nourriture est très payant : chaque réussite renforce le comportement. On ne peut pas « raisonner » un chien gourmand : on empêche le vol (gestion), on apprend une alternative claire (aller sur sa place) et on récompense le calme. Certains aliments sont dangereux : chocolat, raisin, oignon, xylitol.',
  need: ['Un tapis et un coin calme', 'Friandises', 'Poubelle fermée, garde-manger verrouillé', 'Barrière ou porte de cuisine'],
  steps: [
    { t: 'Rendre le vol impossible', min: 5, b: 'Rangez la nourriture hors d’atteinte, fermez poubelles et placards, rentrez le plat dès la cuisson terminée. Un chien qui ne réussit jamais à voler perd l’habitude. Apprenez-le aussi à toute la famille : une seule personne qui cède suffit à ruiner l’effort.', crit: 'Plus aucun vol réussi depuis 7 jours.' },
    { t: 'La place pendant que vous cuisinez', min: 5, b: 'Installez son tapis à l’entrée de la cuisine. Demandez « Place », récompensez régulièrement le calme (friandise posée sur le tapis). Commencez par 1 minute, puis 5, puis toute la préparation du repas.', crit: 'Il reste sur sa place 5 minutes pendant que vous cuisinez, 8 fois sur 10.' },
    { t: 'Ne pas mendier à table', min: 5, b: 'Pendant vos repas, il est sur son tapis avec une mâchouille ou un jouet fourré. Ne lui donnez rien de votre assiette : chaque cession relance la mendicité. Récompensez sa présence calme, à distance de la table.', crit: 'Il reste sur sa place 15 minutes pendant un repas.' },
    { t: 'Apprendre « Laisse-le »', min: 5, b: 'Posez une friandise dans votre main fermée, dites « Laisse-le », récompensez quand il se détourne, puis progressez : main ouverte, friandise au sol, plat sur la table basse. Appliquez à la nourriture tombée par accident.', crit: 'Il laisse une friandise au sol au mot « Laisse-le », 8 fois sur 10.' },
    { t: 'Si un aliment dangereux est avalé', min: 2, b: 'Sachez quoi faire : chocolat, raisins, oignon, ail, xylitol (chewing-gum), os cuits, ou médicaments avalés imposent d’appeler un vétérinaire ou le centre antipoison immédiatement. Ne provoquez pas de vomissement sans avis professionnel.', crit: 'Vous connaissez le numéro de votre vétérinaire et d’un centre antipoison vétérinaire.' }
  ],
  plan: [['Jours 1 à 3', 'Sécuriser cuisine et poubelles, installer le tapis à l’entrée de la cuisine.'], ['Jours 4 à 7', 'Place pendant la préparation des repas, récompenses régulières.'], ['Semaine 2', 'Place pendant le repas de la famille, avec jouet fourré.'], ['Semaines 3 et 4', 'Laisse-le sur nourriture au sol, sans tentation à portée.']],
  next: ['Mettre la gamelle dans un jouet de distribution pour occuper le chien pendant le repas.', 'Apprendre « Donne » pour échanger ce qu’il a volé.', 'Sécuriser voyages et pique-niques avec la même méthode.'],
  mistakes: ['Céder « juste une fois » : c’est la source de la mendicité.', 'Punir après le vol : il ne comprend pas le lien.', 'Laisser la nourriture sur le plan de travail « parce qu’il ne le fait jamais ».', 'Croire que le chien « sait » qu’il a mal fait : sa mine coupable est de la peur, pas du remords.'],
  faq: [['Il fouille la poubelle.', 'Utilisez une poubelle fermée ou placez-la dans un placard : c’est la gestion la plus efficace.'], ['Il aboie pour avoir à manger.', 'Ignorez l’aboiement, récompensez le silence et la place, et ne cédez jamais.']],
  test: 'Il reste sur sa place pendant un repas complet de la famille et ne touche pas à la nourriture laissée à sa portée pendant 30 secondes.', safety: 'Raisins, chocolat, oignon, ail, xylitol et os cuits sont dangereux : en cas d’ingestion, appelez sans attendre un vétérinaire ou un centre antipoison vétérinaire.' }

);

PROGRAMS.push(
  { id: 'ville4', sp: 'dog', icon: '🏙️', title: 'Programme chien citadin : 4 semaines', sub: 'Serein en ville, au café et dans les transports', weeks: [
    ['Semaine 1', 'Attention et maîtrise de soi', ['focus', 'impulsions']],
    ['Semaine 2', 'Marcher et patienter', ['pied', 'attente']],
    ['Semaine 3', 'Le calme sous la table', ['place', 'ville']],
    ['Semaine 4', 'Sons, foule et rencontres', ['bruits', 'congeneres']]
  ] },
  { id: 'reactif8', sp: 'dog', icon: '🐕‍🦺', title: 'Programme chien réactif : 8 semaines', sub: 'Des croisements sereins, pas à pas', weeks: [
    ['Semaines 1 et 2', 'Attention et récompense', ['marqueur', 'focus']],
    ['Semaines 3 et 4', 'Le calme et la maîtrise de soi', ['impulsions', 'place']],
    ['Semaines 5 et 6', 'Croiser sans réagir', ['reactivite', 'stop']],
    ['Semaines 7 et 8', 'Rencontres et balades', ['congeneres', 'laisse']]
  ] },
  { id: 'maison4', sp: 'dog', icon: '🏠', title: 'Programme maison paisible : 4 semaines', sub: 'Fini les vols, les dégâts et les mendicités', weeks: [
    ['Semaine 1', 'Sécuriser et occuper', ['destruction', 'caisse']],
    ['Semaine 2', 'La cuisine sous contrôle', ['vol', 'laisse-le']],
    ['Semaine 3', 'La place et l’attente', ['place', 'attente']],
    ['Semaine 4', 'Santé au quotidien', ['dents', 'manipulations']]
  ] }
);
